//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class IBAColorFormat, NSColor, NSString;

@interface _TtC6Reveal23ColorInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: color
    // Error parsing type: , name: colorFormat
    // Error parsing type: , name: colorFormats
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic, retain) IBAColorFormat *colorFormat; // @synthesize colorFormat;
@property(nonatomic, copy) NSString *colorCode;
@property(nonatomic, retain) NSColor *color; // @synthesize color;

@end

