//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Reveal20RevealDocumentLoader : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: refreshProgress
    // Error parsing type: , name: dataService
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: initialImagesEnqueued
    // Error parsing type: , name: editSequenceNumber
}

- (void).cxx_destruct;
- (id)init;

@end

