//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface _TtC6Reveal30DemanglingAttributeTransformer : NSValueTransformer
{
    // Error parsing type: , name: demangler
}

+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
- (void).cxx_destruct;
- (id)init;
- (id)transformedValue:(id)arg1;

@end

