//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface _TtC6Reveal30InspectorSectionViewController : NSViewController
{
    // Error parsing type: , name: elements
    // Error parsing type: , name: headerNib
    // Error parsing type: , name: separatorNib
    // Error parsing type: , name: edgeInsets
    // Error parsing type: , name: isRootSection
    // Error parsing type: , name: elementContents
    // Error parsing type: , name: isEmpty
    // Error parsing type: , name: elementsDisposeBag
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) BOOL isEmpty; // @synthesize isEmpty;
- (void)viewDidLoad;
- (void)loadView;

@end

