//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumberFormatter.h>

@class NSNumber;

@interface _TtC6Reveal27DefaultValueNumberFormatter : NSNumberFormatter
{
    // Error parsing type: , name: defaultValue
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 range:(struct _NSRange *)arg3 error:(id *)arg4;
@property(nonatomic, retain) NSNumber *defaultValue; // @synthesize defaultValue;

@end

