//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal29DualNumberFieldViewController.h"

@interface _TtC6Reveal41LocationCoordinateInspectorViewController : _TtC6Reveal29DualNumberFieldViewController
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;

@end

