//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface _TtC6Reveal22FilterFieldPopUpButton : NSPopUpButton
{
}

+ (void)setCellClass:(Class)arg1;
+ (Class)cellClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 pullsDown:(BOOL)arg2;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;

@end

