//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevMateKit/DMWelcomeStepController.h>

@class NSDateFormatter, NSTextField, NSView;

@interface _TtC6Reveal40AnnualSupportStatusWelcomeStepController : DMWelcomeStepController
{
    // Error parsing type: , name: dateFormatter
    // Error parsing type: , name: darkContainerView
    // Error parsing type: , name: lightContainerView
    // Error parsing type: , name: activateTitleField
    // Error parsing type: , name: activateMessageField
    // Error parsing type: , name: renewTitleField
    // Error parsing type: , name: renewMessageField
    // Error parsing type: , name: continueTitleField
    // Error parsing type: , name: continueMessageField
    // Error parsing type: , name: licenseInfo
}

+ (id)defaultNibName;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)cancel:(id)arg1;
- (void)updateUIElements;
- (void)restoreState:(id)arg1;
@property(nonatomic, retain) NSTextField *continueMessageField; // @synthesize continueMessageField;
@property(nonatomic, retain) NSTextField *continueTitleField; // @synthesize continueTitleField;
@property(nonatomic, retain) NSTextField *renewMessageField; // @synthesize renewMessageField;
@property(nonatomic, retain) NSTextField *renewTitleField; // @synthesize renewTitleField;
@property(nonatomic, retain) NSTextField *activateMessageField; // @synthesize activateMessageField;
@property(nonatomic, retain) NSTextField *activateTitleField; // @synthesize activateTitleField;
@property(nonatomic, retain) NSView *lightContainerView; // @synthesize lightContainerView;
@property(nonatomic, retain) NSView *darkContainerView; // @synthesize darkContainerView;
@property(nonatomic, retain) NSDateFormatter *dateFormatter; // @synthesize dateFormatter;

@end

