//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@interface _TtC6Reveal33ConnectionPopoverWindowController : NSWindowController
{
    // Error parsing type: , name: parentWindow
    // Error parsing type: , name: passthroughViews
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: localDismissEventMonitor
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)dismissConnectionList:(id)arg1;
- (void)close;
- (void)showWindow:(id)arg1;
- (void)windowDidLoad;

@end

