//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSToolbarItem.h>

@class NSControl;

@interface _TtC6Reveal24CustomControlToolbarItem : NSToolbarItem
{
    // Error parsing type: , name: control
}

- (void).cxx_destruct;
- (id)initWithItemIdentifier:(id)arg1;
- (void)validate;
@property(nonatomic) __weak NSControl *control; // @synthesize control;

@end

