//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSString;

@interface _TtC6Reveal23PointInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: x
    // Error parsing type: , name: y
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: xMin
    // Error parsing type: , name: xMax
    // Error parsing type: , name: yMin
    // Error parsing type: , name: yMax
}

- (void).cxx_destruct;
@property(nonatomic) double yMax; // @synthesize yMax;
@property(nonatomic) double yMin; // @synthesize yMin;
@property(nonatomic) double xMax; // @synthesize xMax;
@property(nonatomic) double xMin; // @synthesize xMin;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic) double y; // @synthesize y;
@property(nonatomic) double x; // @synthesize x;

@end

