//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSPathControlDelegate-Protocol.h"

@class IBARevealViewHierarchyPathControl, NSSegmentedControl;

@interface _TtC6Reveal21ContentViewController : NSViewController <NSPathControlDelegate>
{
    // Error parsing type: , name: viewFocusHistoryControl
    // Error parsing type: , name: viewFocusPathControl
    // Error parsing type: , name: presentationStateControllerDisposeBag
    // Error parsing type: , name: notificationDisposeBag
    // Error parsing type: , name: presentationStateController
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)pathControl:(id)arg1 acceptDrop:(id)arg2;
- (unsigned long long)pathControl:(id)arg1 validateDrop:(id)arg2;
- (void)historyPathControlComponentPressed:(id)arg1;
- (void)historyNavigationButtonPressed:(id)arg1;
@property(nonatomic, retain) IBARevealViewHierarchyPathControl *viewFocusPathControl; // @synthesize viewFocusPathControl;
@property(nonatomic, retain) NSSegmentedControl *viewFocusHistoryControl; // @synthesize viewFocusHistoryControl;

@end

