//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC6Reveal19AMNotificationProxyP33_60D9FCA553357FDE7823C1FEDBFE940819ProxyObserverAction : _TtCs12_SwiftObject
{
    // Error parsing type: , name: block
    // Error parsing type: , name: token
}

@end

