//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6Reveal23USBAdvertiserConnection : _TtCs12_SwiftObject
{
    // Error parsing type: , name: device
    // Error parsing type: , name: advertiserPort
    // Error parsing type: , name: resolvedService
    // Error parsing type: , name: relayedService
    // Error parsing type: , name: advertisementDecoder
    // Error parsing type: , name: advertiserSocket.storage
    // Error parsing type: , name: relay
    // Error parsing type: , name: delegate
}

@end

