//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSApplicationDelegate-Protocol.h"
#import "NSSeguePerforming-Protocol.h"

@interface _TtC6Reveal11AppDelegate : NSObject <NSSeguePerforming, NSApplicationDelegate>
{
    // Error parsing type: , name: sampleAppLauncherWindowController.storage
}

+ (SEL)actionForShowingRevealLibraryWithSystemName:(id)arg1;
- (void).cxx_destruct;
- (id)init;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)openNewTab:(id)arg1;
- (void)openNewDocumentWindowAndInspectDemoApp:(id)arg1;
- (void)checkForUpdates:(id)arg1;
- (void)removeRevealDebuggerCommands:(id)arg1;
- (void)installRevealDebuggerCommands:(id)arg1;
- (void)showRevealLibrariesInFinder:(id)arg1;
- (void)showRevealtvOSLibraryInFinder:(id)arg1;
- (void)showRevealiOSLibraryInFinder:(id)arg1;
- (void)openResetActivationsPage:(id)arg1;
- (void)openIttyBittyAppsWebsite:(id)arg1;
- (void)openRevealWebsite:(id)arg1;
- (void)openSupportForums:(id)arg1;
- (void)openRevealFeedbackWindow:(id)arg1;
- (void)openRevealReleaseNotes:(id)arg1;
- (void)openRevealKeyboardShortcuts:(id)arg1;
- (void)openRevealIntegrationGuide:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (BOOL)application:(id)arg1 openFile:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;

@end

