//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DM_SUUpdaterDelegate-Protocol.h"

@interface _TtCC6Reveal24ApplicationUpdateServiceP33_CD8E1A6A2D4CD0ECBE35F73D1A20A96215UpdaterDelegate : NSObject <DM_SUUpdaterDelegate>
{
    // Error parsing type: , name: service
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)updaterMayCheckForUpdates:(id)arg1;
- (id)bestValidUpdateInAppcast:(id)arg1 forUpdater:(id)arg2;

@end

