//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedAttribute, IBARevealDataModel, NSString, _TtC6Reveal17RepresentedObject;

@interface _TtC6Reveal18InspectorViewModel : NSObject
{
    // Error parsing type: , name: representedAttribute
    // Error parsing type: , name: representedObject
    // Error parsing type: , name: dataModel
    // Error parsing type: , name: labelText
    // Error parsing type: , name: labelTooltipText
    // Error parsing type: , name: isEditable
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) BOOL isEmpty;
@property(nonatomic) BOOL isEditable; // @synthesize isEditable;
@property(nonatomic, copy) NSString *labelTooltipText; // @synthesize labelTooltipText;
@property(nonatomic, copy) NSString *labelText; // @synthesize labelText;
@property(nonatomic, retain) IBARevealDataModel *dataModel; // @synthesize dataModel;
@property(nonatomic, readonly) _TtC6Reveal17RepresentedObject *representedObject; // @synthesize representedObject;
@property(nonatomic, readonly) IBARepresentedAttribute *representedAttribute; // @synthesize representedAttribute;

@end

