//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

@interface _TtC6Reveal26FilterFieldPopUpButtonCell : NSPopUpButtonCell
{
    // Error parsing type: , name: disclosureArrowImage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initTextCell:(id)arg1 pullsDown:(BOOL)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

