//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class NSArrayController, NSPopUpButton;

@interface _TtC6Reveal29LocaleInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: localesArrayController
    // Error parsing type: , name: localesPopupButton
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSPopUpButton *localesPopupButton; // @synthesize localesPopupButton;
@property(nonatomic, retain) NSArrayController *localesArrayController; // @synthesize localesArrayController;

@end

