//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSObjectController, NSTextField, _TtC6Reveal18InspectorViewModel;

@interface _TtC6Reveal23InspectorViewController : NSViewController
{
    // Error parsing type: , name: labelTextField
    // Error parsing type: , name: objectController
    // Error parsing type: , name: viewModel
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) BOOL isEmpty;
@property(nonatomic, readonly) BOOL isEditable;
@property(nonatomic, retain) _TtC6Reveal18InspectorViewModel *viewModel; // @synthesize viewModel;
@property(nonatomic, retain) NSObjectController *objectController; // @synthesize objectController;
@property(nonatomic, retain) NSTextField *labelTextField; // @synthesize labelTextField;

@end

