//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class IBARevealDataModel, NSArray;

@interface _TtC6Reveal23ArrayInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: childViewModels
    // Error parsing type: , name: childObjectsAccessor
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, retain) IBARevealDataModel *dataModel;
- (void)dealloc;
@property(nonatomic, readonly) BOOL isEmpty;
@property(nonatomic, copy) NSArray *childViewModels; // @synthesize childViewModels;

@end

