//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedAttribute, _TtC6Reveal17RepresentedObject;

@interface _TtC6Reveal31RepresentedAttributeValueChange : NSObject
{
    // Error parsing type: , name: attribute
    // Error parsing type: , name: object
    // Error parsing type: , name: fromValue
    // Error parsing type: , name: toValue
}

- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(void *)arg1;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) _TtC6Reveal17RepresentedObject *object; // @synthesize object;
@property(nonatomic, readonly) IBARepresentedAttribute *attribute; // @synthesize attribute;

@end

