//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Reveal22CanvasThemeEditorModel : NSObject
{
    // Error parsing type: , name: orderedKeys
    // Error parsing type: , name: keyTitles
    // Error parsing type: , name: values
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(void *)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

