//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@class NSAttributedString, NSColor, NSString;

@interface _TtC6Reveal15ColorableButton : NSButton
{
    // Error parsing type: , name: textColor
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSAttributedString *attributedTitle;
@property(nonatomic, copy) NSString *title;
@property(nonatomic, retain) NSColor *textColor; // @synthesize textColor;
- (void)layout;

@end

