//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSString;

@interface _TtC6Reveal30DirectionalEdgeInsetsViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: top
    // Error parsing type: , name: leading
    // Error parsing type: , name: bottom
    // Error parsing type: , name: trailing
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: topMin
    // Error parsing type: , name: topMax
    // Error parsing type: , name: leadingMin
    // Error parsing type: , name: leadingMax
    // Error parsing type: , name: bottomMin
    // Error parsing type: , name: bottomMax
    // Error parsing type: , name: trailingMin
    // Error parsing type: , name: trailingMax
}

- (void).cxx_destruct;
@property(nonatomic) double trailingMax; // @synthesize trailingMax;
@property(nonatomic) double trailingMin; // @synthesize trailingMin;
@property(nonatomic) double bottomMax; // @synthesize bottomMax;
@property(nonatomic) double bottomMin; // @synthesize bottomMin;
@property(nonatomic) double leadingMax; // @synthesize leadingMax;
@property(nonatomic) double leadingMin; // @synthesize leadingMin;
@property(nonatomic) double topMax; // @synthesize topMax;
@property(nonatomic) double topMin; // @synthesize topMin;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic) double trailing; // @synthesize trailing;
@property(nonatomic) double bottom; // @synthesize bottom;
@property(nonatomic) double leading; // @synthesize leading;
@property(nonatomic) double top; // @synthesize top;

@end

