//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSString;

@interface _TtC6Reveal18InspectorTextField : NSTextField
{
    // Error parsing type: , name: label
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewDidChangeEffectiveAppearance;
- (void)textDidChange:(id)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)setFrameSize:(struct CGSize)arg1;
@property(nonatomic, copy) NSString *label; // @synthesize label;

@end

