//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSNumber, NSString;

@interface _TtC6Reveal22BoolInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: boolNumber
}

- (void).cxx_destruct;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic, retain) NSNumber *boolNumber; // @synthesize boolNumber;

@end

