//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedClass, IBARepresentedObjectIdentifier, IBARepresentedObjectModel, NSDictionary, NSString, _TtC6Reveal15RepresentedView;

@interface _TtC6Reveal17RepresentedObject : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: identifier
    // Error parsing type: , name: representedClass
    // Error parsing type: , name: attributes
    // Error parsing type: , name: objectAddress
    // Error parsing type: , name: objectModel
}

- (void).cxx_destruct;
- (id)init;
- (long long)countOfAttributes;
@property(nonatomic, readonly) NSString *debugDescription;
- (BOOL)representedClassIsSubclassOfClassNamed:(id)arg1;
- (id)valueForSyntheticAttributeWithKeyPath:(id)arg1;
- (void)addAttribute:(id)arg1;
- (id)attributeForKeyPath:(id)arg1;
- (BOOL)setAttributeValue:(id)arg1 forKeyPath:(id)arg2;
@property(nonatomic) __weak IBARepresentedObjectModel *objectModel; // @synthesize objectModel;
@property(nonatomic, copy) NSDictionary *attributes; // @synthesize attributes;
@property(nonatomic, readonly) IBARepresentedClass *representedClass; // @synthesize representedClass;
@property(nonatomic, readonly) IBARepresentedObjectIdentifier *identifier; // @synthesize identifier;
@property(nonatomic, readonly) _TtC6Reveal15RepresentedView *layoutGuideOwningView;
@property(nonatomic, readonly) BOOL isStackView;
@property(nonatomic, readonly) BOOL isGestureRecognizer;
@property(nonatomic, readonly) BOOL isLayoutGuide;
@property(nonatomic, readonly) BOOL isScreen;
@property(nonatomic, readonly) BOOL isWindow;
@property(nonatomic, readonly) BOOL isLayoutConstraint;
@property(nonatomic, readonly) BOOL isLayer;
@property(nonatomic, readonly) BOOL isView;
@property(nonatomic, readonly) BOOL layoutConstraintIsBroken;
@property(nonatomic, readonly) NSString *layoutConstraintIdentifier;
@property(nonatomic, readonly) IBARepresentedObjectIdentifier *layoutConstraintSecondItemIdentifier;
@property(nonatomic, readonly) IBARepresentedObjectIdentifier *layoutConstraintFirstItemIdentifier;
@property(nonatomic, readonly) _TtC6Reveal17RepresentedObject *layoutConstraintSecondItem;
@property(nonatomic, readonly) _TtC6Reveal17RepresentedObject *layoutConstraintFirstItem;

@end

