//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class IBALinkableInspectorTextField, NSLayoutConstraint, NSTextField;

@interface _TtC6Reveal45LayoutConstraintDetailInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: firstItemLabelTextField
    // Error parsing type: , name: secondItemLabelTextField
    // Error parsing type: , name: relationLabelTextField
    // Error parsing type: , name: constantLabelTextField
    // Error parsing type: , name: priorityLabelTextField
    // Error parsing type: , name: multiplierLabelTextField
    // Error parsing type: , name: firstItemTextField
    // Error parsing type: , name: secondItemTextField
    // Error parsing type: , name: relationTextField
    // Error parsing type: , name: constantTextField
    // Error parsing type: , name: priorityTextField
    // Error parsing type: , name: multiplierTextField
    // Error parsing type: , name: constantToSecondItemVerticalSpacing
    // Error parsing type: , name: constantToRelationVerticalSpacing
    // Error parsing type: , name: firstItemTrackingArea
    // Error parsing type: , name: secondItemTrackingArea
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)selectSecondItemPressed:(id)arg1;
- (void)selectFirstItemPressed:(id)arg1;
- (void)viewDidAppear;
- (void)viewDidLoad;
@property(nonatomic, retain) NSLayoutConstraint *constantToRelationVerticalSpacing; // @synthesize constantToRelationVerticalSpacing;
@property(nonatomic, retain) NSLayoutConstraint *constantToSecondItemVerticalSpacing; // @synthesize constantToSecondItemVerticalSpacing;
@property(nonatomic, retain) NSTextField *multiplierTextField; // @synthesize multiplierTextField;
@property(nonatomic, retain) NSTextField *priorityTextField; // @synthesize priorityTextField;
@property(nonatomic, retain) NSTextField *constantTextField; // @synthesize constantTextField;
@property(nonatomic, retain) NSTextField *relationTextField; // @synthesize relationTextField;
@property(nonatomic, retain) IBALinkableInspectorTextField *secondItemTextField; // @synthesize secondItemTextField;
@property(nonatomic, retain) IBALinkableInspectorTextField *firstItemTextField; // @synthesize firstItemTextField;
@property(nonatomic, retain) NSTextField *multiplierLabelTextField; // @synthesize multiplierLabelTextField;
@property(nonatomic, retain) NSTextField *priorityLabelTextField; // @synthesize priorityLabelTextField;
@property(nonatomic, retain) NSTextField *constantLabelTextField; // @synthesize constantLabelTextField;
@property(nonatomic, retain) NSTextField *relationLabelTextField; // @synthesize relationLabelTextField;
@property(nonatomic, retain) NSTextField *secondItemLabelTextField; // @synthesize secondItemLabelTextField;
@property(nonatomic, retain) NSTextField *firstItemLabelTextField; // @synthesize firstItemLabelTextField;

@end

