//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSCollectionViewDataSource-Protocol.h"
#import "NSCollectionViewDelegate-Protocol.h"

@class IBADocumentController, NSCollectionView, _TtC6Reveal12CursorButton;
@protocol IBARevealConnectionListViewControllerDelegate;

@interface _TtC6Reveal28ConnectionListViewController : NSViewController <NSCollectionViewDataSource, NSCollectionViewDelegate>
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: helpTextButton
    // Error parsing type: , name: helpButton
    // Error parsing type: , name: documentController
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)collectionView:(id)arg1 itemForRepresentedObjectAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic) __weak id <IBARevealConnectionListViewControllerDelegate> delegate; // @synthesize delegate;
@property(nonatomic, retain) IBADocumentController *documentController; // @synthesize documentController;
@property(nonatomic, retain) _TtC6Reveal12CursorButton *helpButton; // @synthesize helpButton;
@property(nonatomic, retain) _TtC6Reveal12CursorButton *helpTextButton; // @synthesize helpTextButton;
@property(nonatomic, retain) NSCollectionView *collectionView; // @synthesize collectionView;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)makeTouchBar;
- (id)scrubber:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsForScrubber:(id)arg1;
- (void)scrubber:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (struct CGSize)scrubber:(id)arg1 layout:(id)arg2 sizeForItemAtIndex:(long long)arg3;

@end

