//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6Reveal27SegmentedControlHoverAspect : _TtCs12_SwiftObject
{
    // Error parsing type: , name: owner
    // Error parsing type: , name: delegate
    // Error parsing type: , name: baseHoverAspect
    // Error parsing type: , name: lastHoveredSegment
}

- (void)hoverableView:(id)arg1 mouseDidExitWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidMoveWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidEnterWithEvent:(id)arg2;

@end

