//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class IBARevealDataModel, NSArray;

@interface _TtC6Reveal22FontInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: availableFontFamilies
    // Error parsing type: , name: availableFonts
    // Error parsing type: , name: minimumFontSize
    // Error parsing type: , name: maximumFontSize
    // Error parsing type: , name: selectedFontSize
    // Error parsing type: , name: selectedFontFamilyIndex
    // Error parsing type: , name: selectedFontIndex
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: selectedFontValue
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void).cxx_destruct;
- (BOOL)validateValue:(id *)arg1 forKey:(id)arg2 error:(id *)arg3;
- (void)dealloc;
@property(nonatomic) long long selectedFontIndex; // @synthesize selectedFontIndex;
@property(nonatomic) long long selectedFontFamilyIndex; // @synthesize selectedFontFamilyIndex;
@property(nonatomic) double selectedFontSize; // @synthesize selectedFontSize;
@property(nonatomic, readonly) long long maximumFontSize; // @synthesize maximumFontSize;
@property(nonatomic, readonly) long long minimumFontSize; // @synthesize minimumFontSize;
@property(nonatomic, retain) IBARevealDataModel *dataModel;
@property(nonatomic, copy) NSArray *availableFonts; // @synthesize availableFonts;
@property(nonatomic, copy) NSArray *availableFontFamilies; // @synthesize availableFontFamilies;

@end

