//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"

@class NSString;

@interface _TtC6Reveal17RevealDataService : NSObject <NSURLSessionDataDelegate>
{
    // Error parsing type: , name: baseURL
    // Error parsing type: , name: serialHttpSession
    // Error parsing type: , name: serialServiceQueue
    // Error parsing type: , name: imageHttpSession
    // Error parsing type: , name: imageDownloadingQueue
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;

@end

