//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSScrubberItemView.h>

@class IBAInspectableApplicationIconView, NSTextField;

@interface _TtC6Reveal26ConnectionScrubberItemView : NSScrubberItemView
{
    // Error parsing type: , name: application
    // Error parsing type: , name: applicationIconView
    // Error parsing type: , name: applicationNameLabel
    // Error parsing type: , name: disposeBag
}

- (CDUnknownBlockType).cxx_destruct;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *applicationNameLabel; // @synthesize applicationNameLabel;
@property(nonatomic, retain) IBAInspectableApplicationIconView *applicationIconView; // @synthesize applicationIconView;

@end

