//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class WebView;

@interface _TtC6Reveal23LicenseWindowController : NSWindowController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: licenseWebView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)acceptLicense:(id)arg1;
- (void)doNotAcceptLicense:(id)arg1;
- (void)windowDidLoad;
@property(nonatomic, retain) WebView *licenseWebView; // @synthesize licenseWebView;

@end

