//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSString;

@interface _TtC6Reveal19EdgeInsetsViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: top
    // Error parsing type: , name: left
    // Error parsing type: , name: bottom
    // Error parsing type: , name: right
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: topMin
    // Error parsing type: , name: topMax
    // Error parsing type: , name: leftMin
    // Error parsing type: , name: leftMax
    // Error parsing type: , name: bottomMin
    // Error parsing type: , name: bottomMax
    // Error parsing type: , name: rightMin
    // Error parsing type: , name: rightMax
}

- (void).cxx_destruct;
@property(nonatomic) double rightMax; // @synthesize rightMax;
@property(nonatomic) double rightMin; // @synthesize rightMin;
@property(nonatomic) double bottomMax; // @synthesize bottomMax;
@property(nonatomic) double bottomMin; // @synthesize bottomMin;
@property(nonatomic) double leftMax; // @synthesize leftMax;
@property(nonatomic) double leftMin; // @synthesize leftMin;
@property(nonatomic) double topMax; // @synthesize topMax;
@property(nonatomic) double topMin; // @synthesize topMin;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic) double right; // @synthesize right;
@property(nonatomic) double bottom; // @synthesize bottom;
@property(nonatomic) double left; // @synthesize left;
@property(nonatomic) double top; // @synthesize top;

@end

