//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSLevelIndicator.h>

@class NSColor, NSTextField;

@interface _TtC6Reveal34LicensePeriodProgressIndicatorView : NSLevelIndicator
{
    // Error parsing type: , name: daysRemainingTextColorForLeft
    // Error parsing type: , name: daysRemainingTextColorForRight
    // Error parsing type: , name: licensePeriod
    // Error parsing type: , name: dateComponentsFormatter.storage
    // Error parsing type: , name: daysRemainingLabel
}

- (void).cxx_destruct;
- (void)layout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *daysRemainingLabel; // @synthesize daysRemainingLabel;
@property(nonatomic, retain) NSColor *daysRemainingTextColorForRight; // @synthesize daysRemainingTextColorForRight;
@property(nonatomic, retain) NSColor *daysRemainingTextColorForLeft; // @synthesize daysRemainingTextColorForLeft;

@end

