//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton, NSSlider, NSTextField;

@interface _TtC6Reveal25DeveloperWindowController : NSWindowController
{
    // Error parsing type: , name: canvas3DZDepthSlider
    // Error parsing type: , name: canvas3DZDepthTextField
    // Error parsing type: , name: sceneStatisticsEnabledButton
    // Error parsing type: , name: canvasRotateFromTextField
    // Error parsing type: , name: canvasRotateToTextField
    // Error parsing type: , name: canvasRotateDurationTextField
    // Error parsing type: , name: canvasRotateDelayTextField
    // Error parsing type: , name: canvasRotateLinear
    // Error parsing type: , name: focusHistoryReplayDuration
    // Error parsing type: , name: focusHistoryReplayDelay
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)updateGeometrySortOrder:(id)arg1;
- (void)sceneKitStatisticsEnabledDidChange:(id)arg1;
- (void)resetUserLicenseAcceptance:(id)arg1;
- (void)forceCrash:(id)arg1;
- (void)replayFocusHistory:(id)arg1;
- (void)rotateCanvas:(id)arg1;
- (void)resetCanvasPan:(id)arg1;
- (void)dumpSCNNodeHierarchy:(id)arg1;
- (void)dumpSceneNodeHierarchy:(id)arg1;
- (void)canvas3DZDepthTextFieldChanged:(id)arg1;
- (void)canvas3DZDepthSliderValueChanged:(id)arg1;
- (void)windowDidLoad;
@property(nonatomic, retain) NSTextField *focusHistoryReplayDelay; // @synthesize focusHistoryReplayDelay;
@property(nonatomic, retain) NSTextField *focusHistoryReplayDuration; // @synthesize focusHistoryReplayDuration;
@property(nonatomic, retain) NSButton *canvasRotateLinear; // @synthesize canvasRotateLinear;
@property(nonatomic, retain) NSTextField *canvasRotateDelayTextField; // @synthesize canvasRotateDelayTextField;
@property(nonatomic, retain) NSTextField *canvasRotateDurationTextField; // @synthesize canvasRotateDurationTextField;
@property(nonatomic, retain) NSTextField *canvasRotateToTextField; // @synthesize canvasRotateToTextField;
@property(nonatomic, retain) NSTextField *canvasRotateFromTextField; // @synthesize canvasRotateFromTextField;
@property(nonatomic, retain) NSButton *sceneStatisticsEnabledButton; // @synthesize sceneStatisticsEnabledButton;
@property(nonatomic, retain) NSTextField *canvas3DZDepthTextField; // @synthesize canvas3DZDepthTextField;
@property(nonatomic, retain) NSSlider *canvas3DZDepthSlider; // @synthesize canvas3DZDepthSlider;

@end

