//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _TtC6Reveal32RepresentedObjectGroupIdentifier;

@interface _TtC6Reveal22ViewHierarchyNodeGroup : NSObject
{
    // Error parsing type: , name: containerNode
    // Error parsing type: , name: groupIdentifier
    // Error parsing type: , name: nodes
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _TtC6Reveal32RepresentedObjectGroupIdentifier *groupIdentifier; // @synthesize groupIdentifier;

@end

