//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6Reveal18MobileDeviceAccess : _TtCs12_SwiftObject
{
    // Error parsing type: , name: devices
    // Error parsing type: , name: quarantinedDeviceConnectionIDs
    // Error parsing type: , name: isSubscribed
    // Error parsing type: , name: deviceNotification
    // Error parsing type: , name: terminationNotificationToken
    // Error parsing type: , name: listener
}

@end

