//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindow.h>

@class NSView;

@interface _TtC6Reveal23ConnectionPopoverWindow : NSWindow
{
    // Error parsing type: , name: backgroundView
}

- (void).cxx_destruct;
@property(nonatomic, retain) NSView *contentView;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;

@end

