//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class IBARepresentedObjectIdentifier, NSString;

@interface _TtC6Reveal34ObjectIdentifierInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: objectIdentifier
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) BOOL isEditable;
@property(nonatomic, readonly) NSString *displayValue;
@property(nonatomic, retain) IBARepresentedObjectIdentifier *objectIdentifier; // @synthesize objectIdentifier;

@end

