//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedType.h"

@interface _TtC6Reveal22RepresentedEnumeration : IBARepresentedType
{
    // Error parsing type: , name: cases
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithName:(id)arg1 objCType:(id)arg2;

@end

