//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSDocument.h>

@class IBARevealDataModel, NSImage, NSScriptObjectSpecifier, NSString, _TtC6Reveal22InspectableApplication, _TtC6Reveal24DocumentWindowController;

@interface _TtC6Reveal14RevealDocument : NSDocument
{
    // Error parsing type: , name: dataModel
    // Error parsing type: , name: applicationIcon
    // Error parsing type: , name: applicationName
    // Error parsing type: , name: cachedInspectableApplicationDisplayName
    // Error parsing type: , name: loader
    // Error parsing type: , name: state
    // Error parsing type: , name: inspectableApplication
    // Error parsing type: , name: notificationCenter
    // Error parsing type: , name: notificationQueue
    // Error parsing type: , name: iconDidUpdateNotificationToken
    // Error parsing type: , name: shouldSuppressServerAttributeChangeUpdates
    // Error parsing type: , name: observerNotificationTokens
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)preservesVersions;
+ (BOOL)autosavesInPlace;
+ (BOOL)autosavesDrafts;
- (void).cxx_destruct;
- (void)refreshApplicationStateSnapshotWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;
@property(nonatomic, retain) _TtC6Reveal22InspectableApplication *inspectableApplication; // @synthesize inspectableApplication;
@property(nonatomic) long long state; // @synthesize state;
@property(nonatomic, readonly) NSString *applicationDisplayName;
@property(nonatomic, copy) NSString *cachedInspectableApplicationDisplayName; // @synthesize cachedInspectableApplicationDisplayName;
@property(nonatomic, copy) NSString *applicationName; // @synthesize applicationName;
@property(nonatomic, retain) NSImage *applicationIcon; // @synthesize applicationIcon;
@property(nonatomic, retain) IBARevealDataModel *dataModel; // @synthesize dataModel;
- (BOOL)matchesApplication:(id)arg1;
@property(nonatomic, readonly) NSScriptObjectSpecifier *objectSpecifier;
@property(nonatomic, readonly) BOOL isEditable;
- (BOOL)isDocumentEdited;
@property(nonatomic, readonly) BOOL isLoadedFromDisk;
@property(nonatomic, readonly) BOOL isRefreshing;
@property(nonatomic, readonly) BOOL isConnected;
@property(nonatomic, readonly) BOOL hasLoadedApplication;
@property(nonatomic, readonly) BOOL canPerformRefresh;
- (BOOL)readFromFileWrapper:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (id)fileWrapperOfType:(id)arg1 error:(id *)arg2;
- (BOOL)canAsynchronouslyWriteToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3;
- (id)handleSaveScriptCommand:(id)arg1;
- (void)saveDocumentTo:(id)arg1;
- (void)saveDocumentAs:(id)arg1;
- (void)saveDocument:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
@property(nonatomic, readonly) _TtC6Reveal24DocumentWindowController *mainWindowController;
- (void)makeWindowControllers;
- (id)handleRefreshScriptCommand:(id)arg1;

// Remaining properties
@property(nonatomic, readonly) BOOL documentEdited;

@end

