//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class NSPopUpButton, NSStepper, NSTextField;

@interface _TtC6Reveal27FontInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: fontFamilyPopUpButton
    // Error parsing type: , name: fontPopUpButton
    // Error parsing type: , name: fontSizeTextField
    // Error parsing type: , name: fontSizeStepper
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSStepper *fontSizeStepper; // @synthesize fontSizeStepper;
@property(nonatomic, retain) NSTextField *fontSizeTextField; // @synthesize fontSizeTextField;
@property(nonatomic, retain) NSPopUpButton *fontPopUpButton; // @synthesize fontPopUpButton;
@property(nonatomic, retain) NSPopUpButton *fontFamilyPopUpButton; // @synthesize fontFamilyPopUpButton;

@end

