//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSColorWell;

@interface _TtC6Reveal34CanvasThemeEditorColorWellCellView : NSTableCellView
{
    // Error parsing type: , name: colorWell
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSColorWell *colorWell; // @synthesize colorWell;

@end

