//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class NSStepper, _TtC6Reveal18InspectorTextField;

@interface _TtC6Reveal29DualNumberFieldViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: firstTextField
    // Error parsing type: , name: secondTextField
    // Error parsing type: , name: firstStepper
    // Error parsing type: , name: secondStepper
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSStepper *secondStepper; // @synthesize secondStepper;
@property(nonatomic, retain) NSStepper *firstStepper; // @synthesize firstStepper;
@property(nonatomic, retain) _TtC6Reveal18InspectorTextField *secondTextField; // @synthesize secondTextField;
@property(nonatomic, retain) _TtC6Reveal18InspectorTextField *firstTextField; // @synthesize firstTextField;

@end

