//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSString;

@interface _TtC6Reveal37MapCoordinateRegionInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: centerLongitude
    // Error parsing type: , name: centerLatitude
    // Error parsing type: , name: spanLongitudeDelta
    // Error parsing type: , name: spanLatitudeDelta
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: centerLatitudeMin
    // Error parsing type: , name: centerLatitudeMax
    // Error parsing type: , name: centerLongitudeMin
    // Error parsing type: , name: centerLongitudeMax
    // Error parsing type: , name: spanLongitudeDeltaMin
    // Error parsing type: , name: spanLongitudeDeltaMax
    // Error parsing type: , name: spanLatitudeDeltaMin
    // Error parsing type: , name: spanLatitudeDeltaMax
}

- (void).cxx_destruct;
@property(nonatomic) double spanLatitudeDeltaMax; // @synthesize spanLatitudeDeltaMax;
@property(nonatomic) double spanLatitudeDeltaMin; // @synthesize spanLatitudeDeltaMin;
@property(nonatomic) double spanLongitudeDeltaMax; // @synthesize spanLongitudeDeltaMax;
@property(nonatomic) double spanLongitudeDeltaMin; // @synthesize spanLongitudeDeltaMin;
@property(nonatomic) double centerLongitudeMax; // @synthesize centerLongitudeMax;
@property(nonatomic) double centerLongitudeMin; // @synthesize centerLongitudeMin;
@property(nonatomic) double centerLatitudeMax; // @synthesize centerLatitudeMax;
@property(nonatomic) double centerLatitudeMin; // @synthesize centerLatitudeMin;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic) double spanLatitudeDelta; // @synthesize spanLatitudeDelta;
@property(nonatomic) double spanLongitudeDelta; // @synthesize spanLongitudeDelta;
@property(nonatomic) double centerLatitude; // @synthesize centerLatitude;
@property(nonatomic) double centerLongitude; // @synthesize centerLongitude;

@end

