//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTouchBar.h>

#import "NSScrubberDataSource-Protocol.h"
#import "NSScrubberFlowLayoutDelegate-Protocol.h"

@interface _TtC6Reveal21FilterFieldPopoverBar : NSTouchBar <NSScrubberFlowLayoutDelegate, NSScrubberDataSource>
{
    // Error parsing type: , name: presentingItem
    // Error parsing type: , name: selectedOption
    // Error parsing type: , name: availableOptions
    // Error parsing type: , name: disposeBag
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (struct CGSize)scrubber:(id)arg1 layout:(id)arg2 sizeForItemAtIndex:(long long)arg3;
- (id)scrubber:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsForScrubber:(id)arg1;
- (void)scrubber:(id)arg1 didSelectItemAtIndex:(long long)arg2;

@end

