//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSplitViewController.h>

@class NSSplitViewItem, _TtC6Reveal26ContentSplitViewController;

@interface _TtC6Reveal31DocumentRootSplitViewController : NSSplitViewController
{
    // Error parsing type: , name: contentSplitViewItem
    // Error parsing type: , name: inspectorsSplitViewItem
    // Error parsing type: , name: filterFieldViewModel
    // Error parsing type: , name: presentationStateMemento
    // Error parsing type: , name: previousCanvasState
    // Error parsing type: , name: previousOutlineViewState
    // Error parsing type: , name: previousInspectorViewState
    // Error parsing type: , name: outlineViewController
    // Error parsing type: , name: viewHierarchyCanvasViewController
    // Error parsing type: , name: inspectorScopeViewController
    // Error parsing type: , name: filterFieldViewController
    // Error parsing type: , name: presentationStateController
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;
- (void)viewDidLoad;
- (void)dealloc;
@property(nonatomic, retain) NSSplitViewItem *inspectorsSplitViewItem; // @synthesize inspectorsSplitViewItem;
@property(nonatomic, retain) NSSplitViewItem *contentSplitViewItem; // @synthesize contentSplitViewItem;
- (void)updateToggleHierarchyOutlineMenuItem:(id)arg1;
- (void)toggleHierarchyOutline:(id)arg1;
- (void)resetCanvasCamera:(id)arg1;
- (void)toggleShowAutoLayout:(id)arg1;
- (void)selectHiddenItemOpacityWithMenuItem:(id)arg1;
- (void)toggleDisplayExcludedItems:(id)arg1;
- (void)toggleDisplayHiddenItems:(id)arg1;
- (void)toggle3DMode:(id)arg1;
- (void)toggle2DMode:(id)arg1;
- (void)switchPerspective:(id)arg1;
- (void)toggleSubviewContentVisible:(id)arg1;
- (void)toggleSubviewFramesVisible:(id)arg1;
- (void)toggleSubviewFramesAndContentVisible:(id)arg1;
- (void)switchRenderingMode:(id)arg1;
- (void)copy:(id)arg1;
- (void)focusFilterField:(id)arg1;
- (void)goForwardInViewSelectionHistory:(id)arg1;
- (void)goBackInViewSelectionHistory:(id)arg1;
- (void)goForwardInViewFocusHistory:(id)arg1;
- (void)goBackInViewFocusHistory:(id)arg1;
- (void)setDisplaysExcludedItems:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL displaysExcludedItems;
- (void)setDisplaysHiddenItems:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL displaysHiddenItems;
- (void)setDisplaysAutoLayout:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL displaysAutoLayout;
- (void)focusOnSelectedItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)showLayoutInspector:(id)arg1;
- (void)showAttributesInspector:(id)arg1;
- (void)showIdentityInspector:(id)arg1;
- (void)showApplicationInspector:(id)arg1;
- (void)showViewScope:(id)arg1;
- (void)updateToggleInspectorsMenuItem:(id)arg1;
- (void)toggleInspectors:(id)arg1;
- (void)handleSplitViewResized:(id)arg1;
- (void)endObservingSplitViews;
- (void)beginObservingSplitViews;
@property(nonatomic) BOOL inspectorsShown;
@property(nonatomic) BOOL hierarchyOutlineShown;
@property(nonatomic, readonly) NSSplitViewItem *hierarchyOutlineSplitViewItem;
@property(nonatomic, readonly) _TtC6Reveal26ContentSplitViewController *contentSplitViewController;
- (void)decreaseZDepth:(id)arg1;
- (void)increaseZDepth:(id)arg1;
- (void)zoomToActualSize:(id)arg1;
- (void)zoomToFitScene:(id)arg1;
- (void)zoomToFitSelected:(id)arg1;
- (void)zoomOut:(id)arg1;
- (void)zoomIn:(id)arg1;
- (void)selectPreviousObjectWithLayoutIssue:(id)arg1;
- (void)selectNextObjectWithLayoutIssue:(id)arg1;
- (void)selectPreviousFilterMatch:(id)arg1;
- (void)selectNextFilterMatch:(id)arg1;
- (void)selectNextSibling:(id)arg1;
- (void)selectPreviousSibling:(id)arg1;
- (void)selectFirstChild:(id)arg1;
- (void)selectParent:(id)arg1;
- (void)performDeveloperExport:(id)arg1;
- (void)toggleSmartMeasurements:(id)arg1;

@end

