//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

@interface _TtC6Reveal33IBAInclusivePresentationStateShim : NSObject
{
    // Error parsing type: , name: target
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (BOOL)isStateSetForViewHierarchyNode:(id)arg1;
- (BOOL)isStateSetForIdentifier:(id)arg1;
@property(nonatomic, copy) NSSet *viewHierarchyNodesWithState;
@property(nonatomic, copy) NSSet *identifiersWithState;
- (void)clearState;

@end

