//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class NSTextField;

@interface _TtC6Reveal33ScreenModeInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: secondaryLabelTextField
    // Error parsing type: , name: pixelAspectRatioField
    // Error parsing type: , name: widthField
    // Error parsing type: , name: heightField
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSTextField *heightField; // @synthesize heightField;
@property(nonatomic, retain) NSTextField *widthField; // @synthesize widthField;
@property(nonatomic, retain) NSTextField *pixelAspectRatioField; // @synthesize pixelAspectRatioField;
@property(nonatomic, retain) NSTextField *secondaryLabelTextField; // @synthesize secondaryLabelTextField;

@end

