//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSControl.h>

@interface _TtC6Reveal18HighlightContainer : NSControl
{
    // Error parsing type: , name: shouldHighlightSubviews
    // Error parsing type: , name: _highlighted
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
@property(nonatomic) BOOL highlighted;
- (BOOL)isHighlighted;
@property(nonatomic) BOOL shouldHighlightSubviews; // @synthesize shouldHighlightSubviews;

@end

