//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSImageView, NSTextField;

@interface _TtC6Reveal29LayoutIssuesInspectorItemView : NSView
{
    // Error parsing type: , name: iconImageView
    // Error parsing type: , name: descriptionTextField
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *descriptionTextField; // @synthesize descriptionTextField;
@property(nonatomic, retain) NSImageView *iconImageView; // @synthesize iconImageView;

@end

