//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAArrayInspectorViewModel.h"

@class IBARevealDataModel;

@interface _TtC6Reveal42ParticipatingConstraintsInspectorViewModel : IBAArrayInspectorViewModel
{
    // Error parsing type: , name: disposeBag
}

+ (BOOL)canModelRepresentedType:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithRepresentedObject:(id)arg1 childObjectsAccessor:(CDUnknownBlockType)arg2;
@property(nonatomic, retain) IBARevealDataModel *dataModel;
- (void)reloadChildViewModels;

@end

