//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class IBARevealDataModel, NSArray, NSString;

@interface _TtC6Reveal24LocaleInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: localeChoices
    // Error parsing type: , name: selectedLocaleIdentifier
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
}

- (void).cxx_destruct;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic, retain) IBARevealDataModel *dataModel;
@property(nonatomic, copy) NSString *selectedLocaleIdentifier; // @synthesize selectedLocaleIdentifier;
@property(nonatomic, copy) NSArray *localeChoices; // @synthesize localeChoices;

@end

