//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSDocumentController.h>

#import "NSMenuDelegate-Protocol.h"

@class NSArray;

@interface _TtC6Reveal18DocumentController : NSDocumentController <NSMenuDelegate>
{
    // Error parsing type: , name: applicationBrowser
    // Error parsing type: , name: availableApplications
    // Error parsing type: , name: autoSelectionMatcher
    // Error parsing type: , name: autoSelectionCompletionHandler
    // Error parsing type: , name: autoSelectionTargetDocument
    // Error parsing type: , name: autoSelectionTimeoutTimer
    // Error parsing type: , name: autoSelectionDelayTimer
    // Error parsing type: , name: pendingDocumentsCount
}

+ (id)sharedDocumentController;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void).cxx_destruct;
- (void)newDocument:(id)arg1;
- (void)reopenDocumentForURL:(id)arg1 withContentsOfURL:(id)arg2 display:(BOOL)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)openDocumentWithContentsOfURL:(id)arg1 display:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)emptyOrNewRevealDocument;
- (id)revealDocumentPassingTest:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic, readonly) BOOL isAvailableApplicationsEmpty;
@property(nonatomic, readonly) long long countOfAvailableApplications;
@property(nonatomic, copy) NSArray *availableApplications; // @synthesize availableApplications;
- (void)connectToServiceUsingFrontmostDocument:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
@property(nonatomic, readonly) BOOL connectionMenuItemsEnabled;
- (BOOL)validateMenuItem:(id)arg1;
- (void)autoSelectApplicationPassingTest:(CDUnknownBlockType)arg1 withTimeout:(double)arg2 delay:(double)arg3 inDocument:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
@property(nonatomic, readonly) BOOL isAutoSelectionPending;

@end

