//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

#import "IBAGCDAsyncSocketDelegate-Protocol.h"

@interface _TtC6RevealP33_1FF42DC1AD0DBEE08EB38B8BC1C178C816USBServiceTunnel : _TtCs12_SwiftObject <IBAGCDAsyncSocketDelegate>
{
    // Error parsing type: , name: incomingSocket
    // Error parsing type: , name: outgoingSocket
    // Error parsing type: , name: isValid
    // Error parsing type: , name: delegate
}

- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;

@end

