//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

@class IBAInspectableApplicationIconView, NSImageView, _TtC6Reveal27HoverableHighlightContainer;

@interface _TtC6Reveal28ConnectionCollectionViewItem : NSCollectionViewItem
{
    // Error parsing type: , name: highlightContainer
    // Error parsing type: , name: applicationIconView
    // Error parsing type: , name: connectionTypeOverlayImageView
    // Error parsing type: , name: extensionTypeOverlayImageView
    // Error parsing type: , name: delegate
    // Error parsing type: , name: disposeBag
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)itemViewClicked:(id)arg1;
- (void)viewWillAppear;
- (void)prepareForReuse;
- (void)awakeFromNib;
@property(nonatomic, copy) id representedObject;
@property(nonatomic, retain) NSImageView *extensionTypeOverlayImageView; // @synthesize extensionTypeOverlayImageView;
@property(nonatomic, retain) NSImageView *connectionTypeOverlayImageView; // @synthesize connectionTypeOverlayImageView;
@property(nonatomic, retain) IBAInspectableApplicationIconView *applicationIconView; // @synthesize applicationIconView;
@property(nonatomic, retain) _TtC6Reveal27HoverableHighlightContainer *highlightContainer; // @synthesize highlightContainer;

@end

