//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSSegmentedControl;

@interface _TtC6Reveal28InspectorScopeViewController : NSViewController
{
    // Error parsing type: , name: scopeSegmentedControl
    // Error parsing type: , name: tabBarController
    // Error parsing type: , name: presentationStateController
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic) __weak NSSegmentedControl *scopeSegmentedControl; // @synthesize scopeSegmentedControl;

@end

