//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23NetworkRequestOperation.h"

@class NSError;

@interface _TtC6Reveal25ImageDataRequestOperation : _TtC6Reveal23NetworkRequestOperation
{
    // Error parsing type: , name: imageData
}

- (void).cxx_destruct;
- (void)main;
@property(nonatomic, readonly) NSError *dataServiceError;

@end

