//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Reveal20FilterFieldViewModel : SwiftObject
{
    // Error parsing type: , name: presentationStateController
    // Error parsing type: , name: filterQuery
    // Error parsing type: , name: filterOptions
    // Error parsing type: , name: shortcutMatcher
    // Error parsing type: , name: _filterControlsEnabled
    // Error parsing type: , name: disposeBag
}

@end

