//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DMTrackingReporterInfoProvider-Protocol.h"

@interface _TtCC6Reveal21TrackingReportServiceP33_C9FCE52BC941D695AE2076396093F23E28TrackingReporterInfoProvider : NSObject <DMTrackingReporterInfoProvider>
{
}

- (id)init;
- (struct _DMAppTrialValue)applicationTrialValue:(id)arg1;
- (unsigned long long)applicationActivationStatus:(id)arg1;

@end

