//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal28ConnectionListViewController.h"

@class NSLayoutConstraint;

@interface _TtC6Reveal31ConnectionPopoverViewController : _TtC6Reveal28ConnectionListViewController
{
    // Error parsing type: , name: collectionScrollViewHeightConstraint
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic, retain) NSLayoutConstraint *collectionScrollViewHeightConstraint; // @synthesize collectionScrollViewHeightConstraint;

@end

