//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSToolbarItem.h>

@class NSView;

@interface _TtC6Reveal24MatchingWidthToolbarItem : NSToolbarItem
{
    // Error parsing type: , name: viewWidthConstraint
    // Error parsing type: , name: matchingItemTypes
    // Error parsing type: , name: fixedWidth
}

- (void).cxx_destruct;
- (id)initWithItemIdentifier:(id)arg1;
@property(nonatomic, retain) NSView *view;
@property(nonatomic, readonly) BOOL allowsDuplicatesInToolbar;

@end

