//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSearchField.h>

@class NSFont, NSString, NSView;

@interface _TtC6Reveal11FilterField : NSSearchField
{
    // Error parsing type: , name: leftAccessoryView
    // Error parsing type: , name: leftAccessoryViewObservationDisposeBag
}

- (void).cxx_destruct;
@property(nonatomic, retain) NSView *leftAccessoryView; // @synthesize leftAccessoryView;
@property(nonatomic, copy) NSString *placeholderString;
- (BOOL)becomeFirstResponder;
@property(nonatomic) BOOL enabled;
- (BOOL)isEnabled;
@property(nonatomic, retain) NSFont *font;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) BOOL allowsVibrancy;

@end

