//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class NSStackView;

@interface _TtC6Reveal35LayoutIssuesInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: stackView
    // Error parsing type: , name: edgeInsets
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: itemViewNib
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSStackView *stackView; // @synthesize stackView;

@end

