//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DMTrackingReporterDelegate-Protocol.h"

@interface _TtCC6Reveal21TrackingReportServiceP33_C9FCE52BC941D695AE2076396093F23E24TrackingReporterDelegate : NSObject <DMTrackingReporterDelegate>
{
    // Error parsing type: , name: service
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)trackingReporter:(id)arg1 didFinishSendingReportWithSuccess:(BOOL)arg2;

@end

