//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString, _TtC6Reveal34LicensePeriodProgressIndicatorView;

@interface _TtC6Reveal20LicenseBindingsModel : NSObject
{
    // Error parsing type: , name: gravatarLoader
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: dateFormatter.storage
    // Error parsing type: , name: licensePeriodProgressIndicatorView
    // Error parsing type: , name: licenseTypeImage
    // Error parsing type: , name: licenseeImage
    // Error parsing type: , name: licenseTypeText
    // Error parsing type: , name: licenseVariantText
    // Error parsing type: , name: licenseName
    // Error parsing type: , name: licenseEmail
    // Error parsing type: , name: licenseActivationIdText
    // Error parsing type: , name: licenseAnnualSupportActiveUntilText
    // Error parsing type: , name: licenseExpiredText
    // Error parsing type: , name: upgradeLicenseMenuItemVisible
    // Error parsing type: , name: licensePeriodExpired
    // Error parsing type: , name: isCommercialLicense
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL isCommercialLicense; // @synthesize isCommercialLicense;
@property(nonatomic) BOOL licensePeriodExpired; // @synthesize licensePeriodExpired;
@property(nonatomic) BOOL upgradeLicenseMenuItemVisible; // @synthesize upgradeLicenseMenuItemVisible;
@property(nonatomic, copy) NSString *licenseExpiredText; // @synthesize licenseExpiredText;
@property(nonatomic, copy) NSString *licenseAnnualSupportActiveUntilText; // @synthesize licenseAnnualSupportActiveUntilText;
@property(nonatomic, copy) NSString *licenseActivationIdText; // @synthesize licenseActivationIdText;
@property(nonatomic, copy) NSString *licenseEmail; // @synthesize licenseEmail;
@property(nonatomic, copy) NSString *licenseName; // @synthesize licenseName;
@property(nonatomic, copy) NSString *licenseVariantText; // @synthesize licenseVariantText;
@property(nonatomic, copy) NSString *licenseTypeText; // @synthesize licenseTypeText;
@property(nonatomic, retain) NSImage *licenseeImage; // @synthesize licenseeImage;
@property(nonatomic, retain) NSImage *licenseTypeImage; // @synthesize licenseTypeImage;
@property(nonatomic) __weak _TtC6Reveal34LicensePeriodProgressIndicatorView *licensePeriodProgressIndicatorView; // @synthesize licensePeriodProgressIndicatorView;

@end

