//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSString;

@interface _TtC6Reveal38TransformationMatrixInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: a
    // Error parsing type: , name: b
    // Error parsing type: , name: c
    // Error parsing type: , name: d
    // Error parsing type: , name: tx
    // Error parsing type: , name: ty
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: aMin
    // Error parsing type: , name: aMax
    // Error parsing type: , name: bMin
    // Error parsing type: , name: bMax
    // Error parsing type: , name: cMin
    // Error parsing type: , name: cMax
    // Error parsing type: , name: dMin
    // Error parsing type: , name: dMax
    // Error parsing type: , name: txMin
    // Error parsing type: , name: txMax
    // Error parsing type: , name: tyMin
    // Error parsing type: , name: tyMax
}

- (void).cxx_destruct;
@property(nonatomic) double tyMax; // @synthesize tyMax;
@property(nonatomic) double tyMin; // @synthesize tyMin;
@property(nonatomic) double txMax; // @synthesize txMax;
@property(nonatomic) double txMin; // @synthesize txMin;
@property(nonatomic) double dMax; // @synthesize dMax;
@property(nonatomic) double dMin; // @synthesize dMin;
@property(nonatomic) double cMax; // @synthesize cMax;
@property(nonatomic) double cMin; // @synthesize cMin;
@property(nonatomic) double bMax; // @synthesize bMax;
@property(nonatomic) double bMin; // @synthesize bMin;
@property(nonatomic) double aMax; // @synthesize aMax;
@property(nonatomic) double aMin; // @synthesize aMin;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic) double ty; // @synthesize ty;
@property(nonatomic) double tx; // @synthesize tx;
@property(nonatomic) double d; // @synthesize d;
@property(nonatomic) double c; // @synthesize c;
@property(nonatomic) double b; // @synthesize b;
@property(nonatomic) double a; // @synthesize a;

@end

