//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6Reveal29ViewHierarchyOutlineViewModel : _TtCs12_SwiftObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: presentationStateController
    // Error parsing type: , name: rootItems
    // Error parsing type: , name: navigator
    // Error parsing type: , name: rootIdentifiers
    // Error parsing type: , name: selectedItems
    // Error parsing type: , name: layoutIssuesTree
    // Error parsing type: , name: batchingProxy.storage
    // Error parsing type: , name: nodesToTreeItemsAdaptor
    // Error parsing type: , name: presentationStateControllerDisposeBag
}

- (void)reloadSelection;

@end

