//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal11OutlineView.h"

@interface _TtC6Reveal24ViewHierarchyOutlineView : _TtC6Reveal11OutlineView
{
    // Error parsing type: , name: viewHierarchyOutlineDelegate
    // Error parsing type: , name: hoverAspect
    // Error parsing type: , name: highlightedRow
}

- (void).cxx_destruct;
- (void)collapseItem:(id)arg1 collapseChildren:(BOOL)arg2;
- (void)expandItem:(id)arg1 expandChildren:(BOOL)arg2;
- (void)reloadData;
- (void)didAddRowView:(id)arg1 forRow:(long long)arg2;
- (id)makeViewWithIdentifier:(id)arg1 owner:(id)arg2;
- (void)viewDidMoveToSuperview;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

