//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAOperation.h"

@class NSError;

@interface _TtC6Reveal23NetworkRequestOperation : IBAOperation
{
    // Error parsing type: , name: request
    // Error parsing type: , name: session
    // Error parsing type: , name: response
    // Error parsing type: , name: error
    // Error parsing type: , name: task
}

- (void).cxx_destruct;
- (id)init;
- (void)cancel;
@property(nonatomic, readonly) NSError *dataServiceError;

@end

