//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSString;

@interface _TtC6Reveal24OffsetInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: horizontal
    // Error parsing type: , name: vertical
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
    // Error parsing type: , name: horizontalMin
    // Error parsing type: , name: horizontalMax
    // Error parsing type: , name: verticalMin
    // Error parsing type: , name: verticalMax
}

- (void).cxx_destruct;
@property(nonatomic) double verticalMax; // @synthesize verticalMax;
@property(nonatomic) double verticalMin; // @synthesize verticalMin;
@property(nonatomic) double horizontalMax; // @synthesize horizontalMax;
@property(nonatomic) double horizontalMin; // @synthesize horizontalMin;
@property(nonatomic, readonly) NSString *description;
- (void)dealloc;
@property(nonatomic) double vertical; // @synthesize vertical;
@property(nonatomic) double horizontal; // @synthesize horizontal;

@end

