//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "IBAMainMenuConnectActionHandler-Protocol.h"
#import "NSMenuItemValidation-Protocol.h"
#import "NSToolbarItemValidation-Protocol.h"
#import "NSTouchBarDelegate-Protocol.h"
#import "NSUserInterfaceValidations-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class NSToolbarItem, _TtC6Reveal25ConnectionInformationView, _TtC6Reveal25DocumentToolbarController, _TtC6Reveal29DocumentContentViewController;

@interface _TtC6Reveal24DocumentWindowController : NSWindowController <NSUserInterfaceValidations, NSMenuItemValidation, NSToolbarItemValidation, IBAMainMenuConnectActionHandler, NSTouchBarDelegate, NSWindowDelegate>
{
    // Error parsing type: , name: toolbarController
    // Error parsing type: , name: connectionInformationToolbarItem
    // Error parsing type: , name: documentCanRefresh
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: documentDisposeBag
    // Error parsing type: , name: connectionsWindowController
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (id)windowWillReturnUndoManager:(id)arg1;
- (void)handleConnectionWindowResized:(id)arg1;
- (void)toggleConnectionPopover:(id)arg1;
- (void)hideConnectionPopover:(id)arg1;
- (void)showConnectionPopover:(id)arg1;
- (BOOL)refreshApplicationSnapshotIfPossibleWithCompletion:(CDUnknownBlockType)arg1;
- (void)inspectApplication:(id)arg1;
- (id)windowTitleForDocumentDisplayName:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
@property(nonatomic, retain) id document;
@property(nonatomic, retain) NSToolbarItem *connectionInformationToolbarItem; // @synthesize connectionInformationToolbarItem;
@property(nonatomic, retain) _TtC6Reveal25DocumentToolbarController *toolbarController; // @synthesize toolbarController;
- (void)toggleSidebars:(id)arg1;
- (void)connectToServiceUsingFrontmostDocument:(id)arg1;
- (void)refreshViewHierarchy:(id)arg1;
- (BOOL)validateToolbarItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;
@property(nonatomic, readonly) _TtC6Reveal25ConnectionInformationView *connectionInfoToolbarView;
@property(nonatomic, readonly) _TtC6Reveal29DocumentContentViewController *documentContentViewController;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)makeTouchBar;

@end

