//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _TtC6Reveal21ProgressIndicatorView : NSView
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: progressView
    // Error parsing type: , name: maskLayer
    // Error parsing type: , name: currentProgress
    // Error parsing type: , name: progressWidthConstraint
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

