//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARevealDeviceInformation, NSDictionary, NSScriptObjectSpecifier, NSString;

@interface _TtC6Reveal22InspectableApplication : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: bundleIdentifier
    // Error parsing type: , name: buildVersion
    // Error parsing type: , name: releaseVersion
    // Error parsing type: , name: protocolVersion
    // Error parsing type: , name: isExtension
    // Error parsing type: , name: extensionTypeIdentifier
    // Error parsing type: , name: deviceInformation
    // Error parsing type: , name: connectionURL
    // Error parsing type: , name: connectionType
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSScriptObjectSpecifier *objectSpecifier;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSString *displayName;
@property(nonatomic, readonly) IBARevealDeviceInformation *deviceInformation; // @synthesize deviceInformation;
@property(nonatomic, readonly) NSString *bundleIdentifier; // @synthesize bundleIdentifier;
@property(nonatomic, readonly) NSString *name; // @synthesize name;
@property(nonatomic, readonly) NSDictionary *analyticsSegmentationInformation;

@end

