//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal29DualNumberFieldViewController.h"

@class NSStepper, _TtC6Reveal18InspectorTextField;

@interface _TtC6Reveal29QuadNumberFieldViewController : _TtC6Reveal29DualNumberFieldViewController
{
    // Error parsing type: , name: thirdTextField
    // Error parsing type: , name: fourthTextField
    // Error parsing type: , name: thirdStepper
    // Error parsing type: , name: fourthStepper
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSStepper *fourthStepper; // @synthesize fourthStepper;
@property(nonatomic, retain) NSStepper *thirdStepper; // @synthesize thirdStepper;
@property(nonatomic, retain) _TtC6Reveal18InspectorTextField *fourthTextField; // @synthesize fourthTextField;
@property(nonatomic, retain) _TtC6Reveal18InspectorTextField *thirdTextField; // @synthesize thirdTextField;

@end

