//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedObjectIdentifier.h"

@class NSString;

@interface _TtC6Reveal32RepresentedObjectGroupIdentifier : IBARepresentedObjectIdentifier
{
    // Error parsing type: , name: kind
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithString:(id)arg1;
- (id)initWithNumber:(id)arg1;
- (id)initWithValue:(long long)arg1;
@property(nonatomic, readonly) NSString *debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;

@end

