//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class NSTableView;

@interface _TtC6Reveal33CanvasThemeEditorWindowController : NSWindowController <NSTableViewDataSource, NSTableViewDelegate>
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: defaultModel
    // Error parsing type: , name: model
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)windowDidLoad;
@property(nonatomic, retain) NSTableView *tableView; // @synthesize tableView;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (void)imageCellValueChanged:(id)arg1;
- (void)colorCellValueChanged:(id)arg1;
- (void)boolCellValueChanged:(id)arg1;
- (void)numberCellValueChanged:(id)arg1;
- (void)stringCellValueChanged:(id)arg1;
- (void)applyDefaultTheme:(id)arg1;
- (void)applyTheme:(id)arg1;
- (void)resetTheme:(id)arg1;
- (void)saveTheme:(id)arg1;
- (void)loadTheme:(id)arg1;
- (void)copyThemeToClipboard:(id)arg1;

@end

