//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewController.h"

@class NSStackView;

@interface _TtC6Reveal35LayoutIssuesInspectorViewController : IBAInspectorViewController
{
    // Error parsing type: , name: stackView
    // Error parsing type: , name: edgeInsets
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: itemViewNib
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)didChangeViewModel;
- (void)viewDidLoad;
@property(nonatomic, retain) NSStackView *stackView; // @synthesize stackView;

@end

