//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSAlertDelegate-Protocol.h"

@interface _TtC6Reveal37DebuggerSupportInstallationController : NSObject <NSAlertDelegate>
{
    // Error parsing type: , name: service
    // Error parsing type: , name: defaultsManager
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)alertShowHelp:(id)arg1;

@end

