//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class IBALinkableInspectorTextField;

@interface _TtC6Reveal39ObjectIdentifierInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: textField
    // Error parsing type: , name: trackingArea
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)performTextFieldAction:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) IBALinkableInspectorTextField *textField; // @synthesize textField;

@end

