//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class IBAHyperlinkButton, NSButton;

@interface _TtC6Reveal19AboutViewController : NSViewController
{
    // Error parsing type: , name: acknowledgementsButton
    // Error parsing type: , name: versionButton
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)openIttyBittyAppsWebsite:(id)arg1;
- (void)openAcknowledgements:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSButton *versionButton; // @synthesize versionButton;
@property(nonatomic, retain) IBAHyperlinkButton *acknowledgementsButton; // @synthesize acknowledgementsButton;

@end

