//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSScrollView;

@interface _TtC6Reveal28InspectorStackViewController : NSViewController
{
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: delegate
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: rootSectionViewController
    // Error parsing type: , name: rootInspectorViewWidthConstraint
    // Error parsing type: , name: needsReloadData
    // Error parsing type: , name: shouldDisplayNoSelection
    // Error parsing type: , name: shouldDisplayNotApplicable
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)updateRootInspectorViewWidth;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)reloadData;
- (void)dealloc;
@property(nonatomic) BOOL shouldDisplayNotApplicable; // @synthesize shouldDisplayNotApplicable;
@property(nonatomic) BOOL shouldDisplayNoSelection; // @synthesize shouldDisplayNoSelection;
@property(nonatomic, retain) NSScrollView *scrollView; // @synthesize scrollView;

@end

