//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6Reveal36ViewHierarchyOutlineViewStateMemento : _TtCs12_SwiftObject
{
    // Error parsing type: , name: absoluteScrollOffset
    // Error parsing type: , name: focusedIdentifierForAbsoluteScrollOffset
    // Error parsing type: , name: _selectionRelativeScrollOffset
}

@end

