//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class IBAOutlineViewTreeItem, NSImageView, NSTextField;

@interface _TtC6Reveal32ViewHierarchyOutlineBaseCellView : NSTableCellView
{
    // Error parsing type: , name: isSelected
    // Error parsing type: , name: isHighlighted
    // Error parsing type: , name: isExpanded
    // Error parsing type: , name: treeItem
    // Error parsing type: , name: textFieldDisposables
    // Error parsing type: , name: imageViewDisposables
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) IBAOutlineViewTreeItem *treeItem; // @synthesize treeItem;
@property(nonatomic, copy) id objectValue;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)prepareForReuse;
@property(nonatomic, retain) NSImageView *imageView;
@property(nonatomic, retain) NSTextField *textField;
@property(nonatomic) BOOL expanded; // @synthesize expanded=isExpanded;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=isHighlighted;
@property(nonatomic) BOOL selected; // @synthesize selected=isSelected;

@end

