//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "IBACanvasSceneViewDelegate-Protocol.h"

@class IBACanvasBitmapErrorPresenter, IBACanvasBottomBarView, IBACanvasSceneView, IBACanvasToastBoard, IBACanvasToastsController, IBACanvasTopBarView, IBAGradientView, NSView;

@interface _TtC6Reveal33ViewHierarchyCanvasViewController : NSViewController <IBACanvasSceneViewDelegate>
{
    // Error parsing type: , name: presentationStateController
    // Error parsing type: , name: presentationStateControllerDisposeBag
    // Error parsing type: , name: _hiddenItemOpacity
    // Error parsing type: , name: containerView
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: canvasSceneView
    // Error parsing type: , name: canvasToastBoard
    // Error parsing type: , name: canvasToolbar
    // Error parsing type: , name: canvasBottomToolbar
    // Error parsing type: , name: toastsController
    // Error parsing type: , name: bitmapErrorPresenter
    // Error parsing type: , name: renderMode
    // Error parsing type: , name: perspective
    // Error parsing type: , name: canvasTreeAdapter
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) long long perspective; // @synthesize perspective;
@property(nonatomic) long long renderMode; // @synthesize renderMode;
@property(nonatomic, retain) IBACanvasBitmapErrorPresenter *bitmapErrorPresenter; // @synthesize bitmapErrorPresenter;
@property(nonatomic, retain) IBACanvasToastsController *toastsController; // @synthesize toastsController;
@property(nonatomic, retain) IBACanvasBottomBarView *canvasBottomToolbar; // @synthesize canvasBottomToolbar;
@property(nonatomic, retain) IBACanvasTopBarView *canvasToolbar; // @synthesize canvasToolbar;
@property(nonatomic, retain) IBACanvasToastBoard *canvasToastBoard; // @synthesize canvasToastBoard;
@property(nonatomic, retain) IBACanvasSceneView *canvasSceneView; // @synthesize canvasSceneView;
@property(nonatomic, retain) IBAGradientView *backgroundView; // @synthesize backgroundView;
@property(nonatomic, retain) NSView *containerView; // @synthesize containerView;
@property(nonatomic) double hiddenItemOpacity;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)zoomIn:(id)arg1;
- (void)zoomOut:(id)arg1;
- (void)zoomCanvasViewToFactor:(double)arg1 animated:(BOOL)arg2;
- (void)zoomToFitFocusedNodeProjectedAtFrontAnimated:(BOOL)arg1;
@property(nonatomic) double zoomFactor;
- (void)decreaseZDepthAnimated:(BOOL)arg1;
- (void)increaseZDepthAnimated:(BOOL)arg1;
- (void)applyCanvasBackgroundWithTheme:(id)arg1;
- (void)rotateCanvasViewToAngleInRadians:(double)arg1 animated:(BOOL)arg2;
- (void)selectRenderModeAction:(id)arg1;
- (void)selectPerspectiveAction:(id)arg1;
- (void)canvasSceneView:(id)arg1 didToggleStatistics:(BOOL)arg2;
- (void)canvasSceneView:(id)arg1 didChangeZoomFactor:(double)arg2 animated:(BOOL)arg3;
- (void)canvasSceneView:(id)arg1 toggleTreeItemExpansion:(id)arg2 includeChildren:(BOOL)arg3;
- (void)canvasSceneView:(id)arg1 didSelectTreeItem:(id)arg2;
- (void)canvasSceneView:(id)arg1 didMouseOverTreeItem:(id)arg2;
- (void)canvasSceneView:(id)arg1 didFocusTreeItem:(id)arg2;
- (struct CGRect)canvasSceneView:(id)arg1 mouseTrackingRectForVisibleRect:(struct CGRect)arg2;
- (double)currentZoomFactorForCanvasToastsController:(id)arg1;
- (BOOL)canvasToastsController:(id)arg1 isContentOptionEnabled:(long long)arg2;
- (id)canvasBitmapErrorPresenter:(id)arg1 bitmapErrorFor:(id)arg2;
- (void)panCanvasToPosition:(struct SCNVector3)arg1 animated:(BOOL)arg2;

@end

