//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class NSNumber;

@interface _TtC6Reveal28ScreenModeInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: pixelAspectRatio
    // Error parsing type: , name: width
    // Error parsing type: , name: height
}

- (void).cxx_destruct;
@property(nonatomic, retain) NSNumber *height; // @synthesize height;
@property(nonatomic, retain) NSNumber *width; // @synthesize width;
@property(nonatomic, retain) NSNumber *pixelAspectRatio; // @synthesize pixelAspectRatio;

@end

