//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@class IBARepresentedObjectIdentifier, IBARevealDataModel, NSImage, NSNumber, NSString, _TtC6Reveal17RepresentedObject, _TtC6Reveal39LayoutConstraintInspectorIssueViewModel;

@interface _TtC6Reveal34LayoutConstraintInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: referenceObject
    // Error parsing type: , name: constraintDescription
    // Error parsing type: , name: constraintIcon
    // Error parsing type: , name: firstItemAttributeDescription
    // Error parsing type: , name: relationshipDescription
    // Error parsing type: , name: secondItemAttributeDescription
    // Error parsing type: , name: shouldBeArchived
    // Error parsing type: , name: constant
    // Error parsing type: , name: priority
    // Error parsing type: , name: multiplier
    // Error parsing type: , name: hasSecondItem
    // Error parsing type: , name: firstItemIdentifier
    // Error parsing type: , name: secondItemIdentifier
    // Error parsing type: , name: firstItemSelectable
    // Error parsing type: , name: secondItemSelectable
    // Error parsing type: , name: issueViewModel
    // Error parsing type: , name: attributeObserver
    // Error parsing type: , name: representedObjectModel
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void).cxx_destruct;
- (BOOL)validateValue:(id *)arg1 forKey:(id)arg2 error:(id *)arg3;
- (void)dealloc;
@property(nonatomic, retain) _TtC6Reveal39LayoutConstraintInspectorIssueViewModel *issueViewModel; // @synthesize issueViewModel;
@property(nonatomic) BOOL secondItemSelectable; // @synthesize secondItemSelectable;
@property(nonatomic) BOOL firstItemSelectable; // @synthesize firstItemSelectable;
@property(nonatomic, retain) IBARepresentedObjectIdentifier *secondItemIdentifier; // @synthesize secondItemIdentifier;
@property(nonatomic, retain) IBARepresentedObjectIdentifier *firstItemIdentifier; // @synthesize firstItemIdentifier;
@property(nonatomic) BOOL hasSecondItem; // @synthesize hasSecondItem;
@property(nonatomic, readonly) BOOL priorityIsEditable;
@property(nonatomic, readonly) NSNumber *maximumPriority;
@property(nonatomic, readonly) NSNumber *minimumPriority;
@property(nonatomic) double multiplier; // @synthesize multiplier;
@property(nonatomic) float priority; // @synthesize priority;
@property(nonatomic) double constant; // @synthesize constant;
@property(nonatomic) BOOL shouldBeArchived; // @synthesize shouldBeArchived;
@property(nonatomic, copy) NSString *secondItemAttributeDescription; // @synthesize secondItemAttributeDescription;
@property(nonatomic, copy) NSString *relationshipDescription; // @synthesize relationshipDescription;
@property(nonatomic, copy) NSString *firstItemAttributeDescription; // @synthesize firstItemAttributeDescription;
@property(nonatomic, retain) NSImage *constraintIcon; // @synthesize constraintIcon;
@property(nonatomic, copy) NSString *constraintDescription; // @synthesize constraintDescription;
@property(nonatomic, retain) IBARevealDataModel *dataModel;
@property(nonatomic, retain) _TtC6Reveal17RepresentedObject *referenceObject; // @synthesize referenceObject;

@end

