//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSTextFieldDelegate-Protocol.h"

@class _TtC6Reveal11FilterField, _TtC6Reveal22FilterFieldPopUpButton;

@interface _TtC6Reveal25FilterFieldViewController : NSViewController <NSTextFieldDelegate>
{
    // Error parsing type: , name: queryField
    // Error parsing type: , name: optionsSelector
    // Error parsing type: , name: viewModelDisposeBag
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic, copy) id representedObject;
@property(nonatomic, retain) _TtC6Reveal22FilterFieldPopUpButton *optionsSelector; // @synthesize optionsSelector;
@property(nonatomic, retain) _TtC6Reveal11FilterField *queryField; // @synthesize queryField;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)makeTouchBar;
- (void)changeFilterOptions:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;

@end

