//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18HighlightContainer.h"

@class NSColor;

@interface _TtC6Reveal27HoverableHighlightContainer : _TtC6Reveal18HighlightContainer
{
    // Error parsing type: , name: hoverBackgroundColor
    // Error parsing type: , name: hoverBackgroundInsets
    // Error parsing type: , name: hoverBackgroundCornerRadius
    // Error parsing type: , name: hoverAspect
}

- (CDUnknownBlockType).cxx_destruct;
- (void)hoverableView:(id)arg1 mouseDidExitWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidEnterWithEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double hoverBackgroundCornerRadius; // @synthesize hoverBackgroundCornerRadius;
@property(nonatomic, retain) NSColor *hoverBackgroundColor; // @synthesize hoverBackgroundColor;

@end

