//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal23InspectorViewController.h"

@class NSButton, NSImageView, NSTextField;

@interface _TtC6Reveal50LayoutConstraintDescriptionInspectorViewController : _TtC6Reveal23InspectorViewController
{
    // Error parsing type: , name: detailButton
    // Error parsing type: , name: overlayButton
    // Error parsing type: , name: constraintDescriptionTextField
    // Error parsing type: , name: constraintIcon
    // Error parsing type: , name: layoutIssueButton
    // Error parsing type: , name: hoverAspect
    // Error parsing type: , name: isLayoutReportPopoverShown
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)displayLayoutReport:(id)arg1;
- (void)selectConstraint:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSButton *layoutIssueButton; // @synthesize layoutIssueButton;
@property(nonatomic, retain) NSImageView *constraintIcon; // @synthesize constraintIcon;
@property(nonatomic, retain) NSTextField *constraintDescriptionTextField; // @synthesize constraintDescriptionTextField;
@property(nonatomic, retain) NSButton *overlayButton; // @synthesize overlayButton;
@property(nonatomic, retain) NSButton *detailButton; // @synthesize detailButton;

@end

