//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtCC6Reveal15BonjourResolverP33_276F07B7FA0FFC4093437ACC566F50C79Attempter : SwiftObject
{
    // Error parsing type: , name: maximumAttempts
    // Error parsing type: , name: handler
    // Error parsing type: , name: attemptsCounter
}

@end

