//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal17RepresentedObject.h"

@class IBARepresentedLayer, NSArray, NSString, _TtC6Reveal17RepresentedWindow;

@interface _TtC6Reveal15RepresentedView : _TtC6Reveal17RepresentedObject
{
}

- (BOOL)isDescendentOfRepresentedView:(id)arg1;
@property(nonatomic, readonly) NSArray *gestureRecognizers;
@property(nonatomic, readonly) NSArray *layoutGuides;
@property(nonatomic, readonly) NSArray *constraints;
@property(nonatomic, readonly) NSArray *subviews;
@property(nonatomic, readonly) struct CGPoint center;
@property(nonatomic, readonly) struct CGRect bounds;
@property(nonatomic, readonly) struct CGRect frame;
@property(nonatomic, readonly) BOOL isHidden;
@property(nonatomic, readonly) double alpha;
@property(nonatomic, readonly) _TtC6Reveal17RepresentedWindow *window;
@property(nonatomic, readonly) _TtC6Reveal15RepresentedView *superview;
@property(nonatomic, readonly) IBARepresentedLayer *layer;
@property(nonatomic, readonly) NSString *debugDescription;

@end

