//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class IBAInspectorTabControl, NSView;

@interface _TtC6Reveal25InspectorTabBarController : NSViewController
{
    // Error parsing type: , name: tabBarView
    // Error parsing type: , name: inspectorTabContainerView
    // Error parsing type: , name: badgeController
    // Error parsing type: , name: dataSources
    // Error parsing type: , name: userDefaultsManager
    // Error parsing type: , name: sectionDividerNib
    // Error parsing type: , name: sectionHeaderNib
    // Error parsing type: , name: subsectionHeaderNib
    // Error parsing type: , name: viewControllers
    // Error parsing type: , name: selectedViewController
    // Error parsing type: , name: containerConstraints
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)transitionFromViewController:(id)arg1 toViewController:(id)arg2 options:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)handleSelectedSegmentChange:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSView *inspectorTabContainerView; // @synthesize inspectorTabContainerView;
@property(nonatomic, retain) IBAInspectorTabControl *tabBarView; // @synthesize tabBarView;

@end

