//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBAViewHoverDelegate-Protocol.h"

@interface _TtCC6Reveal21InspectorScopeControlP33_F579C36A5ABB2E9F12D45D2400BDF18913HoverRedrawer : NSObject <IBAViewHoverDelegate>
{
}

- (id)init;
- (void)hoverableView:(id)arg1 mouseDidExitWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidMoveWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidEnterWithEvent:(id)arg2;

@end

