//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtCE6RevealCSo20NSDocumentControllerP33_42715F0D1D2A8E11A7B800C5E2E614FF25CloseAllDocumentsDelegate : NSObject
{
    // Error parsing type: , name: closeAllDocumentsHandler
    // Error parsing type: , name: retainer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)documentController:(id)arg1 didCloseAll:(BOOL)arg2 contextInfo:(void *)arg3;

@end

