//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal27HoverableHighlightContainer.h"

@class NSImage, NSImageView, NSString, NSTextField;

@interface _TtC6Reveal16WelcomePromoTile : _TtC6Reveal27HoverableHighlightContainer
{
    // Error parsing type: , name: image
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: imageView
    // Error parsing type: , name: titleField
    // Error parsing type: , name: subtitleField
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *subtitleField; // @synthesize subtitleField;
@property(nonatomic, retain) NSTextField *titleField; // @synthesize titleField;
@property(nonatomic, retain) NSImageView *imageView; // @synthesize imageView;
- (void)prepareForInterfaceBuilder;
- (void)awakeFromNib;
- (void)resetCursorRects;
@property(nonatomic) BOOL enabled;
- (BOOL)isEnabled;
@property(nonatomic, copy) NSString *subtitle; // @synthesize subtitle;
@property(nonatomic, copy) NSString *title; // @synthesize title;
@property(nonatomic, retain) NSImage *image; // @synthesize image;

@end

