//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal18InspectorViewModel.h"

@interface _TtC6Reveal22UUIDInspectorViewModel : _TtC6Reveal18InspectorViewModel
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: changeObserver
    // Error parsing type: , name: objectModel
}

- (void).cxx_destruct;
- (void)dealloc;

@end

