//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSearchFieldCell.h>

@interface _TtC6Reveal15FilterFieldCell : NSSearchFieldCell
{
    // Error parsing type: , name: leftAccessoryViewRect
}

- (id)setUpFieldEditorAttributes:(id)arg1;
- (struct CGRect)searchTextRectForBounds:(struct CGRect)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property(nonatomic, readonly) long long interiorBackgroundStyle;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

