//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6Reveal17ActivationService : _TtCs12_SwiftObject
{
    // Error parsing type: , name: activationControllerDelegate
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: analytics
    // Error parsing type: , name: activationController
    // Error parsing type: , name: isDeactivatingLicense
    // Error parsing type: , name: userDefaults
}

@end

