//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedObjectIdentifier, NSArray, NSImage, NSString;

@interface _TtC6Reveal19OutlineViewTreeItem : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: title
    // Error parsing type: , name: image
    // Error parsing type: , name: isEnabled
    // Error parsing type: , name: isEmphasized
    // Error parsing type: , name: queryString
    // Error parsing type: , name: queryExclusionRange
    // Error parsing type: , name: filterResults
    // Error parsing type: , name: layoutIssue
    // Error parsing type: , name: children
    // Error parsing type: , name: parent
    // Error parsing type: , name: identifier
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *debugDescription;
@property(nonatomic, readonly) IBARepresentedObjectIdentifier *identifier; // @synthesize identifier;
@property(nonatomic) __weak _TtC6Reveal19OutlineViewTreeItem *parent; // @synthesize parent;
@property(nonatomic) struct _NSRange queryExclusionRange; // @synthesize queryExclusionRange;
@property(nonatomic, copy) NSString *queryString; // @synthesize queryString;
@property(nonatomic) BOOL isEmphasized; // @synthesize isEmphasized;
@property(nonatomic) BOOL isEnabled; // @synthesize isEnabled;
@property(nonatomic, retain) NSImage *image; // @synthesize image;
@property(nonatomic, copy) NSString *title; // @synthesize title;
@property(nonatomic, readonly) NSArray *parentItems;

@end

