//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DMActivationController, NSArray, NSDictionary, NSURL, WebFrame, WebScriptObject;
@protocol DMFsprgStoreParameters;

@protocol DMFsprgEmbeddedStoreDelegate <NSObject>

@optional
- (void)activationController:(DMActivationController *)arg1 waitsForCustomFsprgEmbeddedStore:(void (^)(id <DMFsprgOrder>))arg2;
- (NSArray *)activationController:(DMActivationController *)arg1 contextMenuItemsForNativeFsprgEmbeddedStoreElement:(NSDictionary *)arg2 defaultMenuItems:(NSArray *)arg3;
- (void)activationController:(DMActivationController *)arg1 didClearNativeFsprgEmbededStoreWindowObject:(WebScriptObject *)arg2 forFrame:(WebFrame *)arg3;
- (void)activationController:(DMActivationController *)arg1 didLoadNativeFsprgEmbeddedStorePage:(NSURL *)arg2;
- (BOOL)activationController:(DMActivationController *)arg1 canResizeNativeFsprgEmbeddedStoreWindowWithInitialSize:(struct CGSize *)arg2;
- (void)activationController:(DMActivationController *)arg1 willStartNativeFsprgEmbeddedStore:(id <DMFsprgStoreParameters>)arg2;
- (unsigned long long)fsprgEmbeddedStoreTypeForActivationController:(DMActivationController *)arg1;
@end

