//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAAMService.h"

@class NSMutableDictionary;

@interface IBAAMNotificationProxy : IBAAMService
{
    NSMutableDictionary *_observersRegistry;
}

+ (id)registeredInstanceForOpaquePointer:(void *)arg1;
+ (void)registerInstance:(id)arg1;
+ (void)initialize;
+ (id)serviceName;
- (void).cxx_destruct;
- (void)didReceiveNotificationWithName:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)removeObserver:(id)arg1 name:(id)arg2;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3;
- (void)postNotification:(id)arg1;
- (void)dealloc;
- (id)initWithServiceStruct:(int)arg1;

@end

