//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IBAAMDevice : NSObject
{
    struct _am_device *_device;
    BOOL _connected;
    BOOL _sessionStarted;
    NSString *_deviceName;
    NSString *_UDID;
}

+ (BOOL)successWithCode:(int)arg1 fromFunction:(const char *)arg2 error:(id *)arg3;
@property(readonly, copy, nonatomic) NSString *UDID; // @synthesize UDID=_UDID;
@property(readonly, copy, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
- (void).cxx_destruct;
- (id)newNotificationProxyWithError:(id *)arg1;
- (id)newServiceHandler:(Class)arg1 error:(id *)arg2;
- (int)startService:(id)arg1 error:(id *)arg2;
- (id)description;
@property(readonly, copy, nonatomic) NSString *serialNumber;
@property(readonly, copy, nonatomic) NSString *deviceClass;
@property(readonly, copy, nonatomic) NSString *productType;
- (id)allDeviceValuesForDomain:(id)arg1;
- (id)deviceValueForKey:(id)arg1;
- (id)deviceValueForKey:(id)arg1 inDomain:(id)arg2;
- (int)connectToPort:(unsigned long long)arg1 error:(id *)arg2;
- (BOOL)performInSession:(CDUnknownBlockType)arg1 error:(id *)arg2;
- (BOOL)stopSessionWithError:(id *)arg1;
- (BOOL)startSessionWithError:(id *)arg1;
- (BOOL)deviceDisconnectWithError:(id *)arg1;
- (BOOL)deviceConnectWithError:(id *)arg1;
- (void)cleanupDeviceConnections;
- (void)invalidate;
- (BOOL)matchesDeviceStruct:(struct _am_device *)arg1;
- (void)dealloc;
- (id)initWithDeviceStruct:(struct _am_device *)arg1 error:(id *)arg2;
- (id)init;

@end

