//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSArray;

@interface IBAArrayInspectorViewModel : IBAInspectorViewModel
{
    NSArray *_childViewModels;
    CDUnknownBlockType _childObjectsAccessor;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (id)childViewModelsFromChildObjects:(id)arg1 dataModel:(id)arg2;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(readonly, copy, nonatomic) CDUnknownBlockType childObjectsAccessor; // @synthesize childObjectsAccessor=_childObjectsAccessor;
@property(copy, nonatomic) NSArray *childViewModels; // @synthesize childViewModels=_childViewModels;
- (void).cxx_destruct;
- (void)reloadChildViewModels;
- (void)setDataModel:(id)arg1;
- (BOOL)isEmpty;
- (void)dealloc;
- (id)initWithRepresentedObject:(id)arg1;
- (id)initWithRepresentedObject:(id)arg1 childObjectsAccessor:(CDUnknownBlockType)arg2;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

