//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CLYEventStack, NSOperationQueue, NSString, NSTimer, NSURLSession;

@interface IBAAnalytics : NSObject
{
    BOOL _applicationInBackgroundState;
    BOOL _shouldTrackSessionDuration;
    BOOL _shouldSendEventsViaWWAN;
    NSTimer *_sessionTimer;
    NSTimer *_eventStackPopTimer;
    double _sessionsLastTime;
    CLYEventStack *_eventStack;
    NSString *_appKey;
    NSString *_appHost;
    NSString *_UUID;
    unsigned long long _sessionState;
    NSOperationQueue *_httpOperationQueue;
    struct __SCNetworkReachability *_networkReachability;
    long long _networkReachabilityStatus;
    double _sessionDurationUpdateInterval;
    unsigned long long _recordingStatus;
    NSURLSession *_urlSession;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
@property(nonatomic) unsigned long long recordingStatus; // @synthesize recordingStatus=_recordingStatus;
@property(nonatomic) double sessionDurationUpdateInterval; // @synthesize sessionDurationUpdateInterval=_sessionDurationUpdateInterval;
@property(nonatomic) BOOL shouldSendEventsViaWWAN; // @synthesize shouldSendEventsViaWWAN=_shouldSendEventsViaWWAN;
@property(nonatomic) BOOL shouldTrackSessionDuration; // @synthesize shouldTrackSessionDuration=_shouldTrackSessionDuration;
@property(nonatomic) long long networkReachabilityStatus; // @synthesize networkReachabilityStatus=_networkReachabilityStatus;
@property(readonly, nonatomic) struct __SCNetworkReachability *networkReachability; // @synthesize networkReachability=_networkReachability;
@property(retain, nonatomic) NSOperationQueue *httpOperationQueue; // @synthesize httpOperationQueue=_httpOperationQueue;
@property(nonatomic) BOOL applicationInBackgroundState; // @synthesize applicationInBackgroundState=_applicationInBackgroundState;
@property(nonatomic) unsigned long long sessionState; // @synthesize sessionState=_sessionState;
@property(copy, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(copy, nonatomic) NSString *appHost; // @synthesize appHost=_appHost;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) CLYEventStack *eventStack; // @synthesize eventStack=_eventStack;
@property(nonatomic) double sessionsLastTime; // @synthesize sessionsLastTime=_sessionsLastTime;
@property(retain, nonatomic) NSTimer *eventStackPopTimer; // @synthesize eventStackPopTimer=_eventStackPopTimer;
@property(retain, nonatomic) NSTimer *sessionTimer; // @synthesize sessionTimer=_sessionTimer;
- (void).cxx_destruct;
- (id)deviceResolution;
- (id)osVersion;
- (id)applicationVersion;
- (void)stopMonitoringNetworkReachability;
- (void)startMonitoringNetworkReachability;
@property(readonly, nonatomic) BOOL isHostReachable;
- (id)urlRequestForSessionUpdateWithDuration:(double)arg1;
- (id)urlRequestForSessionBegin;
- (void)sendPendingEvents;
- (void)eventStackPopTimerFired:(id)arg1;
- (void)recordEvent:(id)arg1 segmentation:(id)arg2 count:(unsigned long long)arg3 sum:(double)arg4;
- (void)sessionTimerFired:(id)arg1;
- (void)updateSessionState;
- (void)recordEvent:(id)arg1 segmentation:(id)arg2 count:(unsigned long long)arg3;
- (void)recordEvent:(id)arg1 count:(unsigned long long)arg2 sum:(double)arg3;
- (void)recordEvent:(id)arg1 count:(unsigned long long)arg2;
- (void)startRecordingAnalyticsWithAttributes:(id)arg1;
- (void)stopRecordingAnalytics;
- (void)dealloc;
- (id)init;

@end

