//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DMActivationControllerDelegate-Protocol.h"

@class NSString;

@interface IBAActivationControllerDelegate : NSObject <DMActivationControllerDelegate>
{
    // Error parsing type: , name: service
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)iba_activationController:(id)arg1 shouldShowDialogForReason:(unsigned long long)arg2;
- (long long)activationController:(id)arg1 activationStepForProposedStep:(long long)arg2;
- (id)additionalStoreURLParameters:(id)arg1;
- (BOOL)activationController:(id)arg1 shouldShowDialogForReason:(unsigned long long)arg2 withAdditionalInfo:(id)arg3 proposedActivationMode:(inout unsigned long long *)arg4 completionHandlerSetter:(CDUnknownBlockType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

