//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSArray, NSNumber;

@interface IBABitFieldInspectorViewModel : IBAInspectorViewModel
{
    NSArray *_maskOptions;
    NSNumber *_bitFieldValue;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (id)enumValuesForRepresentedOptionSet:(id)arg1;
+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) NSNumber *bitFieldValue; // @synthesize bitFieldValue=_bitFieldValue;
@property(readonly, copy, nonatomic) NSArray *maskOptions; // @synthesize maskOptions=_maskOptions;
- (void).cxx_destruct;
- (void)updateBitFieldWithMaskSelection:(id)arg1;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

