//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface IBAConnectionBarRefreshButton : NSButton
{
    // Error parsing type: , name: hoverAspect
}

- (void).cxx_destruct;
- (void)hoverableView:(id)arg1 mouseDidExitWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidEnterWithEvent:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

