//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol IBACanvasTreeItemRectangular <NSObject>
@property(readonly, nonatomic) struct CGPoint center;
@property(readonly, nonatomic) struct CGRect frame;
@property(readonly, nonatomic) struct CGRect bounds;
@end

