//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSArray, NSString;

@interface IBACalendarInspectorViewModel : IBAInspectorViewModel
{
    NSArray *_calendarChoices;
    NSString *_selectedCalendarIdentifier;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(copy, nonatomic) NSString *selectedCalendarIdentifier; // @synthesize selectedCalendarIdentifier=_selectedCalendarIdentifier;
@property(copy, nonatomic) NSArray *calendarChoices; // @synthesize calendarChoices=_calendarChoices;
- (void).cxx_destruct;
- (id)description;
- (void)setDataModel:(id)arg1;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

