//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class IBAConnectionBarRefreshButton, IBAInspectableApplicationIconView, NSButton, NSTextField;

@interface IBAConnectionInformationView : NSView
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: backgroundButton
    // Error parsing type: , name: refreshButton
    // Error parsing type: , name: progressIndicatorView
    // Error parsing type: , name: iconView
    // Error parsing type: , name: nameField
    // Error parsing type: , name: stateField
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *stateField; // @synthesize stateField;
@property(nonatomic, retain) NSTextField *nameField; // @synthesize nameField;
@property(nonatomic, retain) IBAInspectableApplicationIconView *iconView; // @synthesize iconView;
@property(nonatomic, retain) IBAConnectionBarRefreshButton *refreshButton; // @synthesize refreshButton;
@property(nonatomic, retain) NSButton *backgroundButton; // @synthesize backgroundButton;
- (void)awakeFromNib;

@end

