//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBACanvasToastView, IBASelectionController;
@protocol IBACanvasBitmapErrorPresenterDelegate;

@interface IBACanvasBitmapErrorPresenter : NSObject
{
    // Error parsing type: , name: bitmapErrorToastView
    // Error parsing type: , name: delegate
    // Error parsing type: , name: selectionController
    // Error parsing type: , name: selectionObserverBag
    // Error parsing type: , name: shouldDisplayBitmapErrors
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL shouldDisplayBitmapErrors; // @synthesize shouldDisplayBitmapErrors;
@property(nonatomic, retain) IBASelectionController *selectionController; // @synthesize selectionController;
@property(nonatomic) __weak id <IBACanvasBitmapErrorPresenterDelegate> delegate; // @synthesize delegate;
@property(nonatomic, retain) IBACanvasToastView *bitmapErrorToastView; // @synthesize bitmapErrorToastView;

@end

