//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewController.h"

@class IBAColorInspectorViewModel, NSMenuItem, NSPopUpButton, NSSegmentedControl, NSTextField;

@interface IBAColorInspectorViewController : IBAInspectorViewController
{
    BOOL _observingKeyPaths;
    BOOL _deallocating;
    BOOL _customColorVisible;
    NSMenuItem *_previouslySelectedItem;
    NSTextField *_colorCodeTextField;
    NSSegmentedControl *_colorCodeFormatPicker;
    NSPopUpButton *_colorsPopupButton;
    NSMenuItem *_defaultColorMenuItem;
    NSMenuItem *_currentColorMenuItem;
    NSMenuItem *_chooseCustomColorMenuItem;
}

@property(retain) NSMenuItem *chooseCustomColorMenuItem; // @synthesize chooseCustomColorMenuItem=_chooseCustomColorMenuItem;
@property(retain) NSMenuItem *currentColorMenuItem; // @synthesize currentColorMenuItem=_currentColorMenuItem;
@property(retain) NSMenuItem *defaultColorMenuItem; // @synthesize defaultColorMenuItem=_defaultColorMenuItem;
@property(retain) NSPopUpButton *colorsPopupButton; // @synthesize colorsPopupButton=_colorsPopupButton;
@property(retain) NSSegmentedControl *colorCodeFormatPicker; // @synthesize colorCodeFormatPicker=_colorCodeFormatPicker;
@property(retain) NSTextField *colorCodeTextField; // @synthesize colorCodeTextField=_colorCodeTextField;
@property __weak NSMenuItem *previouslySelectedItem; // @synthesize previouslySelectedItem=_previouslySelectedItem;
@property(getter=isCustomColorVisible) BOOL customColorVisible; // @synthesize customColorVisible=_customColorVisible;
- (void).cxx_destruct;
- (void)updateColorFormatSegments:(id)arg1 usingColorFormats:(id)arg2;
- (id)menuItemForColor:(id)arg1 inMenu:(id)arg2;
- (void)selectMenuItemForColor:(id)arg1;
- (void)selectColorMenuItem:(id)arg1;
- (void)updateColorPreviewSwatchInMenuItem:(id)arg1;
- (void)updateColorPreviewSwatchesInMenu:(id)arg1;
- (void)colorPanelDidChangeColor:(id)arg1;
- (void)showColorPanel;
- (id)colorPanel;
- (void)controlDidBecomeFirstResponder:(id)arg1;
- (void)selectCustomColor:(id)arg1;
- (void)selectPredefinedColor:(id)arg1;
- (void)selectColorFormat:(id)arg1;
- (void)stopObservingKeyPaths;
- (void)startObservingKeyPaths;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(retain, nonatomic) IBAColorInspectorViewModel *viewModel; // @dynamic viewModel;

@end

