//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARevealColoredBorderedView.h"

@class NSButton, NSSlider;

@interface IBACanvasBottomBarView : IBARevealColoredBorderedView
{
    // Error parsing type: , name: autoLayoutToggleButton
    // Error parsing type: , name: excludedItemsToggleButton
    // Error parsing type: , name: hiddenItemsToggleButton
    // Error parsing type: , name: resetCameraButton
    // Error parsing type: , name: zoomOutButton
    // Error parsing type: , name: zoomSlider
    // Error parsing type: , name: zoomInButton
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)prepareForInterfaceBuilder;
- (void)awakeFromNib;
@property(nonatomic, retain) NSButton *zoomInButton; // @synthesize zoomInButton;
@property(nonatomic, retain) NSSlider *zoomSlider; // @synthesize zoomSlider;
@property(nonatomic, retain) NSButton *zoomOutButton; // @synthesize zoomOutButton;
@property(nonatomic, retain) NSButton *resetCameraButton; // @synthesize resetCameraButton;
@property(nonatomic, retain) NSButton *hiddenItemsToggleButton; // @synthesize hiddenItemsToggleButton;
@property(nonatomic, retain) NSButton *excludedItemsToggleButton; // @synthesize excludedItemsToggleButton;
@property(nonatomic, retain) NSButton *autoLayoutToggleButton; // @synthesize autoLayoutToggleButton;

@end

