//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CAShapeLayer.h>

@interface IBACanvasToastLayer : CAShapeLayer
{
    // Error parsing type: , name: toast
    // Error parsing type: , name: textLayer
    // Error parsing type: , name: imageLayer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) double contentsScale;
- (void)layoutSublayers;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;

@end

