//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBACanvasButton, IBACanvasSegmentedControl, IBACanvasSlider, IBACanvasToastBoard;
@protocol IBACanvasToastsControllerDelegate;

@interface IBACanvasToastsController : NSObject
{
    // Error parsing type: , name: toastBoard
    // Error parsing type: , name: renderModeControl
    // Error parsing type: , name: perspectiveModeControl
    // Error parsing type: , name: resetCameraButton
    // Error parsing type: , name: autoLayoutToggleButton
    // Error parsing type: , name: excludedItemsToggleButton
    // Error parsing type: , name: hiddenItemsToggleButton
    // Error parsing type: , name: zoomOutButton
    // Error parsing type: , name: zoomSlider
    // Error parsing type: , name: zoomInButton
    // Error parsing type: , name: delegate
    // Error parsing type: , name: zoomPercentageFormatter
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)hoverableSegmentedControl:(id)arg1 mouseDidExitAtSegment:(long long)arg2 withEvent:(id)arg3;
- (void)hoverableSegmentedControl:(id)arg1 mouseDidMoveToSegment:(long long)arg2 withEvent:(id)arg3;
- (void)hoverableSegmentedControl:(id)arg1 mouseDidEnterAtSegment:(long long)arg2 withEvent:(id)arg3;
- (void)hoverableView:(id)arg1 mouseDidExitWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidEnterWithEvent:(id)arg2;
- (void)presentTransientZoomSliderToastWithZoomFactor:(double)arg1;
- (void)presentTransientToastForContentOption:(long long)arg1 enabled:(BOOL)arg2;
- (void)presentTransientToastForPerspective:(long long)arg1;
- (void)presentTransientToastForRenderMode:(long long)arg1;
@property(nonatomic) __weak id <IBACanvasToastsControllerDelegate> delegate; // @synthesize delegate;
@property(nonatomic, retain) IBACanvasButton *zoomInButton; // @synthesize zoomInButton;
@property(nonatomic, retain) IBACanvasSlider *zoomSlider; // @synthesize zoomSlider;
@property(nonatomic, retain) IBACanvasButton *zoomOutButton; // @synthesize zoomOutButton;
@property(nonatomic, retain) IBACanvasButton *hiddenItemsToggleButton; // @synthesize hiddenItemsToggleButton;
@property(nonatomic, retain) IBACanvasButton *excludedItemsToggleButton; // @synthesize excludedItemsToggleButton;
@property(nonatomic, retain) IBACanvasButton *autoLayoutToggleButton; // @synthesize autoLayoutToggleButton;
@property(nonatomic, retain) IBACanvasButton *resetCameraButton; // @synthesize resetCameraButton;
@property(nonatomic, retain) IBACanvasSegmentedControl *perspectiveModeControl; // @synthesize perspectiveModeControl;
@property(nonatomic, retain) IBACanvasSegmentedControl *renderModeControl; // @synthesize renderModeControl;
@property(nonatomic, retain) IBACanvasToastBoard *toastBoard; // @synthesize toastBoard;

@end

