//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import "CALayerDelegate-Protocol.h"

@class CALayer;

@interface IBACanvasToastBoard : NSView <CALayerDelegate>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: toastTimers
    // Error parsing type: , name: toastLayers
}

- (CDUnknownBlockType).cxx_destruct;
- (void)setFrameSize:(struct CGSize)arg1;
- (id)hitTest:(struct CGPoint)arg1;
- (void)viewDidChangeBackingProperties;
@property(nonatomic, retain) CALayer *layer;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

