//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSNumber, NSString;

@interface IBAColorFormat : NSObject <NSCoding>
{
    NSNumber *_tag;
    NSString *_name;
    NSString *_colorTransformerName;
}

+ (id)rgbaColorFormat;
+ (id)hexColorFormat;
@property(retain) NSString *colorTransformerName; // @synthesize colorTransformerName=_colorTransformerName;
@property(retain) NSString *name; // @synthesize name=_name;
@property(retain) NSNumber *tag; // @synthesize tag=_tag;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqualToFormat:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 tag:(id)arg2 colorTransformerName:(id)arg3;

@end

