//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class IBACanvasToastView, NSSegmentedControl;

@interface IBACanvasTopBarView : NSView
{
    // Error parsing type: , name: perspectiveModeControl
    // Error parsing type: , name: bitmapErrorToastView
    // Error parsing type: , name: renderModeControl
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSSegmentedControl *renderModeControl; // @synthesize renderModeControl;
@property(nonatomic, retain) IBACanvasToastView *bitmapErrorToastView; // @synthesize bitmapErrorToastView;
@property(nonatomic, retain) NSSegmentedControl *perspectiveModeControl; // @synthesize perspectiveModeControl;

@end

