//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBACanvasTree, IBAExclusionControllerObservationProxy, IBAExpansionControllerObservationProxy, IBAFilteringControllerObservationProxy, IBAHighlightControllerObservationProxy, IBAPresentationStateController, IBARepresentedSystemConstraintClassifier, IBASelectionControllerObservationProxy, IBAViewHierarchy;
@protocol IBACanvasTreeAdapterDataSource;

@interface IBACanvasTreeAdapter : NSObject
{
    IBACanvasTree *_canvasTree;
    IBAViewHierarchy *_viewHierarchy;
    IBAPresentationStateController *_presentationStateController;
    id <IBACanvasTreeAdapterDataSource> _dataSource;
    double _hiddenItemsOpacity;
    IBAExclusionControllerObservationProxy *_exclusionObservationProxy;
    IBAExpansionControllerObservationProxy *_expansionObservationProxy;
    IBAHighlightControllerObservationProxy *_highlightObservationProxy;
    IBASelectionControllerObservationProxy *_selectionObservationProxy;
    IBAFilteringControllerObservationProxy *_filteringObservationProxy;
    IBARepresentedSystemConstraintClassifier *_systemConstraintClassifier;
}

+ (unsigned long long)itemTypeForRepresentedObject:(id)arg1;
+ (BOOL)representedObjectIsScreen:(id)arg1;
+ (unsigned long long)canvasBitmapStateForImageError:(id)arg1;
+ (id)bitmapComponentAffectingProperties;
+ (BOOL)representedObjectIsLayer:(id)arg1;
+ (BOOL)representedObjectIsLayoutConstraint:(id)arg1;
+ (BOOL)representedObjectIsLayoutGuide:(id)arg1;
+ (BOOL)representedObjectIsView:(id)arg1;
@property(readonly, nonatomic) IBARepresentedSystemConstraintClassifier *systemConstraintClassifier; // @synthesize systemConstraintClassifier=_systemConstraintClassifier;
@property(retain, nonatomic) IBAFilteringControllerObservationProxy *filteringObservationProxy; // @synthesize filteringObservationProxy=_filteringObservationProxy;
@property(retain, nonatomic) IBASelectionControllerObservationProxy *selectionObservationProxy; // @synthesize selectionObservationProxy=_selectionObservationProxy;
@property(retain, nonatomic) IBAHighlightControllerObservationProxy *highlightObservationProxy; // @synthesize highlightObservationProxy=_highlightObservationProxy;
@property(retain, nonatomic) IBAExpansionControllerObservationProxy *expansionObservationProxy; // @synthesize expansionObservationProxy=_expansionObservationProxy;
@property(retain, nonatomic) IBAExclusionControllerObservationProxy *exclusionObservationProxy; // @synthesize exclusionObservationProxy=_exclusionObservationProxy;
@property(nonatomic) double hiddenItemsOpacity; // @synthesize hiddenItemsOpacity=_hiddenItemsOpacity;
@property(nonatomic) __weak id <IBACanvasTreeAdapterDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) IBAPresentationStateController *presentationStateController; // @synthesize presentationStateController=_presentationStateController;
@property(retain, nonatomic) IBAViewHierarchy *viewHierarchy; // @synthesize viewHierarchy=_viewHierarchy;
@property(readonly, nonatomic) IBACanvasTree *canvasTree; // @synthesize canvasTree=_canvasTree;
- (void).cxx_destruct;
- (void)filteringController:(id)arg1 didChangeFilteredStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)filteringController:(id)arg1 didChangeFilteringState:(BOOL)arg2;
- (void)selectionController:(id)arg1 didChangeSelectionStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)highlightController:(id)arg1 didChangeHighlightStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)expansionController:(id)arg1 didChangeExpansionStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)exclusionController:(id)arg1 didChangeDisabledStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)exclusionController:(id)arg1 didChangeIgnoredStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)exclusionController:(id)arg1 didChangeHiddenStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)replaceAllChildItemsOfNode:(id)arg1;
- (void)nodeChildrenDidChange:(id)arg1;
- (void)configureEmphasisStatesForItemsOfViewHierarchyNodes:(id)arg1;
- (void)configureEmphasisStatesForItemsOfViewHierarchyNode:(id)arg1;
- (void)configureVisibilityStatesForItemsWithIdentifiers:(id)arg1;
- (void)configureVisibilityStatesForItemsOfViewHierarchyNodes:(id)arg1;
- (void)configureVisibilityStatesForItemsOfViewHierarchyNode:(id)arg1;
- (id)canvasTreeItemsForViewHierarchyNodes:(id)arg1;
- (id)canvasTreeItemsWithIdentifiers:(id)arg1 includingGroups:(BOOL)arg2;
- (void)updateCanvasTreeWithChangedNode:(id)arg1 changedPropertyNames:(id)arg2 affectsChildren:(BOOL)arg3;
- (void)updateWithViewHierarchyChange:(id)arg1;
- (id)treeItemsForViewHierarchyNode:(id)arg1 recursive:(BOOL)arg2;
- (void)createCanvasTreeFromViewHierarchyNode:(id)arg1;
- (void)configureWithViewHierarchyNode:(id)arg1;
- (void)setViewHierarchy:(id)arg1 presentationStateController:(id)arg2;
- (id)initWithCanvasTree:(id)arg1;
- (void)updateScreenItems:(id)arg1 propertyWithName:(id)arg2 representedObject:(id)arg3;
- (id)screenItemsWithRepresentedObject:(id)arg1;
- (void)updateBitmapComponentForItems:(id)arg1 representedObject:(id)arg2;
- (unsigned long long)canvasBitmapStateForImage:(id)arg1 error:(id)arg2;
- (id)bitmapComponentForIdentifier:(id)arg1;
- (void)updateLayerItems:(id)arg1 propertyWithName:(id)arg2 representedObject:(id)arg3;
- (id)layerItemsWithRepresentedObject:(id)arg1;
- (void)updateLayoutConstraintItems:(id)arg1 propertyWithName:(id)arg2 representedObject:(id)arg3;
- (id)constraintItemsWithRepresentedObject:(id)arg1;
- (void)updateLayoutGuideItems:(id)arg1 propertyWithName:(id)arg2 representedObject:(id)arg3;
- (id)guideItemsWithRepresentedObject:(id)arg1;
- (void)updateViewItems:(id)arg1 propertyWithName:(id)arg2 representedObject:(id)arg3;
- (id)viewItemsWithRepresentedObject:(id)arg1;

@end

