//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSDictionary, NSMutableDictionary;

@interface IBACanvasThemeEditorModel : NSObject <NSCoding>
{
    NSArray *_orderedKeys;
    NSDictionary *_keyTitles;
    NSMutableDictionary *_values;
}

+ (id)modelWithCanvasTheme:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
@property(readonly, copy, nonatomic) NSDictionary *keyTitles; // @synthesize keyTitles=_keyTitles;
@property(readonly, copy, nonatomic) NSArray *orderedKeys; // @synthesize orderedKeys=_orderedKeys;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)summary;
- (void)applyToCanvasTheme:(id)arg1;
- (id)initWithValues:(id)arg1;

@end

