//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBACanvasSceneView, IBACanvasTreeItem;

@protocol IBACanvasSceneViewDelegate <NSObject>
- (void)canvasSceneView:(IBACanvasSceneView *)arg1 didToggleStatistics:(BOOL)arg2;
- (void)canvasSceneView:(IBACanvasSceneView *)arg1 didChangeZoomFactor:(double)arg2 animated:(BOOL)arg3;
- (void)canvasSceneView:(IBACanvasSceneView *)arg1 toggleTreeItemExpansion:(IBACanvasTreeItem *)arg2 includeChildren:(BOOL)arg3;
- (void)canvasSceneView:(IBACanvasSceneView *)arg1 didSelectTreeItem:(IBACanvasTreeItem *)arg2;
- (void)canvasSceneView:(IBACanvasSceneView *)arg1 didMouseOverTreeItem:(IBACanvasTreeItem *)arg2;
- (void)canvasSceneView:(IBACanvasSceneView *)arg1 didFocusTreeItem:(IBACanvasTreeItem *)arg2;
- (struct CGRect)canvasSceneView:(IBACanvasSceneView *)arg1 mouseTrackingRectForVisibleRect:(struct CGRect)arg2;
@end

