//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBAColorFormat, IBARepresentedObjectModel, NSArray, NSColor, NSString;

@interface IBAColorInspectorViewModel : IBAInspectorViewModel
{
    NSColor *_color;
    IBAColorFormat *_colorFormat;
    NSString *_colorCode;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (id)colorCodeForColor:(id)arg1 format:(id)arg2;
+ (id)colorForColorCode:(id)arg1 format:(id)arg2 referenceColor:(id)arg3;
+ (BOOL)providedColor:(id)arg1 isBasicallyEqualToColor:(id)arg2;
+ (id)colorSwatchImageForColor:(id)arg1 inRect:(struct CGRect)arg2;
+ (id)stringToColorTransformer;
+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(copy, nonatomic) NSString *colorCode; // @synthesize colorCode=_colorCode;
@property(retain, nonatomic) IBAColorFormat *colorFormat; // @synthesize colorFormat=_colorFormat;
@property(retain, nonatomic) NSColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *colorFormats;
- (void)setColorCode:(id)arg1 updateAttributeValue:(BOOL)arg2;
- (void)setColor:(id)arg1 updateAttributeValue:(BOOL)arg2;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

