//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface IBACanvasButtonCell : NSButtonCell
{
}

- (id)initTextCell:(id)arg1;
- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;

@end

