//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class IBACanvasThemeEditorModel, NSString, NSTableView;

@interface IBACanvasThemeEditorWindowController : NSWindowController <NSTableViewDataSource, NSTableViewDelegate>
{
    NSTableView *_tableView;
    IBACanvasThemeEditorModel *_defaultModel;
    IBACanvasThemeEditorModel *_model;
}

+ (void)applyModelOnAllCanvasThemes:(id)arg1;
+ (id)modelFromFirstCanvasTheme;
+ (id)canvasThemeForCanvasViewController:(id)arg1;
+ (id)canvasViewControllers;
+ (id)controller;
@property(retain, nonatomic) IBACanvasThemeEditorModel *model; // @synthesize model=_model;
@property(retain, nonatomic) IBACanvasThemeEditorModel *defaultModel; // @synthesize defaultModel=_defaultModel;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)imageCellValueChanged:(id)arg1;
- (void)colorCellValueChanged:(id)arg1;
- (void)boolCellValueChanged:(id)arg1;
- (void)numberCellValueChanged:(id)arg1;
- (void)stringCellValueChanged:(id)arg1;
- (void)applyDefaultTheme:(id)arg1;
- (void)applyTheme:(id)arg1;
- (void)resetTheme:(id)arg1;
- (void)saveTheme:(id)arg1;
- (void)loadTheme:(id)arg1;
- (void)copyThemeToClipboard:(id)arg1;
- (void)didChangeCellControl:(id)arg1 withNewValue:(id)arg2;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

