//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton, NSSlider, NSTextField;

@interface IBADeveloperWindowController : NSWindowController
{
    NSSlider *_canvas3DZDepthSlider;
    NSTextField *_canvas3DZDepthTextField;
    NSButton *_sceneStatisticsEnabledButton;
    NSTextField *_canvasRotateFromTextField;
    NSTextField *_canvasRotateToTextField;
    NSTextField *_canvasRotateDurationTextField;
    NSTextField *_canvasRotateDelayTextField;
    NSButton *_canvasRotateLinear;
    NSTextField *_focusHistoryReplayDuration;
    NSTextField *_focusHistoryReplayDelay;
}

+ (id)controller;
@property(retain) NSTextField *focusHistoryReplayDelay; // @synthesize focusHistoryReplayDelay=_focusHistoryReplayDelay;
@property(retain) NSTextField *focusHistoryReplayDuration; // @synthesize focusHistoryReplayDuration=_focusHistoryReplayDuration;
@property(retain) NSButton *canvasRotateLinear; // @synthesize canvasRotateLinear=_canvasRotateLinear;
@property(retain) NSTextField *canvasRotateDelayTextField; // @synthesize canvasRotateDelayTextField=_canvasRotateDelayTextField;
@property(retain) NSTextField *canvasRotateDurationTextField; // @synthesize canvasRotateDurationTextField=_canvasRotateDurationTextField;
@property(retain) NSTextField *canvasRotateToTextField; // @synthesize canvasRotateToTextField=_canvasRotateToTextField;
@property(retain) NSTextField *canvasRotateFromTextField; // @synthesize canvasRotateFromTextField=_canvasRotateFromTextField;
@property(retain) NSButton *sceneStatisticsEnabledButton; // @synthesize sceneStatisticsEnabledButton=_sceneStatisticsEnabledButton;
@property(retain) NSTextField *canvas3DZDepthTextField; // @synthesize canvas3DZDepthTextField=_canvas3DZDepthTextField;
@property(retain) NSSlider *canvas3DZDepthSlider; // @synthesize canvas3DZDepthSlider=_canvas3DZDepthSlider;
- (void).cxx_destruct;
- (id)firstRootViewController;
- (id)allCanvasSceneViews;
- (id)allSceneKitViews;
- (void)updateGeometrySortOrder:(id)arg1;
- (BOOL)isSceneKitStatisticsEnabled;
- (void)sceneKitStatisticsEnabledDidChange:(id)arg1;
- (void)resetUserLicenseAcceptance:(id)arg1;
- (void)forceCrash:(id)arg1;
- (void)replayFocusHistory:(id)arg1;
- (void)rotateCanvas:(id)arg1;
- (void)resetCanvasPan:(id)arg1;
- (void)dumpSCNNodeHierarchy:(id)arg1;
- (void)dumpSceneNodeHierarchy:(id)arg1;
- (void)postNotificationForCanvas3DZDepthChange;
- (void)canvas3DZDepthTextFieldChanged:(id)arg1;
- (void)canvas3DZDepthSliderValueChanged:(id)arg1;
- (void)windowDidLoad;

@end

