//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSToolbarDelegate-Protocol.h"

@class NSToolbar;

@interface IBADocumentToolbarController : NSObject <NSToolbarDelegate>
{
    // Error parsing type: , name: defaultToolbarItems
    // Error parsing type: , name: allowedToolbarItems
    // Error parsing type: , name: rightFixedWidthItems
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: timer
    // Error parsing type: , name: toolbar
    // Error parsing type: , name: licenseReminderUpdateInterval
}

- (CDUnknownBlockType).cxx_destruct;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (void)toolbarDidRemoveItem:(id)arg1;
- (void)toolbarWillAddItem:(id)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (void)beginApplicationActivation:(id)arg1;
- (void)dealloc;
- (id)init;
@property(nonatomic) __weak NSToolbar *toolbar; // @synthesize toolbar;

@end

