//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "IBARevealDocumentObserver-Protocol.h"
#import "IBASampleAppWindowControllerDelegate-Protocol.h"

@interface IBADocumentContentViewController : NSViewController <IBARevealDocumentObserver, IBASampleAppWindowControllerDelegate>
{
    // Error parsing type: , name: document
    // Error parsing type: , name: welcomeContentViewController
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)controller:(id)arg1 controllerDidLaunchAndConnectToApp:(BOOL)arg2;
- (void)revealDocumentDidUpdateViewHierarchy:(id)arg1;
- (void)revealDocumentDidEndRefreshingApplicationStateSnapshot:(id)arg1;
- (void)revealDocumentWillBeginRefreshingApplicationStateSnapshot:(id)arg1;
- (void)revealDocumentDidReset:(id)arg1;
- (void)inspectSampleApp:(id)arg1;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;
- (void)viewWillAppear;
- (void)viewDidLoad;

@end

