//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumberFormatter.h>

@class NSNumber;

@interface IBADefaultValueNumberFormatter : NSNumberFormatter
{
    NSNumber *_defaultValue;
}

@property(copy) NSNumber *defaultValue; // @synthesize defaultValue=_defaultValue;
- (void).cxx_destruct;
- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;

@end

