//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSNumber;

@interface IBAEdgeInsetsInspectorViewModel : IBAInspectorViewModel
{
    NSNumber *_top;
    NSNumber *_left;
    NSNumber *_bottom;
    NSNumber *_right;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) NSNumber *right; // @synthesize right=_right;
@property(retain, nonatomic) NSNumber *bottom; // @synthesize bottom=_bottom;
@property(retain, nonatomic) NSNumber *left; // @synthesize left=_left;
@property(retain, nonatomic) NSNumber *top; // @synthesize top=_top;
- (void).cxx_destruct;
@property(nonatomic) struct NSEdgeInsets edgeInsetsValue;
@property(readonly, nonatomic) NSNumber *rightMax;
@property(readonly, nonatomic) NSNumber *rightMin;
@property(readonly, nonatomic) NSNumber *bottomMax;
@property(readonly, nonatomic) NSNumber *bottomMin;
@property(readonly, nonatomic) NSNumber *leftMax;
@property(readonly, nonatomic) NSNumber *leftMin;
@property(readonly, nonatomic) NSNumber *topMax;
@property(readonly, nonatomic) NSNumber *topMin;
- (id)description;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

