//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _TtC6Reveal33IBAInclusivePresentationStateShim;

@interface IBAExclusionController : NSObject
{
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: stateModel
    // Error parsing type: , name: stateChangePublisher
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: delegate
    // Error parsing type: , name: conditionallyExcludedClassNames
    // Error parsing type: , name: options
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (BOOL)isNodeWithIdentifierIgnored:(id)arg1;
- (BOOL)isNodeWithIdentifierDisabled:(id)arg1;
- (BOOL)isNodeWithIdentifierHidden:(id)arg1;
@property(nonatomic, readonly) _TtC6Reveal33IBAInclusivePresentationStateShim *presentationState;
- (void)correctExclusionOptionsToRemoveIgnoredStateFromNodes:(id)arg1;
- (id)addObserver:(id)arg1;

@end

