//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface IBAFontFamily : NSObject
{
    NSString *_familyName;
    NSArray *_fontNames;
}

@property(copy, nonatomic) NSArray *fontNames; // @synthesize fontNames=_fontNames;
@property(copy, nonatomic) NSString *familyName; // @synthesize familyName=_familyName;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqualToFontFamily:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)debugDescription;
- (id)description;
@property(readonly, copy, nonatomic) NSArray *sortedFontNames;
@property(readonly, copy, nonatomic) NSString *familyNameForHumans;
- (id)initWithFamilyName:(id)arg1 fontNames:(id)arg2;

@end

