//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBAViewHierarchyNode, _TtC6Reveal26IBAUndoHistoryProviderShim, _TtC6Reveal33IBAExclusivePresentationStateShim;

@interface IBAFocusController : NSObject
{
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: stateModel
    // Error parsing type: , name: stateChangePublisher
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: disabledFocusClassNames.storage
    // Error parsing type: , name: undoManager
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)focusOnViewHierarchyNode:(id)arg1 savePreviousFocus:(BOOL)arg2;
- (BOOL)canFocusOnViewHierarchyNode:(id)arg1;
@property(nonatomic, readonly) IBAViewHierarchyNode *focusedNode;
@property(nonatomic, readonly) _TtC6Reveal26IBAUndoHistoryProviderShim *undoHistoryProvider;
@property(nonatomic, readonly) _TtC6Reveal33IBAExclusivePresentationStateShim *presentationState;
- (id)addObserver:(id)arg1;

@end

