//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IBAFilteringController;

@protocol IBAFilteringControllerDelegate

@optional
- (void)filteringControllerDidUpdateMatchStates:(IBAFilteringController *)arg1 filterChanged:(BOOL)arg2;
- (void)filteringControllerWillUpdateMatchStates:(IBAFilteringController *)arg1 filterChanged:(BOOL)arg2;
@end

