//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewController.h"

@class NSPopUpButton, NSStepper, NSTextField;

@interface IBAFontInspectorViewController : IBAInspectorViewController
{
    NSPopUpButton *_fontFamilyPopUpButton;
    NSPopUpButton *_fontPopUpButton;
    NSTextField *_fontSizeTextField;
    NSStepper *_fontSizeStepper;
}

@property(retain, nonatomic) NSStepper *fontSizeStepper; // @synthesize fontSizeStepper=_fontSizeStepper;
@property(retain, nonatomic) NSTextField *fontSizeTextField; // @synthesize fontSizeTextField=_fontSizeTextField;
@property(retain, nonatomic) NSPopUpButton *fontPopUpButton; // @synthesize fontPopUpButton=_fontPopUpButton;
@property(retain, nonatomic) NSPopUpButton *fontFamilyPopUpButton; // @synthesize fontFamilyPopUpButton=_fontFamilyPopUpButton;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

