//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAFilteringController : NSObject
{
    // Error parsing type: , name: filter
    // Error parsing type: , name: isFiltered
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: stateModel
    // Error parsing type: , name: stateChangePublisher
    // Error parsing type: , name: matchState
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)isNodeWithIdentifierDescendentOfNodeThatMatchesFilterQuery:(id)arg1;
- (BOOL)isNodeWithIdentifierAncestorOfNodeThatMatchesFilterQuery:(id)arg1;
- (BOOL)nodeWithIdentifierMatchesFilterQuery:(id)arg1;

@end

