//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IBAFontValue : NSObject
{
    NSString *_familyName;
    NSString *_fontName;
    double _pointSize;
}

+ (id)fontWithFamilyName:(id)arg1 fontName:(id)arg2 size:(double)arg3;
@property(nonatomic) double pointSize; // @synthesize pointSize=_pointSize;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
@property(copy, nonatomic) NSString *familyName; // @synthesize familyName=_familyName;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqualToValue:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)updateFontValue:(id)arg1;
- (id)initWithFamilyName:(id)arg1 fontName:(id)arg2 size:(double)arg3;

@end

