//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAFocusController : NSObject
{
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: stateModel
    // Error parsing type: , name: stateChangePublisher
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: disabledFocusClassNames.storage
    // Error parsing type: , name: undoManager
}

- (void).cxx_destruct;
- (id)init;

@end

