//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBAFontValue, IBARepresentedObjectModel, NSArray, NSNumber;

@interface IBAFontInspectorViewModel : IBAInspectorViewModel
{
    NSArray *_availableFontFamilies;
    NSArray *_availableFonts;
    IBAFontValue *_selectedFontValue;
    NSNumber *_selectedFontFamilyIndex;
    NSNumber *_selectedFontIndex;
    NSNumber *_selectedFontSize;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (id)sortedFontFamiliesWithFontFamilies:(id)arg1;
+ (id)fontFamiliesByAddingFontValue:(id)arg1 toFontFamilies:(id)arg2;
+ (unsigned long long)indexOfFontName:(id)arg1 inFontNames:(id)arg2;
+ (unsigned long long)indexOfFamilyName:(id)arg1 inFontFamilies:(id)arg2;
+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) NSNumber *selectedFontSize; // @synthesize selectedFontSize=_selectedFontSize;
@property(retain, nonatomic) NSNumber *selectedFontIndex; // @synthesize selectedFontIndex=_selectedFontIndex;
@property(retain, nonatomic) NSNumber *selectedFontFamilyIndex; // @synthesize selectedFontFamilyIndex=_selectedFontFamilyIndex;
@property(retain, nonatomic) IBAFontValue *selectedFontValue; // @synthesize selectedFontValue=_selectedFontValue;
@property(copy, nonatomic) NSArray *availableFonts; // @synthesize availableFonts=_availableFonts;
@property(copy, nonatomic) NSArray *availableFontFamilies; // @synthesize availableFontFamilies=_availableFontFamilies;
- (void).cxx_destruct;
- (id)fontValueForCurrentPropertySelections;
- (void)updateSelectedFontValue;
@property(readonly, nonatomic) NSNumber *maximumFontSize;
@property(readonly, nonatomic) NSNumber *minimumFontSize;
- (BOOL)validateSelectedFontSize:(inout id *)arg1 error:(id *)arg2;
- (id)description;
- (void)updateFontForFontFamilyIndex:(id)arg1;
- (void)populateAvailableFontsForFontFamilyIndex:(id)arg1;
- (void)initializeWithFontValue:(id)arg1 dataModel:(id)arg2;
- (void)setDataModel:(id)arg1;
- (Class)representingInspectorViewControllerClass;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;

@end

