//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IBAGCDAsyncSocket, NSData, NSError, NSString, NSURL, OS_dispatch_queue;

@protocol IBAGCDAsyncSocketDelegate

@optional
- (void)socket:(IBAGCDAsyncSocket *)arg1 didReceiveTrust:(struct __SecTrust *)arg2 completionHandler:(void (^)(BOOL))arg3;
- (void)socketDidSecure:(IBAGCDAsyncSocket *)arg1;
- (void)socketDidDisconnect:(IBAGCDAsyncSocket *)arg1 withError:(NSError *)arg2;
- (void)socketDidCloseReadStream:(IBAGCDAsyncSocket *)arg1;
- (double)socket:(IBAGCDAsyncSocket *)arg1 shouldTimeoutWriteWithTag:(long long)arg2 elapsed:(double)arg3 bytesDone:(unsigned long long)arg4;
- (double)socket:(IBAGCDAsyncSocket *)arg1 shouldTimeoutReadWithTag:(long long)arg2 elapsed:(double)arg3 bytesDone:(unsigned long long)arg4;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didWritePartialDataOfLength:(unsigned long long)arg2 tag:(long long)arg3;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didWriteDataWithTag:(long long)arg2;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didReadPartialDataOfLength:(unsigned long long)arg2 tag:(long long)arg3;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didReadData:(NSData *)arg2 withTag:(long long)arg3;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didConnectToUrl:(NSURL *)arg2;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didConnectToHost:(NSString *)arg2 port:(unsigned short)arg3;
- (void)socket:(IBAGCDAsyncSocket *)arg1 didAcceptNewSocket:(IBAGCDAsyncSocket *)arg2;
- (OS_dispatch_queue *)newSocketQueueForConnectionFromAddress:(NSData *)arg1 onSocket:(IBAGCDAsyncSocket *)arg2;
@end

