//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor, NSGradient;

@interface IBAGradientView : NSView
{
    // Error parsing type: , name: gradientLayer
    // Error parsing type: , name: gradient
    // Error parsing type: , name: direction
}

- (void).cxx_destruct;
@property(nonatomic, retain) NSGradient *gradient; // @synthesize gradient;
@property(nonatomic, retain) NSColor *backgroundColor;
- (void)layout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

