//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IBAHighlightController, NSSet;

@protocol IBAHighlightControllerObserver
- (void)highlightController:(IBAHighlightController *)arg1 didChangeHighlightStateOfIdentifiers:(NSSet *)arg2 toValue:(BOOL)arg3;
@end

