//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedAttribute, IBARepresentedObject, IBARevealDataModel, NSString;

@interface IBAInspectorViewModel : NSObject
{
    BOOL _editable;
    IBARepresentedAttribute *_representedAttribute;
    IBARepresentedObject *_representedObject;
    IBARevealDataModel *_dataModel;
    NSString *_labelText;
    NSString *_labelTooltipText;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
@property(nonatomic, getter=isEditable) BOOL editable; // @synthesize editable=_editable;
@property(copy, nonatomic) NSString *labelTooltipText; // @synthesize labelTooltipText=_labelTooltipText;
@property(copy, nonatomic) NSString *labelText; // @synthesize labelText=_labelText;
@property(retain, nonatomic) IBARevealDataModel *dataModel; // @synthesize dataModel=_dataModel;
@property(readonly, nonatomic) IBARepresentedObject *representedObject; // @synthesize representedObject=_representedObject;
@property(readonly, nonatomic) IBARepresentedAttribute *representedAttribute; // @synthesize representedAttribute=_representedAttribute;
- (void).cxx_destruct;
- (id)initWithRepresentedObject:(id)arg1;
- (id)initWithRepresentedAttribute:(id)arg1;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
- (Class)representingInspectorViewControllerClass;

@end

