//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAInspectorDataDefaults : NSObject
{
}

+ (BOOL)validateValue:(id)arg1 forAttribute:(id)arg2 error:(id *)arg3;
+ (BOOL)valueIsEditableForAttribute:(id)arg1;
+ (id)incrementValueForAttribute:(id)arg1;
+ (id)maximumDisplayValueForAttribute:(id)arg1;
+ (id)minimumDisplayValueForAttribute:(id)arg1;
+ (id)nonNegativeAttributeKeyPaths;

@end

