//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface IBAInspectorSection : NSObject
{
    NSMutableArray *_subSections;
    NSString *_title;
}

@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (id)subSectionAtIndex:(unsigned long long)arg1;
- (void)attachInspectorSubsection:(id)arg1;
- (id)addSubSectionWithTitle:(id)arg1;
- (unsigned long long)countOfSubSections;
@property(readonly, copy, nonatomic) NSArray *subSections;
- (id)initWithTitle:(id)arg1;
- (id)init;

@end

