//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBANetworkRequestOperation.h"

@class NSImage;

@interface IBAImageRequestOperation : IBANetworkRequestOperation
{
    // Error parsing type: , name: image
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithRequest:(id)arg1 session:(id)arg2;
@property(nonatomic, readonly) id responseData;
- (void)main;
@property(nonatomic, retain) NSImage *image; // @synthesize image;

@end

