//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAInspectorDataSourceFactory : NSObject
{
    // Error parsing type: , name: dataModel
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)dataSourceForLayoutInspectorWithRepresentedObjects:(id)arg1;
- (id)dataSourceForAttributesInspectorWithRepresentedObjects:(id)arg1;
- (id)dataSourceForIdentityInspectorWithRepresentedObjects:(id)arg1;
- (id)dataSourceForDocumentInspector;
- (id)initWithDataModel:(id)arg1;

@end

