//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface IBAInspectorViewModelFactory : NSObject
{
    NSMutableDictionary *_nameToInspectorViewModelClassMap;
    NSMutableDictionary *_typeToInspectorViewModelClassMap;
    NSMutableSet *_registeredClasses;
}

+ (id)defaultModelFactory;
- (void).cxx_destruct;
- (id)inspectorViewModelsForAttributes:(id)arg1;
- (id)makeInspectorModelWithName:(id)arg1 forObject:(id)arg2;
- (id)makeInspectorModelForObject:(id)arg1;
- (id)makeInspectorModelWithName:(id)arg1 forAttribute:(id)arg2;
- (id)makeInspectorModelForAttribute:(id)arg1;
- (Class)inspectorViewModelClassForRepresentedType:(id)arg1;
- (Class)inspectorViewModelClassWithName:(id)arg1;
- (void)registerInspectorModelClass:(Class)arg1;
- (id)init;

@end

