//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSArray, NSNib;

@interface IBAInspectorSectionViewController : NSViewController
{
    // Error parsing type: , name: elements
    // Error parsing type: , name: headerNib
    // Error parsing type: , name: separatorNib
    // Error parsing type: , name: edgeInsets
    // Error parsing type: , name: isRootSection
    // Error parsing type: , name: elementContents
    // Error parsing type: , name: isEmpty
    // Error parsing type: , name: elementsDisposeBag
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) BOOL empty; // @synthesize empty=isEmpty;
- (BOOL)isEmpty;
- (void)viewDidLoad;
- (void)loadView;
@property(nonatomic) BOOL isRootSection; // @synthesize isRootSection;
@property(nonatomic) struct NSEdgeInsets edgeInsets; // @synthesize edgeInsets;
@property(nonatomic, retain) NSNib *separatorNib; // @synthesize separatorNib;
@property(nonatomic, retain) NSNib *headerNib; // @synthesize headerNib;
@property(nonatomic, copy) NSArray *elements; // @synthesize elements;

@end

