//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAViewController.h"

@class IBAInspectorSectionViewController, NSLayoutConstraint, NSScrollView;
@protocol IBAInspectorStackViewControllerDataSource, IBAInspectorStackViewControllerDelegate;

@interface IBAInspectorStackViewController : IBAViewController
{
    BOOL _needsReloadData;
    BOOL _shouldDisplayNoSelection;
    BOOL _shouldDisplayNotApplicable;
    id <IBAInspectorStackViewControllerDataSource> _dataSource;
    id <IBAInspectorStackViewControllerDelegate> _delegate;
    NSScrollView *_scrollView;
    IBAInspectorSectionViewController *_rootSectionViewController;
    NSLayoutConstraint *_rootInspectorViewWidthConstraint;
}

+ (void)insertContentView:(id)arg1 inContainer:(id)arg2 withBottomMargin:(double)arg3;
@property BOOL shouldDisplayNotApplicable; // @synthesize shouldDisplayNotApplicable=_shouldDisplayNotApplicable;
@property BOOL shouldDisplayNoSelection; // @synthesize shouldDisplayNoSelection=_shouldDisplayNoSelection;
@property(nonatomic) BOOL needsReloadData; // @synthesize needsReloadData=_needsReloadData;
@property(retain, nonatomic) NSLayoutConstraint *rootInspectorViewWidthConstraint; // @synthesize rootInspectorViewWidthConstraint=_rootInspectorViewWidthConstraint;
@property(retain) IBAInspectorSectionViewController *rootSectionViewController; // @synthesize rootSectionViewController=_rootSectionViewController;
@property(retain) NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <IBAInspectorStackViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <IBAInspectorStackViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)updateRootInspectorViewWidth;
- (void)setNeedsReloadData;
- (id)instantiateSectionViewControllerAtIndexPath:(id)arg1;
- (id)instantiateViewControllerForSubsectionAtIndexPath:(id)arg1;
- (id)instantiateViewControllerForSectionAtIndex:(unsigned long long)arg1;
- (id)instantiateRootSectionViewController;
- (void)reloadData;
- (id)viewControllerForInspectorAtIndexPath:(id)arg1 objectValue:(id)arg2;
- (struct NSEdgeInsets)edgeInsetsForSectionAtIndexPath:(id)arg1;
- (id)separatorNibForElementsInSectionAtIndexPath:(id)arg1;
- (id)headerNibForElementsInSectionAtIndexPath:(id)arg1;
- (id)objectValueForInspectorAtIndexPath:(id)arg1;
- (id)titleForSectionHeaderAtIndexPath:(id)arg1;
- (unsigned long long)numberOfItemsInSubSectionAtIndexPath:(id)arg1;
- (unsigned long long)numberOfSubSectionsInSection:(unsigned long long)arg1;
- (unsigned long long)numberOfSections;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)dealloc;

@end

