//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAViewController.h"

@class IBAInspectorViewModel, NSObjectController, NSTextField;

@interface IBAInspectorViewController : IBAViewController
{
    NSTextField *_labelTextField;
    NSObjectController *_objectController;
    IBAInspectorViewModel *_viewModel;
}

+ (id)keyPathsForValuesAffectingEmpty;
+ (id)keyPathsForValuesAffectingEditable;
@property(retain, nonatomic) IBAInspectorViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain) NSObjectController *objectController; // @synthesize objectController=_objectController;
@property(retain, nonatomic) NSTextField *labelTextField; // @synthesize labelTextField=_labelTextField;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
@property(readonly, nonatomic, getter=isEditable) BOOL editable;
- (void)didChangeViewModel;
- (void)willChangeViewModel;
- (void)viewDidLoad;

@end

