//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAViewController.h"

#import "IBAInspectorStackViewControllerDelegate-Protocol.h"

@class IBAInspectorTabBadgeController, IBAInspectorTabControl, IBAUserDefaultsManager, NSArray, NSMutableDictionary, NSNib, NSString, NSView;

@interface IBAInspectorTabBarController : IBAViewController <IBAInspectorStackViewControllerDelegate>
{
    IBAInspectorTabControl *_tabBarView;
    NSView *_inspectorTabContainerView;
    NSArray *_viewControllers;
    IBAViewController *_selectedViewController;
    IBAInspectorTabBadgeController *_badgeController;
    NSMutableDictionary *_dataSources;
    IBAUserDefaultsManager *_userDefaultsManager;
    NSNib *_sectionDividerNib;
    NSNib *_sectionHeaderNib;
    NSNib *_subsectionHeaderNib;
}

@property(readonly, nonatomic) NSNib *subsectionHeaderNib; // @synthesize subsectionHeaderNib=_subsectionHeaderNib;
@property(readonly, nonatomic) NSNib *sectionHeaderNib; // @synthesize sectionHeaderNib=_sectionHeaderNib;
@property(readonly, nonatomic) NSNib *sectionDividerNib; // @synthesize sectionDividerNib=_sectionDividerNib;
@property(readonly, nonatomic) IBAUserDefaultsManager *userDefaultsManager; // @synthesize userDefaultsManager=_userDefaultsManager;
@property(readonly, nonatomic) NSMutableDictionary *dataSources; // @synthesize dataSources=_dataSources;
@property(retain, nonatomic) IBAInspectorTabBadgeController *badgeController; // @synthesize badgeController=_badgeController;
@property(nonatomic) __weak IBAViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(retain, nonatomic) NSView *inspectorTabContainerView; // @synthesize inspectorTabContainerView=_inspectorTabContainerView;
@property(retain, nonatomic) IBAInspectorTabControl *tabBarView; // @synthesize tabBarView=_tabBarView;
- (void).cxx_destruct;
- (id)inspectorStackViewController:(id)arg1 viewControllerForInspectorAtIndexPath:(id)arg2 objectValue:(id)arg3;
- (struct NSEdgeInsets)inspectorStackViewController:(id)arg1 edgeInsetsForSectionAtIndexPath:(id)arg2;
- (id)inspectorStackViewController:(id)arg1 separatorNibForElementsInSectionAtIndexPath:(id)arg2;
- (id)inspectorStackViewController:(id)arg1 headerNibForElementsInSectionAtIndexPath:(id)arg2;
- (void)handleSelectedSegmentChange:(id)arg1;
- (void)setDataSource:(id)arg1 forTabIndex:(unsigned long long)arg2;
- (void)setDataModel:(id)arg1 selectedObjects:(id)arg2;
- (void)viewDidLoad;
- (void)didSelectIndex:(unsigned long long)arg1;
@property(nonatomic) unsigned long long selectedIndex;
- (void)selectDefaultTab;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

