//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBAInspectorStackViewController, NSIndexPath, NSNib, NSViewController;

@protocol IBAInspectorStackViewControllerDelegate <NSObject>
- (NSViewController *)inspectorStackViewController:(IBAInspectorStackViewController *)arg1 viewControllerForInspectorAtIndexPath:(NSIndexPath *)arg2 objectValue:(id)arg3;
- (struct NSEdgeInsets)inspectorStackViewController:(IBAInspectorStackViewController *)arg1 edgeInsetsForSectionAtIndexPath:(NSIndexPath *)arg2;
- (NSNib *)inspectorStackViewController:(IBAInspectorStackViewController *)arg1 separatorNibForElementsInSectionAtIndexPath:(NSIndexPath *)arg2;
- (NSNib *)inspectorStackViewController:(IBAInspectorStackViewController *)arg1 headerNibForElementsInSectionAtIndexPath:(NSIndexPath *)arg2;
@end

