//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSNumber;

@interface IBALocationCoordinate2DViewModel : IBAInspectorViewModel
{
    NSNumber *_longitude;
    NSNumber *_latitude;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(copy, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
- (void).cxx_destruct;
@property(nonatomic) struct CLLocationCoordinate2D locationCoordinate2DValue;
- (id)longitudeMax;
- (id)longitudeMin;
- (id)latitudeMax;
- (id)latitudeMin;
- (id)description;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

