//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewController.h"

@class IBALinkableInspectorTextField, NSLayoutConstraint, NSTextField, NSTrackingArea;

@interface IBALayoutConstraintDetailInspectorViewController : IBAInspectorViewController
{
    NSTextField *_firstItemLabelTextField;
    NSTextField *_secondItemLabelTextField;
    NSTextField *_relationLabelTextField;
    NSTextField *_constantLabelTextField;
    NSTextField *_priorityLabelTextField;
    NSTextField *_multiplierLabelTextField;
    IBALinkableInspectorTextField *_firstItemTextField;
    IBALinkableInspectorTextField *_secondItemTextField;
    NSTextField *_relationTextField;
    NSTextField *_constantTextField;
    NSTextField *_priorityTextField;
    NSTextField *_multiplierTextField;
    NSLayoutConstraint *_constantToSecondItemVerticalSpacing;
    NSLayoutConstraint *_constantToRelationVerticalSpacing;
    NSTrackingArea *_firstItemTrackingArea;
    NSTrackingArea *_secondItemTrackingArea;
}

@property(retain, nonatomic) NSTrackingArea *secondItemTrackingArea; // @synthesize secondItemTrackingArea=_secondItemTrackingArea;
@property(retain, nonatomic) NSTrackingArea *firstItemTrackingArea; // @synthesize firstItemTrackingArea=_firstItemTrackingArea;
@property(retain, nonatomic) NSLayoutConstraint *constantToRelationVerticalSpacing; // @synthesize constantToRelationVerticalSpacing=_constantToRelationVerticalSpacing;
@property(retain, nonatomic) NSLayoutConstraint *constantToSecondItemVerticalSpacing; // @synthesize constantToSecondItemVerticalSpacing=_constantToSecondItemVerticalSpacing;
@property(retain, nonatomic) NSTextField *multiplierTextField; // @synthesize multiplierTextField=_multiplierTextField;
@property(retain, nonatomic) NSTextField *priorityTextField; // @synthesize priorityTextField=_priorityTextField;
@property(retain, nonatomic) NSTextField *constantTextField; // @synthesize constantTextField=_constantTextField;
@property(retain, nonatomic) NSTextField *relationTextField; // @synthesize relationTextField=_relationTextField;
@property(retain, nonatomic) IBALinkableInspectorTextField *secondItemTextField; // @synthesize secondItemTextField=_secondItemTextField;
@property(retain, nonatomic) IBALinkableInspectorTextField *firstItemTextField; // @synthesize firstItemTextField=_firstItemTextField;
@property(retain, nonatomic) NSTextField *multiplierLabelTextField; // @synthesize multiplierLabelTextField=_multiplierLabelTextField;
@property(retain, nonatomic) NSTextField *priorityLabelTextField; // @synthesize priorityLabelTextField=_priorityLabelTextField;
@property(retain, nonatomic) NSTextField *constantLabelTextField; // @synthesize constantLabelTextField=_constantLabelTextField;
@property(retain, nonatomic) NSTextField *relationLabelTextField; // @synthesize relationLabelTextField=_relationLabelTextField;
@property(retain, nonatomic) NSTextField *secondItemLabelTextField; // @synthesize secondItemLabelTextField=_secondItemLabelTextField;
@property(retain, nonatomic) NSTextField *firstItemLabelTextField; // @synthesize firstItemLabelTextField=_firstItemLabelTextField;
- (void).cxx_destruct;
- (void)highlightNodeForObjectIdentifier:(id)arg1;
- (void)selectNodeForObjectIdentifier:(id)arg1;
- (void)selectSecondItemPressed:(id)arg1;
- (void)selectFirstItemPressed:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTextFieldActionButtons;
- (void)updateSecondItemViewsVisibility;
- (void)didChangeViewModel;
- (void)viewDidAppear;
- (void)viewDidLoad;

@end

