//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface IBALayoutConstraintRepresentedObjectToDescriptionTransformer : NSValueTransformer
{
    NSValueTransformer *_representedObjectToDetailedNameValueTransformer;
}

+ (id)descriptionForLayoutAttribute:(long long)arg1;
+ (id)attributeToNameMap;
+ (BOOL)isParticipatingItem:(id)arg1 selfReferenceForConstraintObject:(id)arg2 referenceObjectIdentifier:(id)arg3;
+ (id)contextualNameForParticipatingItem:(id)arg1 constraintObject:(id)arg2 referenceObjectIdentifier:(id)arg3;
+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
@property(readonly, nonatomic) NSValueTransformer *representedObjectToDetailedNameValueTransformer; // @synthesize representedObjectToDetailedNameValueTransformer=_representedObjectToDetailedNameValueTransformer;
- (void).cxx_destruct;
- (id)descriptionForParticipatingItem:(id)arg1 constraintObject:(id)arg2 correspondingAttribute:(long long)arg3 referenceObjectIdentifier:(id)arg4;
- (id)descriptionStringForPriority:(id)arg1;
- (id)descriptionStringForMultiplier:(id)arg1;
- (id)descriptionStringForConstant:(id)arg1;
- (id)descriptionForRelationshipAttribute:(id)arg1;
- (id)descriptionForConstraintRepresentedObject:(id)arg1 referenceObjectIdentifier:(id)arg2;
- (id)transformedValue:(id)arg1 referenceObjectIdentifier:(id)arg2;
- (id)transformedValue:(id)arg1;
- (id)init;

@end

