//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARevealDataModel;

@interface IBALayoutIssuesInspectorViewModel : IBAInspectorViewModel
{
    // Error parsing type: , name: itemsVariable
    // Error parsing type: , name: disposeBag
}

+ (BOOL)canModelRepresentedType:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithRepresentedAttribute:(id)arg1;
@property(nonatomic, retain) IBARevealDataModel *dataModel;
- (BOOL)isEmpty;
- (Class)representingInspectorViewControllerClass;
- (id)initWithRepresentedObject:(id)arg1;

// Remaining properties
@property(nonatomic, readonly) BOOL empty;

@end

