//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBALayoutConstraintInspectorIssueViewModel, IBARepresentedObject, IBARepresentedObjectIdentifier, IBARepresentedObjectModel, NSImage, NSNumber, NSString;

@interface IBALayoutConstraintInspectorViewModel : IBAInspectorViewModel
{
    BOOL _shouldBeArchived;
    BOOL _hasSecondItem;
    BOOL _firstItemSelectable;
    BOOL _secondItemSelectable;
    IBARepresentedObject *_referenceObject;
    NSString *_constraintDescription;
    NSImage *_constraintIcon;
    NSString *_firstItemAttributeDescription;
    NSString *_relationshipDescription;
    NSString *_secondItemAttributeDescription;
    NSNumber *_constant;
    NSNumber *_priority;
    NSNumber *_multiplier;
    IBARepresentedObjectIdentifier *_firstItemIdentifier;
    IBARepresentedObjectIdentifier *_secondItemIdentifier;
    IBALayoutConstraintInspectorIssueViewModel *_issueViewModel;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(retain) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(retain) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain) IBALayoutConstraintInspectorIssueViewModel *issueViewModel; // @synthesize issueViewModel=_issueViewModel;
@property BOOL secondItemSelectable; // @synthesize secondItemSelectable=_secondItemSelectable;
@property BOOL firstItemSelectable; // @synthesize firstItemSelectable=_firstItemSelectable;
@property(retain) IBARepresentedObjectIdentifier *secondItemIdentifier; // @synthesize secondItemIdentifier=_secondItemIdentifier;
@property(retain) IBARepresentedObjectIdentifier *firstItemIdentifier; // @synthesize firstItemIdentifier=_firstItemIdentifier;
@property BOOL hasSecondItem; // @synthesize hasSecondItem=_hasSecondItem;
@property(copy) NSNumber *multiplier; // @synthesize multiplier=_multiplier;
@property(copy, nonatomic) NSNumber *priority; // @synthesize priority=_priority;
@property(copy, nonatomic) NSNumber *constant; // @synthesize constant=_constant;
@property(nonatomic) BOOL shouldBeArchived; // @synthesize shouldBeArchived=_shouldBeArchived;
@property(copy) NSString *secondItemAttributeDescription; // @synthesize secondItemAttributeDescription=_secondItemAttributeDescription;
@property(copy) NSString *relationshipDescription; // @synthesize relationshipDescription=_relationshipDescription;
@property(copy) NSString *firstItemAttributeDescription; // @synthesize firstItemAttributeDescription=_firstItemAttributeDescription;
@property(copy) NSImage *constraintIcon; // @synthesize constraintIcon=_constraintIcon;
@property(copy) NSString *constraintDescription; // @synthesize constraintDescription=_constraintDescription;
@property(retain, nonatomic) IBARepresentedObject *referenceObject; // @synthesize referenceObject=_referenceObject;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *maximumPriority;
@property(readonly, nonatomic) NSNumber *minimumPriority;
@property(readonly) BOOL priorityIsEditable;
- (BOOL)validatePriority:(id *)arg1 error:(id *)arg2;
- (void)updateIssueViewModel;
- (void)updateConstraintDescriptionWithRepresentedObject:(id)arg1 referenceObject:(id)arg2;
- (void)updatePropertiesWithRepresentedObject:(id)arg1;
- (void)setDataModel:(id)arg1;
- (Class)representingInspectorViewControllerClass;
- (void)dealloc;
- (id)initWithRepresentedObject:(id)arg1;
- (id)initWithRepresentedAttribute:(id)arg1;
- (id)formattedDescriptionForRelation:(id)arg1;
- (id)formattedDescriptionForItem:(id)arg1 attribute:(id)arg2;

@end

