//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal22InspectorTextFieldCell.h"

@interface IBALinkableInspectorTextFieldCell : _TtC6Reveal22InspectorTextFieldCell
{
    // Error parsing type: , name: actionButtonState
    // Error parsing type: , name: actionButtonHighlighted
    // Error parsing type: , name: showActionButton
}

- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

