//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSMenu.h>

@class IBACanvasThemeEditorWindowController, IBADeveloperWindowController, NSMenuItem;

@interface IBAMainMenu : NSMenu
{
    NSMenu *_connectionMenu;
    NSMenu *_canvasMenu;
    NSMenuItem *_showSubviewFramesAndContentMenuItem;
    NSMenuItem *_showSubviewFramesMenuItem;
    NSMenuItem *_showSubviewContentMenuItem;
    NSMenuItem *_twoDimensionalMenuItem;
    NSMenuItem *_threeDimensionalMenuItem;
    NSMenuItem *_toggleDisplayHiddenItemsMenuItem;
    NSMenuItem *_toggleShowAutoLayoutMenuItem;
    NSMenuItem *_toggleDisplayExcludedItemsMenuItem;
    NSMenuItem *_toggleOutlineMenuItem;
    NSMenuItem *_toggleInspectorMenuItem;
    NSMenuItem *_toggleConnectionSheetMenuItem;
    NSMenuItem *_logLevelsMenuItem;
    NSMenuItem *_refreshMenuItem;
    NSMenuItem *_hiddenItemOpacity0MenuItem;
    NSMenuItem *_hiddenItemOpacity25MenuItem;
    NSMenuItem *_hiddenItemOpacity50MenuItem;
    NSMenuItem *_hiddenItemOpacity75MenuItem;
    NSMenuItem *_hiddenItemOpacity100MenuItem;
    NSMenuItem *_developerMenu;
    IBADeveloperWindowController *_developerWindowController;
    IBACanvasThemeEditorWindowController *_canvasThemeEditorWindowController;
}

@property(retain, nonatomic) IBACanvasThemeEditorWindowController *canvasThemeEditorWindowController; // @synthesize canvasThemeEditorWindowController=_canvasThemeEditorWindowController;
@property(retain, nonatomic) IBADeveloperWindowController *developerWindowController; // @synthesize developerWindowController=_developerWindowController;
@property(retain) NSMenuItem *developerMenu; // @synthesize developerMenu=_developerMenu;
@property(retain) NSMenuItem *hiddenItemOpacity100MenuItem; // @synthesize hiddenItemOpacity100MenuItem=_hiddenItemOpacity100MenuItem;
@property(retain) NSMenuItem *hiddenItemOpacity75MenuItem; // @synthesize hiddenItemOpacity75MenuItem=_hiddenItemOpacity75MenuItem;
@property(retain) NSMenuItem *hiddenItemOpacity50MenuItem; // @synthesize hiddenItemOpacity50MenuItem=_hiddenItemOpacity50MenuItem;
@property(retain) NSMenuItem *hiddenItemOpacity25MenuItem; // @synthesize hiddenItemOpacity25MenuItem=_hiddenItemOpacity25MenuItem;
@property(retain) NSMenuItem *hiddenItemOpacity0MenuItem; // @synthesize hiddenItemOpacity0MenuItem=_hiddenItemOpacity0MenuItem;
@property(retain) NSMenuItem *refreshMenuItem; // @synthesize refreshMenuItem=_refreshMenuItem;
@property(retain) NSMenuItem *logLevelsMenuItem; // @synthesize logLevelsMenuItem=_logLevelsMenuItem;
@property(retain) NSMenuItem *toggleConnectionSheetMenuItem; // @synthesize toggleConnectionSheetMenuItem=_toggleConnectionSheetMenuItem;
@property(retain) NSMenuItem *toggleInspectorMenuItem; // @synthesize toggleInspectorMenuItem=_toggleInspectorMenuItem;
@property(retain) NSMenuItem *toggleOutlineMenuItem; // @synthesize toggleOutlineMenuItem=_toggleOutlineMenuItem;
@property(retain) NSMenuItem *toggleDisplayExcludedItemsMenuItem; // @synthesize toggleDisplayExcludedItemsMenuItem=_toggleDisplayExcludedItemsMenuItem;
@property(retain) NSMenuItem *toggleShowAutoLayoutMenuItem; // @synthesize toggleShowAutoLayoutMenuItem=_toggleShowAutoLayoutMenuItem;
@property(retain) NSMenuItem *toggleDisplayHiddenItemsMenuItem; // @synthesize toggleDisplayHiddenItemsMenuItem=_toggleDisplayHiddenItemsMenuItem;
@property(retain) NSMenuItem *threeDimensionalMenuItem; // @synthesize threeDimensionalMenuItem=_threeDimensionalMenuItem;
@property(retain) NSMenuItem *twoDimensionalMenuItem; // @synthesize twoDimensionalMenuItem=_twoDimensionalMenuItem;
@property(retain) NSMenuItem *showSubviewContentMenuItem; // @synthesize showSubviewContentMenuItem=_showSubviewContentMenuItem;
@property(retain) NSMenuItem *showSubviewFramesMenuItem; // @synthesize showSubviewFramesMenuItem=_showSubviewFramesMenuItem;
@property(retain) NSMenuItem *showSubviewFramesAndContentMenuItem; // @synthesize showSubviewFramesAndContentMenuItem=_showSubviewFramesAndContentMenuItem;
@property(retain) NSMenu *canvasMenu; // @synthesize canvasMenu=_canvasMenu;
@property(retain) NSMenu *connectionMenu; // @synthesize connectionMenu=_connectionMenu;
- (void).cxx_destruct;
- (void)unregisterFromConnectionChangeNotifications;
- (void)registerForConnectionChangeNotifications;
- (void)updateConnectionsMenu;
- (void)updateLogLevelMenuItems;
- (void)toggleLogLevel:(id)arg1;
- (void)toggleSmartMeasurements:(id)arg1;
- (void)showCanvasThemeEditor:(id)arg1;
- (void)showDeveloperWindow:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

