//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableSet;
@protocol IBAMobileDeviceAccessListener;

@interface IBAMobileDeviceAccess : NSObject
{
    NSMutableArray *_devices;
    NSMutableSet *_quarantinedDeviceConnectionIDs;
    BOOL _subscribed;
    struct _am_device_notification *_notification;
    id <IBAMobileDeviceAccessListener> _listener;
}

@property __weak id <IBAMobileDeviceAccessListener> listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)arg1;
- (void)didReceiveDeviceNotification:(struct am_device_notification_callback_info *)arg1;
- (void)deviceDidDisconnect:(struct _am_device *)arg1;
- (BOOL)deviceDidConnect:(struct _am_device *)arg1;
- (BOOL)isDeviceQuarantined:(struct _am_device *)arg1;
- (void)removeQuarantinedDevice:(struct _am_device *)arg1;
- (void)addQuarantinedDevice:(struct _am_device *)arg1;
@property(readonly, copy, nonatomic) NSArray *devices;
- (void)dealloc;
- (id)initWithListener:(id)arg1;
- (id)init;

@end

