//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSMenu.h>

@class NSMenuItem;

@interface IBAMainMenu : NSMenu
{
    // Error parsing type: , name: developerWindowController.storage
    // Error parsing type: , name: canvasThemeEditorWindowController.storage
    // Error parsing type: , name: connectionMenu
    // Error parsing type: , name: canvasMenu
    // Error parsing type: , name: showSubviewFramesAndContentMenuItem
    // Error parsing type: , name: showSubviewFramesMenuItem
    // Error parsing type: , name: showSubviewContentMenuItem
    // Error parsing type: , name: twoDimensionalMenuItem
    // Error parsing type: , name: threeDimensionalMenuItem
    // Error parsing type: , name: toggleDisplayHiddenItemsMenuItem
    // Error parsing type: , name: toggleShowAutoLayoutMenuItem
    // Error parsing type: , name: toggleDisplayExcludedItemsMenuItem
    // Error parsing type: , name: toggleOutlineMenuItem
    // Error parsing type: , name: toggleInspectorMenuItem
    // Error parsing type: , name: toggleConnectionSheetMenuItem
    // Error parsing type: , name: refreshMenuItem
    // Error parsing type: , name: hiddenItemOpacity0MenuItem
    // Error parsing type: , name: hiddenItemOpacity25MenuItem
    // Error parsing type: , name: hiddenItemOpacity50MenuItem
    // Error parsing type: , name: hiddenItemOpacity75MenuItem
    // Error parsing type: , name: hiddenItemOpacity100MenuItem
    // Error parsing type: , name: developerMenu
}

- (void).cxx_destruct;
- (void)updateConnectionsMenu;
- (void)toggleSmartMeasurements:(id)arg1;
- (void)showCanvasThemeEditor:(id)arg1;
- (void)showDeveloperWindow:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithTitle:(id)arg1;
@property(nonatomic, retain) NSMenuItem *developerMenu; // @synthesize developerMenu;
@property(nonatomic, retain) NSMenuItem *hiddenItemOpacity100MenuItem; // @synthesize hiddenItemOpacity100MenuItem;
@property(nonatomic, retain) NSMenuItem *hiddenItemOpacity75MenuItem; // @synthesize hiddenItemOpacity75MenuItem;
@property(nonatomic, retain) NSMenuItem *hiddenItemOpacity50MenuItem; // @synthesize hiddenItemOpacity50MenuItem;
@property(nonatomic, retain) NSMenuItem *hiddenItemOpacity25MenuItem; // @synthesize hiddenItemOpacity25MenuItem;
@property(nonatomic, retain) NSMenuItem *hiddenItemOpacity0MenuItem; // @synthesize hiddenItemOpacity0MenuItem;
@property(nonatomic, retain) NSMenuItem *refreshMenuItem; // @synthesize refreshMenuItem;
@property(nonatomic, retain) NSMenuItem *toggleConnectionSheetMenuItem; // @synthesize toggleConnectionSheetMenuItem;
@property(nonatomic, retain) NSMenuItem *toggleInspectorMenuItem; // @synthesize toggleInspectorMenuItem;
@property(nonatomic, retain) NSMenuItem *toggleOutlineMenuItem; // @synthesize toggleOutlineMenuItem;
@property(nonatomic, retain) NSMenuItem *toggleDisplayExcludedItemsMenuItem; // @synthesize toggleDisplayExcludedItemsMenuItem;
@property(nonatomic, retain) NSMenuItem *toggleShowAutoLayoutMenuItem; // @synthesize toggleShowAutoLayoutMenuItem;
@property(nonatomic, retain) NSMenuItem *toggleDisplayHiddenItemsMenuItem; // @synthesize toggleDisplayHiddenItemsMenuItem;
@property(nonatomic, retain) NSMenuItem *threeDimensionalMenuItem; // @synthesize threeDimensionalMenuItem;
@property(nonatomic, retain) NSMenuItem *twoDimensionalMenuItem; // @synthesize twoDimensionalMenuItem;
@property(nonatomic, retain) NSMenuItem *showSubviewContentMenuItem; // @synthesize showSubviewContentMenuItem;
@property(nonatomic, retain) NSMenuItem *showSubviewFramesMenuItem; // @synthesize showSubviewFramesMenuItem;
@property(nonatomic, retain) NSMenuItem *showSubviewFramesAndContentMenuItem; // @synthesize showSubviewFramesAndContentMenuItem;
@property(nonatomic, retain) NSMenu *canvasMenu; // @synthesize canvasMenu;
@property(nonatomic, retain) NSMenu *connectionMenu; // @synthesize connectionMenu;

@end

