//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSNumber;

@interface IBAMapCoordinateRegionInspectorViewModel : IBAInspectorViewModel
{
    NSNumber *_centerLatitude;
    NSNumber *_centerLongitude;
    NSNumber *_spanLongitudeDelta;
    NSNumber *_spanLatitudeDelta;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) NSNumber *spanLatitudeDelta; // @synthesize spanLatitudeDelta=_spanLatitudeDelta;
@property(retain, nonatomic) NSNumber *spanLongitudeDelta; // @synthesize spanLongitudeDelta=_spanLongitudeDelta;
@property(retain, nonatomic) NSNumber *centerLongitude; // @synthesize centerLongitude=_centerLongitude;
@property(retain, nonatomic) NSNumber *centerLatitude; // @synthesize centerLatitude=_centerLatitude;
- (void).cxx_destruct;
@property(nonatomic) CDStruct_2b0c6e0b regionValue;
@property(readonly, nonatomic) NSNumber *spanLatitudeDeltaMax;
@property(readonly, nonatomic) NSNumber *spanLatitudeDeltaMin;
@property(readonly, nonatomic) NSNumber *spanLongitudeDeltaMax;
@property(readonly, nonatomic) NSNumber *spanLongitudeDeltaMin;
@property(readonly, nonatomic) NSNumber *centerLongitudeMax;
@property(readonly, nonatomic) NSNumber *centerLongitudeMin;
@property(readonly, nonatomic) NSNumber *centerLatitudeMax;
@property(readonly, nonatomic) NSNumber *centerLatitudeMin;
- (id)description;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

