//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBANormalizedQuadraticCurve : NSObject
{
    // Error parsing type: , name: coefficientA
    // Error parsing type: , name: coefficientB
    // Error parsing type: , name: baseSlope
    // Error parsing type: , name: maximumValue
}

- (id)init;
- (double)solveForXWithY:(double)arg1;
- (double)calculateYForX:(double)arg1;
- (id)copyWithZone:(void *)arg1;
- (id)initWithBaseSlope:(double)arg1 maximumValue:(double)arg2;
@property(nonatomic, readonly) double maximumValue; // @synthesize maximumValue;
@property(nonatomic, readonly) double baseSlope; // @synthesize baseSlope;

@end

