//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@class IBANormalizedQuadraticCurve;

@interface IBANonlinearScaleValueTransformer : NSValueTransformer
{
    double _minimum;
    double _midpoint;
    double _maximum;
    double _normalizedMidpoint;
    IBANormalizedQuadraticCurve *_secondPartNormalizedCurve;
}

+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
@property(readonly, copy, nonatomic) IBANormalizedQuadraticCurve *secondPartNormalizedCurve; // @synthesize secondPartNormalizedCurve=_secondPartNormalizedCurve;
@property(readonly, nonatomic) double normalizedMidpoint; // @synthesize normalizedMidpoint=_normalizedMidpoint;
@property(readonly, nonatomic) double maximum; // @synthesize maximum=_maximum;
@property(readonly, nonatomic) double midpoint; // @synthesize midpoint=_midpoint;
@property(readonly, nonatomic) double minimum; // @synthesize minimum=_minimum;
- (void).cxx_destruct;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;
- (id)initWithMinimum:(double)arg1 midpoint:(double)arg2 maximum:(double)arg3 normalizedMidpoint:(double)arg4;
- (id)init;

@end

