//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBANormalizedQuadraticCurve : NSObject
{
    double _baseSlope;
    double _maximumValue;
    double _coefficientA;
    double _coefficientB;
}

@property(readonly, nonatomic) double coefficientB; // @synthesize coefficientB=_coefficientB;
@property(readonly, nonatomic) double coefficientA; // @synthesize coefficientA=_coefficientA;
@property(readonly, nonatomic) double maximumValue; // @synthesize maximumValue=_maximumValue;
@property(readonly, nonatomic) double baseSlope; // @synthesize baseSlope=_baseSlope;
- (double)solveForXWithY:(double)arg1;
- (double)calculateYForX:(double)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithBaseSlope:(double)arg1 maximumValue:(double)arg2;

@end

