//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSNumber;

@interface IBANumberInspectorViewModel : IBAInspectorViewModel
{
    NSNumber *_displayValue;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) NSNumber *displayValue; // @synthesize displayValue=_displayValue;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *incrementValueBy;
@property(readonly, nonatomic) NSNumber *maxDisplayValue;
@property(readonly, nonatomic) NSNumber *minDisplayValue;
- (BOOL)validateDisplayValue:(id *)arg1 error:(id *)arg2;
- (id)description;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (BOOL)isEditable;
- (Class)representingInspectorViewControllerClass;

@end

