//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewController.h"

@class NSStepper, NSTextField;

@interface IBANumberInspectorViewController : IBAInspectorViewController
{
    NSTextField *_textField;
    NSStepper *_stepper;
}

@property(retain) NSStepper *stepper; // @synthesize stepper=_stepper;
@property(retain) NSTextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)setupIncrementByValue;
- (void)didChangeViewModel;
- (void)viewDidLoad;

@end

