//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSOutlineView.h>

@class NSMutableDictionary;

@interface IBAOutlineView : NSOutlineView
{
    NSMutableDictionary *_registeredClasses;
}

- (void).cxx_destruct;
- (id)makeViewWithIdentifier:(id)arg1 owner:(id)arg2;
- (void)registerClass:(Class)arg1 forIdentifier:(id)arg2;

@end

