//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBAOutlineViewTreeItemLayoutIssueAdaptor, IBARepresentedObjectIdentifier, IBAViewHierarchyNodeFilterResultAdaptor, NSArray, NSImage, NSMutableArray, NSString;

@interface IBAOutlineViewTreeItem : NSObject
{
    NSMutableArray *_childItems;
    BOOL _enabled;
    BOOL _emphasized;
    NSString *_title;
    NSImage *_image;
    NSString *_queryString;
    IBAViewHierarchyNodeFilterResultAdaptor *_filterResultAdaptor;
    IBAOutlineViewTreeItemLayoutIssueAdaptor *_layoutIssueAdaptor;
    IBAOutlineViewTreeItem *_parentItem;
    IBARepresentedObjectIdentifier *_identifier;
    struct _NSRange _queryExclusionRange;
}

+ (id)keyPathsForValuesAffectingHasDefaultFilterResults;
+ (id)keyPathsForValuesAffectingHasFilterResults;
@property(readonly, copy, nonatomic) IBARepresentedObjectIdentifier *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak IBAOutlineViewTreeItem *parentItem; // @synthesize parentItem=_parentItem;
@property(retain, nonatomic) IBAOutlineViewTreeItemLayoutIssueAdaptor *layoutIssueAdaptor; // @synthesize layoutIssueAdaptor=_layoutIssueAdaptor;
@property(retain, nonatomic) IBAViewHierarchyNodeFilterResultAdaptor *filterResultAdaptor; // @synthesize filterResultAdaptor=_filterResultAdaptor;
@property(nonatomic) struct _NSRange queryExclusionRange; // @synthesize queryExclusionRange=_queryExclusionRange;
@property(copy, nonatomic) NSString *queryString; // @synthesize queryString=_queryString;
@property(nonatomic, getter=isEmphasized) BOOL emphasized; // @synthesize emphasized=_emphasized;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL hasDefaultFilterResults;
@property(readonly, nonatomic) BOOL hasFilterResults;
- (id)debugDescription;
- (void)insertChildItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addChildItem:(id)arg1;
- (unsigned long long)countOfChildItems;
@property(readonly, copy, nonatomic) NSArray *childItems;
- (id)initWithTitle:(id)arg1 image:(id)arg2 identifier:(id)arg3;
@property(nonatomic, readonly) NSArray *parentItems;

@end

