//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSProgress;

@interface IBAOperation : NSOperation
{
    BOOL _executing;
    BOOL _finished;
    BOOL _shouldDispatchCompletionBlockOnMainQueue;
    NSProgress *_progress;
}

@property(readonly, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property BOOL shouldDispatchCompletionBlockOnMainQueue; // @synthesize shouldDispatchCompletionBlockOnMainQueue=_shouldDispatchCompletionBlockOnMainQueue;
@property(nonatomic, getter=isFinished) BOOL finished; // @synthesize finished=_finished;
@property(nonatomic, getter=isExecuting) BOOL executing; // @synthesize executing=_executing;
- (void).cxx_destruct;
- (void)done;
- (void)main;
- (void)start;
- (BOOL)isAsynchronous;
- (void)setCompletionBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

