//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBAOutlineViewModelReloadable-Protocol.h"

@interface IBAOutlineViewModelBatchingProxy : NSObject <IBAOutlineViewModelReloadable>
{
    // Error parsing type: , name: target
    // Error parsing type: , name: transactionsCount
    // Error parsing type: , name: completionHandlers
    // Error parsing type: , name: needsReloadData
    // Error parsing type: , name: needsReloadSelection
    // Error parsing type: , name: identifiersToExpand
    // Error parsing type: , name: identifiersToCollapse
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)collapseItemsWithIdentifiers:(id)arg1;
- (void)expandItemsWithIdentifiers:(id)arg1;
- (void)reloadSelection;
- (void)reloadData;
- (void)notifyWhenBatchEndsUsingBlock:(CDUnknownBlockType)arg1;
- (void)endUpdates;
- (void)beginUpdates;
@property(nonatomic, readonly) BOOL isBatchingUpdates;
- (id)initWithTarget:(id)arg1;

@end

