//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectIdentifier, IBARepresentedObjectModel, NSString;

@interface IBAObjectIdentifierInspectorViewModel : IBAInspectorViewModel
{
    IBARepresentedObjectIdentifier *_objectIdentifier;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (id)keyPathsForValuesAffectingDisplayValue;
+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) IBARepresentedObjectIdentifier *objectIdentifier; // @synthesize objectIdentifier=_objectIdentifier;
- (void).cxx_destruct;
- (BOOL)isEditable;
- (void)dealloc;
@property(readonly, copy, nonatomic) NSString *displayValue;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

