//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class IBARepresentedObjectModel, NSNumber;

@interface IBAPointInspectorViewModel : IBAInspectorViewModel
{
    NSNumber *_x;
    NSNumber *_y;
    id _attributeObserver;
    IBARepresentedObjectModel *_representedObjectModel;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) IBARepresentedObjectModel *representedObjectModel; // @synthesize representedObjectModel=_representedObjectModel;
@property(readonly, nonatomic) id attributeObserver; // @synthesize attributeObserver=_attributeObserver;
@property(retain, nonatomic) NSNumber *y; // @synthesize y=_y;
@property(retain, nonatomic) NSNumber *x; // @synthesize x=_x;
- (void).cxx_destruct;
@property(nonatomic) struct CGPoint pointValue;
@property(readonly, nonatomic) NSNumber *yMax;
@property(readonly, nonatomic) NSNumber *yMin;
@property(readonly, nonatomic) NSNumber *xMax;
@property(readonly, nonatomic) NSNumber *xMin;
- (id)description;
- (void)dealloc;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

