//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBAFilteringControllerDelegate-Protocol.h"

@class IBAExclusionController, IBAExpansionController, IBAFilteringController, IBAFocusController, IBAHighlightController, IBASelectionController, IBAViewHierarchy, _TtC6Reveal34IBAPresentationStateControllerShim;
@protocol IBAPresentationStateControllerDelegate;

@interface IBAPresentationStateController : NSObject <IBAFilteringControllerDelegate>
{
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: stateModel
    // Error parsing type: , name: highlightController
    // Error parsing type: , name: selectionController
    // Error parsing type: , name: expansionController
    // Error parsing type: , name: filterController
    // Error parsing type: , name: focusController
    // Error parsing type: , name: exclusionController
    // Error parsing type: , name: delegate
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: filterQuery
    // Error parsing type: , name: filterOptions
    // Error parsing type: , name: unfilteredExpansionState
    // Error parsing type: , name: unfilteredSelectionState
    // Error parsing type: , name: filteringSelectionObserverDisposeBag
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)filteringControllerDidUpdateMatchStates:(id)arg1 filterChanged:(BOOL)arg2;
- (void)filteringControllerWillUpdateMatchStates:(id)arg1 filterChanged:(BOOL)arg2;
@property(nonatomic, readonly) BOOL canHideExcludedItems;
- (id)mementoForCurrentStateUnfiltered:(BOOL)arg1;
- (void)viewHierarchyDidUpdateWithChangeSet:(id)arg1;
@property(nonatomic) __weak id <IBAPresentationStateControllerDelegate> delegate; // @synthesize delegate;
@property(nonatomic, readonly) IBAExclusionController *exclusionController; // @synthesize exclusionController;
@property(nonatomic, readonly) IBAFocusController *focusController; // @synthesize focusController;
@property(nonatomic, readonly) IBAFilteringController *filterController; // @synthesize filterController;
@property(nonatomic, readonly) IBAExpansionController *expansionController; // @synthesize expansionController;
@property(nonatomic, readonly) IBASelectionController *selectionController; // @synthesize selectionController;
@property(nonatomic, readonly) IBAHighlightController *highlightController; // @synthesize highlightController;
@property(nonatomic, readonly) IBAViewHierarchy *viewHierarchy; // @synthesize viewHierarchy;
@property(nonatomic, readonly) _TtC6Reveal34IBAPresentationStateControllerShim *shim;

@end

