//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface IBAPresentationStateMemento : NSObject <NSCopying>
{
    // Error parsing type: , name: preservedIdentifierStates
    // Error parsing type: , name: preservedFilterOptions
}

- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(void *)arg1;

@end

