//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBADualNumberFieldViewController.h"

@class IBAInspectorTextField, NSStepper;

@interface IBAQuadNumberFieldViewController : IBADualNumberFieldViewController
{
    IBAInspectorTextField *_thirdTextField;
    IBAInspectorTextField *_fourthTextField;
    NSStepper *_thirdStepper;
    NSStepper *_fourthStepper;
}

+ (id)viewController;
@property(nonatomic) __weak NSStepper *fourthStepper; // @synthesize fourthStepper=_fourthStepper;
@property(nonatomic) __weak NSStepper *thirdStepper; // @synthesize thirdStepper=_thirdStepper;
@property(nonatomic) __weak IBAInspectorTextField *fourthTextField; // @synthesize fourthTextField=_fourthTextField;
@property(nonatomic) __weak IBAInspectorTextField *thirdTextField; // @synthesize thirdTextField=_thirdTextField;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

