//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBARepresentedAttribute;

@protocol IBARepresentedAttributeDelegate <NSObject>
- (void)representedAttribute:(IBARepresentedAttribute *)arg1 didChangeFromValue:(id)arg2 toValue:(id)arg3;
@end

