//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedObjectIdentifier, NSString;

@interface IBARepresentedObjectImageRequest : NSObject
{
    // Error parsing type: , name: variation
    // Error parsing type: , name: identifier
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqualToRequest:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) NSString *description;
- (id)initWithObjectIdentifier:(id)arg1 variation:(long long)arg2;
@property(nonatomic, readonly) IBARepresentedObjectIdentifier *identifier; // @synthesize identifier;
@property(nonatomic, readonly) long long variation; // @synthesize variation;

@end

