//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedAttribute.h"

@class IBAFontValue, IBARepresentedObjectIdentifier, NSArray, NSColor, NSDate, NSNumber, NSString, NSURL, NSUUID, _TtC6Reveal17RepresentedObject;

@interface IBARepresentedAttribute (Reveal)
@property(nonatomic, copy) NSString *stringEnumerationValue;
@property(nonatomic, readonly) BOOL isStringEnumerationValue;
@property(nonatomic) long long integerEnumerationValue;
@property(nonatomic, readonly) BOOL isIntegerEnumerationValue;
@property(nonatomic, readonly) _TtC6Reveal17RepresentedObject *representedObjectValue;
@property(nonatomic, readonly) IBARepresentedObjectIdentifier *objectIdentifierValue;
@property(nonatomic, readonly) BOOL isObjectIdentifierValue;
@property(nonatomic) CDStruct_90e2a262 mapRectValue;
@property(nonatomic) CDStruct_2b0c6e0b mapCoordinateRegionValue;
@property(nonatomic) struct CLLocationCoordinate2D locationCoordinate2DValue;
@property(nonatomic, retain) IBAFontValue *fontValue;
@property(nonatomic, copy) NSDate *dateValue;
@property(nonatomic, retain) NSColor *colorValue;
@property(nonatomic, copy) NSString *calendarIdentifierValue;
@property(nonatomic, copy) NSString *localeIdentifierValue;
@property(nonatomic, copy) NSString *timeZoneNameValue;
@property(nonatomic, copy) NSURL *urlValue;
@property(nonatomic, copy) NSUUID *UUIDValue;
@property(nonatomic) float floatValue;
@property(nonatomic) double doubleValue;
@property(nonatomic) double CGFloatValue;
@property(nonatomic) unsigned long long unsignedIntegerValue;
@property(nonatomic) long long integerValue;
@property(nonatomic) struct IBADirectionalEdgeInsets directionalEdgeInsetsValue;
@property(nonatomic) struct _IBAHorizontalAndVerticalLayoutPriority horizontalAndVerticalLayoutPriorityValue;
@property(nonatomic) long long maskValue;
@property(nonatomic, retain) NSNumber *maskNumberValue;
@property(nonatomic) BOOL boolValue;
@property(nonatomic) struct _IBAOffset offsetValue;
@property(nonatomic) struct NSEdgeInsets edgeInsetsValue;
@property(nonatomic) struct CGSize sizeValue;
@property(nonatomic, readonly) BOOL isSizeValue;
@property(nonatomic) struct CGRect rectValue;
@property(nonatomic) struct CGPoint pointValue;
@property(nonatomic) struct CATransform3D CATransform3DValue;
@property(nonatomic) struct CGAffineTransform affineTransformValue;
@property(nonatomic, copy) NSArray *arrayOfRepresentedObjectsValue;
@property(nonatomic, copy) NSString *stringValue;
@property(nonatomic, retain) NSNumber *numberValue;
@end

