//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSDictionary, NSString;

@protocol IBARevealSimulatorHelper
- (oneway void)launchApplicationWithPath:(NSString *)arg1 deviceTypeIdentifier:(NSString *)arg2 sdkVersion:(NSString *)arg3 environment:(NSDictionary *)arg4 args:(NSArray *)arg5 timeout:(double)arg6 completionHandler:(void (^)(BOOL, NSError *))arg7;
- (oneway void)availableSimulatorSDKVersionsWithCompletionHandler:(void (^)(NSArray *, NSError *))arg1;
- (oneway void)prepareWithCompletionHandler:(void (^)(BOOL, NSError *))arg1;
@end

