//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBARevealSimulatorHelperDelegate-Protocol.h"

@class NSString;
@protocol IBARevealSimulatorHelperDelegate;

@interface IBARevealSimulatorHelperDelegateHolder : NSObject <IBARevealSimulatorHelperDelegate>
{
    id <IBARevealSimulatorHelperDelegate> _delegate;
}

- (void).cxx_destruct;
- (oneway void)simulatorApplicationLauncherSessionDidStart:(BOOL)arg1 withError:(id)arg2;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

