//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@class NSString;

@interface IBARefreshScriptCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;
@property(readonly, copy, nonatomic) NSString *applicationBundleIdentifier;
@property(readonly, copy, nonatomic) NSString *applicationName;
@property(readonly, copy, nonatomic) NSString *deviceName;
@property(readonly, nonatomic) long long refreshWhen;

@end

