//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal17RepresentedObject.h"

@class NSArray, NSString, _TtC6Reveal15RepresentedView;

@interface IBARepresentedLayer : _TtC6Reveal17RepresentedObject
{
}

@property(nonatomic, readonly) struct CATransform3D transform;
@property(nonatomic, readonly) double zPosition;
@property(nonatomic, readonly) struct CGPoint position;
@property(nonatomic, readonly) struct CGRect frame;
@property(nonatomic, readonly) struct CGRect bounds;
@property(nonatomic, readonly) double opacity;
@property(nonatomic, readonly) BOOL isHidden;
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) NSArray *sublayers;
@property(nonatomic, readonly) _TtC6Reveal15RepresentedView *view;
@property(nonatomic, readonly) NSString *debugDescription;

@end

