//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "IBAFocusControllerObserver-Protocol.h"
#import "NSPathControlDelegate-Protocol.h"

@class IBARevealViewHierarchyPathControl, NSSegmentedControl;

@interface IBARevealContentViewController : NSViewController <NSPathControlDelegate, IBAFocusControllerObserver>
{
    // Error parsing type: , name: viewFocusHistoryControl
    // Error parsing type: , name: viewFocusPathControl
    // Error parsing type: , name: focusObservationProxy
    // Error parsing type: , name: notificationDisposeBag
    // Error parsing type: , name: presentationStateController
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)focusController:(id)arg1 didChangeFocusedNode:(id)arg2;
- (BOOL)pathControl:(id)arg1 acceptDrop:(id)arg2;
- (unsigned long long)pathControl:(id)arg1 validateDrop:(id)arg2;
- (void)historyPathControlComponentPressed:(id)arg1;
- (void)historyNavigationButtonPressed:(id)arg1;
@property(nonatomic, retain) IBARevealViewHierarchyPathControl *viewFocusPathControl; // @synthesize viewFocusPathControl;
@property(nonatomic, retain) NSSegmentedControl *viewFocusHistoryControl; // @synthesize viewFocusHistoryControl;

@end

