//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString;

@interface IBARevealSnapshotSerializerMetadata : NSObject
{
    // Error parsing type: , name: applicationName
    // Error parsing type: , name: applicationIcon
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithApplicationName:(id)arg1 applicationIcon:(id)arg2;
@property(nonatomic, readonly) NSImage *applicationIcon; // @synthesize applicationIcon;
@property(nonatomic, readonly) NSString *applicationName; // @synthesize applicationName;

@end

