//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IBARepresentedLocale : NSObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: name
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *debugDescription;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 name:(id)arg2;
@property(nonatomic, readonly) NSString *name; // @synthesize name;
@property(nonatomic, readonly) NSString *identifier; // @synthesize identifier;

@end

