//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSBox.h>

@interface IBARevealColoredBorderedView : NSBox
{
    // Error parsing type: , name: borderWidthUnit
    // Error parsing type: , name: borderedEdges
}

- (void)drawRect:(struct CGRect)arg1;
- (void)prepareForInterfaceBuilder;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isOpaque;

// Remaining properties
@property(nonatomic, readonly) BOOL opaque;

@end

