//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBARepresentedObjectModelDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString;
@protocol IBARepresentedObjectModelChangeObserverDelegate;

@interface IBARepresentedObjectModelChangeObserver : NSObject <IBARepresentedObjectModelDelegate>
{
    NSMutableSet *_objectsAdded;
    NSMutableSet *_objectsRemoved;
    NSMutableArray *_attributeValueChanges;
    BOOL _batchingChanges;
    id <IBARepresentedObjectModelChangeObserverDelegate> _delegate;
}

@property(getter=isBatchingChanges) BOOL batchingChanges; // @synthesize batchingChanges=_batchingChanges;
@property(nonatomic) __weak id <IBARepresentedObjectModelChangeObserverDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)objectModel:(id)arg1 didChangeAttributeValue:(id)arg2 toValue:(id)arg3 forAttribute:(id)arg4 ofRepresentedObject:(id)arg5;
- (void)objectModel:(id)arg1 didRemoveRepresentedObject:(id)arg2;
- (void)objectModel:(id)arg1 didAddRepresentedObject:(id)arg2;
- (BOOL)hasChanges;
- (void)publishPendingChangeSet;
- (BOOL)shouldPublishChangeSet;
- (void)publishPendingChangeSetIfNecessary;
- (void)endBatchingChanges;
- (void)beginBatchingChanges;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

