//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNotification;

@protocol IBARevealDocumentObserver <NSObject>

@optional
- (void)revealDocumentDidUpdateViewHierarchy:(NSNotification *)arg1;
- (void)revealDocumentDidEndRefreshingApplicationStateSnapshot:(NSNotification *)arg1;
- (void)revealDocumentWillBeginRefreshingApplicationStateSnapshot:(NSNotification *)arg1;
- (void)revealDocumentDidReset:(NSNotification *)arg1;
- (void)revealDocumentWillReset:(NSNotification *)arg1;
@end

