//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSSet;

@interface IBARepresentedObjectModelChangeSet : NSObject
{
    NSSet *_objectsAdded;
    NSSet *_objectsRemoved;
    NSSet *_objectsChanged;
    NSDictionary *_attributesChanged;
}

- (void).cxx_destruct;
- (BOOL)hasChanges;
- (id)attributeChangesForRepresentedObjects:(id)arg1;
- (id)attributeChangesForRepresentedObject:(id)arg1;
- (id)objectsChanged;
- (id)objectsRemoved;
- (id)objectsAdded;
- (id)initWithAddedObjects:(id)arg1 removedObjects:(id)arg2 attributeValueChanges:(id)arg3;

@end

