//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedType.h"

@class NSString;

@interface IBARepresentedClass : IBARepresentedType
{
    unsigned long long _precalculatedHash;
    NSString *_displayName;
    IBARepresentedClass *_parentClass;
}

+ (id)typeNameDemangler;
@property(copy, nonatomic) IBARepresentedClass *parentClass; // @synthesize parentClass=_parentClass;
@property(readonly, copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (BOOL)isSubclassOfRepresentedClassNamed:(id)arg1;
- (BOOL)isSubclassOfRepresentedClass:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqualToRepresentedClass:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)initWithName:(id)arg1 parentClass:(id)arg2;

@end

