//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBARepresentedAttribute, IBARepresentedObject, NSString;

@protocol IBARepresentedObjectDelegate <NSObject>
- (id)representedObject:(IBARepresentedObject *)arg1 valueForSyntheticAttributeWithKeyPath:(NSString *)arg2;
- (void)representedObject:(IBARepresentedObject *)arg1 attributeValueDidChangeFromValue:(id)arg2 toValue:(id)arg3 forAttribute:(IBARepresentedAttribute *)arg4;
@end

