//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBAFontValue, IBARepresentedClass, IBARepresentedObject, IBARepresentedType, NSArray, NSColor, NSDate, NSNumber, NSString;
@protocol IBARepresentedAttributeDelegate;

@interface IBARepresentedAttribute : NSObject
{
    BOOL _editable;
    id <IBARepresentedAttributeDelegate> _delegate;
    IBARepresentedObject *_representedObject;
    IBARepresentedClass *_onClass;
    NSString *_keyPath;
    IBARepresentedType *_attributeType;
    id _attributeValue;
}

+ (id)numberToStringTransformer;
+ (id)stringToFontTransformer;
+ (id)stringToDateTransformer;
+ (id)stringToColorTransformer;
@property(readonly, nonatomic, getter=isEditable) BOOL editable; // @synthesize editable=_editable;
@property(retain, nonatomic) id attributeValue; // @synthesize attributeValue=_attributeValue;
@property(readonly) IBARepresentedType *attributeType; // @synthesize attributeType=_attributeType;
@property(readonly) NSString *keyPath; // @synthesize keyPath=_keyPath;
@property(readonly) IBARepresentedClass *onClass; // @synthesize onClass=_onClass;
@property __weak IBARepresentedObject *representedObject; // @synthesize representedObject=_representedObject;
@property __weak id <IBARepresentedAttributeDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (BOOL)hasAttributeValue;
- (id)initWithKeyPath:(id)arg1 onClass:(id)arg2 type:(id)arg3 value:(id)arg4 editable:(BOOL)arg5;
@property(nonatomic, copy) NSString *stringEnumerationValue;
@property(nonatomic, readonly) BOOL isStringEnumerationValue;
@property(nonatomic) long long integerEnumerationValue;
@property(nonatomic, readonly) BOOL isIntegerEnumerationValue;
- (id)representedObjectValue;
@property(copy, nonatomic) NSArray *arrayOfRepresentedObjectsValue;
@property(nonatomic) CDStruct_90e2a262 mapRectValue;
@property(readonly) BOOL isMapRectValue;
@property(nonatomic) CDStruct_2b0c6e0b mapCoordinateRegionValue;
@property(readonly) BOOL isMapCoordinateRegionValue;
@property(nonatomic) struct CLLocationCoordinate2D locationCoordinate2DValue;
@property(readonly) BOOL isLocationCoordinate2DValue;
- (double)doubleValue;
- (float)floatValue;
- (double)CGFloatValue;
@property(copy, nonatomic) NSString *calendarIdentifierValue;
- (BOOL)isCalendarValue;
@property(copy, nonatomic) NSString *localeIdentifierValue;
- (BOOL)isLocaleValue;
@property(copy, nonatomic) NSString *timeZoneNameValue;
- (BOOL)isTimeZoneValue;
- (id)URLValue;
- (BOOL)isURLValue;
- (id)UUIDValue;
- (BOOL)isUUIDValue;
- (unsigned long long)unsignedIntegerValue;
- (long long)integerValue;
- (void)setStringValue:(id)arg1;
- (id)stringValue;
- (id)numberValue;
- (void)setNumberValue:(id)arg1;
- (BOOL)isNumberValue;
- (BOOL)isStringValue;
@property struct IBADirectionalEdgeInsets directionalEdgeInsetsValue;
- (BOOL)isDirectionalEdgeInsetsValue;
- (struct _IBAHorizontalAndVerticalLayoutPriority)horizontalAndVerticalLayoutPriorityValue;
- (void)setHorizontalAndVerticalLayoutPriorityValue:(struct _IBAHorizontalAndVerticalLayoutPriority)arg1;
- (BOOL)isHorizontalAndVerticalLayoutPriorityValue;
@property(retain, nonatomic) NSNumber *maskNumberValue;
- (unsigned long long)maskValue;
- (BOOL)isMaskValue;
- (void)setBoolValue:(BOOL)arg1;
- (BOOL)boolValue;
- (BOOL)isBoolValue;
@property(retain, nonatomic) IBAFontValue *fontValue;
- (BOOL)isFontValue;
@property(retain, nonatomic) NSDate *dateValue;
- (BOOL)isDateValue;
@property(retain, nonatomic) NSColor *colorValue;
- (BOOL)isColorValue;
- (struct _IBAOffset)offsetValue;
- (void)setOffsetValue:(struct _IBAOffset)arg1;
- (BOOL)isOffsetValue;
- (BOOL)isRectValue;
- (BOOL)isCATransform3DValue;
- (struct CATransform3D)CATransform3DValue;
@property(readonly) BOOL isAffineTransformValue;
@property(nonatomic) struct CGAffineTransform affineTransformValue;
- (void)setEdgeInsetsValue:(struct NSEdgeInsets)arg1;
- (struct NSEdgeInsets)edgeInsetsValue;
- (id)objectIdentifierValue;
- (BOOL)isObjectIdentifierValue;
- (BOOL)isArrayValue;
- (BOOL)isEdgeInsetsValue;
- (void)setRectValue:(struct CGRect)arg1;
- (struct CGRect)rectValue;
- (struct CGRect)CGRectValue;
- (BOOL)isPointValue;
- (void)setPointValue:(struct CGPoint)arg1;
- (struct CGPoint)pointValue;
- (struct CGPoint)CGPointValue;
- (void)setSizeValue:(struct CGSize)arg1;
- (BOOL)isSizeValue;
- (struct CGSize)sizeValue;
- (struct CGSize)CGSizeValue;

@end

