//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedObject.h"

@class IBARepresentedLayer, IBARepresentedWindow, NSArray;

@interface IBARepresentedView : IBARepresentedObject
{
}

- (BOOL)isDescendentOfRepresentedView:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *gestureRecognizers;
@property(readonly, copy, nonatomic) NSArray *layoutGuides;
@property(readonly, copy, nonatomic) NSArray *constraints;
@property(readonly, copy, nonatomic) NSArray *subviews;
@property(readonly, nonatomic) BOOL hidden;
@property(readonly, nonatomic) double alpha;
@property(readonly, nonatomic) struct CGPoint center;
@property(readonly, nonatomic) struct CGRect bounds;
@property(readonly, nonatomic) struct CGRect frame;
@property(readonly, nonatomic) IBARepresentedLayer *layer;
@property(readonly, nonatomic) IBARepresentedWindow *window;
@property(readonly, nonatomic) IBARepresentedView *superview;
- (id)description;

@end

