//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal17RepresentedObject.h"

#import "IBAAbstractDevice-Protocol.h"

@class NSString, NSUUID;

@interface IBARepresentedDevice : _TtC6Reveal17RepresentedObject <IBAAbstractDevice>
{
}

@property(nonatomic, readonly) BOOL isSimulator;
@property(nonatomic, readonly) NSUUID *identifierForVendor;
@property(nonatomic, readonly) NSString *systemVersion;
@property(nonatomic, readonly) NSString *systemName;
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) NSString *iba_identifier;

@end

