//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString;

@interface IBARevealSnapshotSerializerMetadata : NSObject
{
    // Error parsing type: , name: applicationName
    // Error parsing type: , name: applicationIcon
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithApplicationName:(id)arg1 applicationIcon:(id)arg2;
@property(nonatomic, readonly) NSImage *applicationIcon; // @synthesize applicationIcon;
@property(nonatomic, readonly) NSString *applicationName; // @synthesize applicationName;

@end

