//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBARepresentedObjectDelegate-Protocol.h"

@class IBARepresentedTypeRegistry, NSArray, NSMutableDictionary, NSNotificationCenter, NSSet, NSString;
@protocol IBARepresentedObjectModelDataSource, IBARepresentedObjectModelDelegate;

@interface IBARepresentedObjectModel : NSObject <IBARepresentedObjectDelegate>
{
    NSMutableDictionary *_identifierToObjectMap;
    IBARepresentedTypeRegistry *_typeRegistry;
    NSNotificationCenter *_attributeValueChangeNotificationCenter;
    id <IBARepresentedObjectModelDataSource> _dataSource;
    id <IBARepresentedObjectModelDelegate> _delegate;
}

@property __weak id <IBARepresentedObjectModelDelegate> delegate; // @synthesize delegate=_delegate;
@property __weak id <IBARepresentedObjectModelDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) IBARepresentedTypeRegistry *typeRegistry; // @synthesize typeRegistry=_typeRegistry;
- (void).cxx_destruct;
- (id)representedObject:(id)arg1 valueForSyntheticAttributeWithKeyPath:(id)arg2;
- (void)representedObject:(id)arg1 attributeValueDidChangeFromValue:(id)arg2 toValue:(id)arg3 forAttribute:(id)arg4;
- (void)removeAttributeChangeObserver:(id)arg1;
- (id)addAttributeChangeObserverForKeyPath:(id)arg1 object:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
@property(readonly, copy, nonatomic) NSArray *representedObjects;
@property(readonly, copy, nonatomic) NSSet *identifiers;
@property(readonly, nonatomic) unsigned long long count;
- (void)clear;
- (id)representedObjectForIdentifier:(id)arg1;
- (void)removeRepresentedObjectsInArray:(id)arg1;
- (void)willRemoveRepresentedObject:(id)arg1;
- (void)didRemoveRepresentedObject:(id)arg1;
- (void)removeRepresentedObject:(id)arg1;
- (void)addRepresentedObjectsFromArray:(id)arg1;
- (void)didAddRepresentedObject:(id)arg1;
- (void)willAddRepresentedObject:(id)arg1;
- (void)addRepresentedObject:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

