//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedBundle, IBARepresentedDevice, IBARepresentedScreen, NSArray, _TtC6Reveal22RepresentedApplication;

@interface IBARevealDataModelRepresentedRoots : NSObject
{
    // Error parsing type: , name: device
    // Error parsing type: , name: application
    // Error parsing type: , name: mainBundle
    // Error parsing type: , name: screens
    // Error parsing type: , name: mainScreen
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithDevice:(id)arg1 application:(id)arg2 mainBundle:(id)arg3 screens:(id)arg4 mainScreen:(id)arg5;
@property(nonatomic, readonly) IBARepresentedScreen *mainScreen; // @synthesize mainScreen;
@property(nonatomic, readonly) NSArray *screens; // @synthesize screens;
@property(nonatomic, readonly) IBARepresentedBundle *mainBundle; // @synthesize mainBundle;
@property(nonatomic, readonly) _TtC6Reveal22RepresentedApplication *application; // @synthesize application;
@property(nonatomic, readonly) IBARepresentedDevice *device; // @synthesize device;

@end

