//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedClass, IBARepresentedType, NSString, _TtC6Reveal17RepresentedObject;

@interface IBARepresentedAttribute : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: representedObject
    // Error parsing type: , name: onClass
    // Error parsing type: , name: keyPath
    // Error parsing type: , name: attributeType
    // Error parsing type: , name: value
    // Error parsing type: , name: isEditable
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *debugDescription;
@property(nonatomic, readonly) BOOL hasAttributeValue;
- (id)initWithKeyPath:(id)arg1 on:(id)arg2 type:(id)arg3 value:(id)arg4 editable:(BOOL)arg5;
@property(nonatomic, readonly) BOOL isEditable; // @synthesize isEditable;
@property(nonatomic, copy) id rawValue;
@property(nonatomic, readonly) IBARepresentedType *attributeType; // @synthesize attributeType;
@property(nonatomic, readonly) NSString *keyPath; // @synthesize keyPath;
@property(nonatomic, readonly) IBARepresentedClass *onClass; // @synthesize onClass;
@property(nonatomic, retain) _TtC6Reveal17RepresentedObject *representedObject; // @synthesize representedObject;

@end

