//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBARepresentedAttribute, IBARepresentedObject, IBARepresentedObjectModel;

@protocol IBARepresentedObjectModelDelegate <NSObject>

@optional
- (void)objectModel:(IBARepresentedObjectModel *)arg1 didChangeAttributeValue:(id)arg2 toValue:(id)arg3 forAttribute:(IBARepresentedAttribute *)arg4 ofRepresentedObject:(IBARepresentedObject *)arg5;
- (void)objectModel:(IBARepresentedObjectModel *)arg1 didRemoveRepresentedObject:(IBARepresentedObject *)arg2;
- (void)objectModel:(IBARepresentedObjectModel *)arg1 willRemoveRepresentedObject:(IBARepresentedObject *)arg2;
- (void)objectModel:(IBARepresentedObjectModel *)arg1 didAddRepresentedObject:(IBARepresentedObject *)arg2;
- (void)objectModel:(IBARepresentedObjectModel *)arg1 willAddRepresentedObject:(IBARepresentedObject *)arg2;
@end

