//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedAttribute, IBARepresentedObject;

@interface IBARepresentedAttributeValueChange : NSObject
{
    IBARepresentedAttribute *_attribute;
    IBARepresentedObject *_object;
    id _fromValue;
    id _toValue;
}

@property(copy) id toValue; // @synthesize toValue=_toValue;
@property(copy) id fromValue; // @synthesize fromValue=_fromValue;
@property(retain) IBARepresentedObject *object; // @synthesize object=_object;
@property(retain) IBARepresentedAttribute *attribute; // @synthesize attribute=_attribute;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqualToChange:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAttribute:(id)arg1 object:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4;

@end

