//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@interface IBARevealEnumerationInspectorViewModel : IBAInspectorViewModel
{
    // Error parsing type: , name: selectedCaseIndex
    // Error parsing type: , name: cases
}

+ (BOOL)canModelRepresentedType:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithRepresentedObject:(id)arg1;
- (id)initWithRepresentedAttribute:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

