//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBARevealDataModelJSONUpdateDeserializer : NSObject
{
    // Error parsing type: , name: wrapper
}

- (void).cxx_destruct;
- (id)init;
- (id)updatedDictionaryRepresentationForObjectModel:(id)arg1 dictionaryRepresentation:(id)arg2 error:(id *)arg3;
- (id)initWithUpdatesDictionary:(id)arg1;

@end

