//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSScriptObjectSpecifier, NSString;

@interface IBARevealDeviceInformation : NSObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: name
    // Error parsing type: , name: systemVersion
    // Error parsing type: , name: systemName
    // Error parsing type: , name: model
    // Error parsing type: , name: localizedModel
    // Error parsing type: , name: isSimulator
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *systemDisplayName;
@property(nonatomic, readonly) NSString *baseDisplayName;
@property(nonatomic, readonly) NSString *displayName;
@property(nonatomic, readonly) NSScriptObjectSpecifier *objectSpecifier;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqualToDeviceInformation:(id)arg1;
@property(nonatomic, readonly) NSString *description;
- (id)initWithIdentifier:(id)arg1 name:(id)arg2 systemVersion:(id)arg3 systemName:(id)arg4 model:(id)arg5 localizedModel:(id)arg6 isSimulator:(BOOL)arg7;
@property(nonatomic, readonly) BOOL simulator; // @synthesize simulator=isSimulator;
@property(nonatomic, readonly) NSString *localizedModel; // @synthesize localizedModel;
@property(nonatomic, readonly) NSString *model; // @synthesize model;
@property(nonatomic, readonly) NSString *systemName; // @synthesize systemName;
@property(nonatomic, readonly) NSString *systemVersion; // @synthesize systemVersion;
@property(nonatomic, readonly) NSString *name; // @synthesize name;
@property(nonatomic, readonly) NSString *identifier; // @synthesize identifier;

@end

