//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBARepresentedObjectImageStore : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: store
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)removeImageForIdentifier:(id)arg1 variation:(long long)arg2;
- (void)setError:(id)arg1 forIdentifier:(id)arg2 variation:(long long)arg3;
- (void)setImageWithData:(id)arg1 forIdentifier:(id)arg2 variation:(long long)arg3;
- (id)imageErrorForIdentifier:(id)arg1 variation:(long long)arg2;
- (id)imageForIdentifier:(id)arg1 variation:(long long)arg2;

@end

