//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSDocument.h>

@class IBADocumentWindowController, IBARevealDataModel, IBARevealDocumentLoader, IBARevealInspectableApplication, NSImage, NSNotificationCenter, NSNotificationQueue, NSProgress, NSString;

@interface IBARevealDocument : NSDocument
{
    NSNotificationCenter *_notificationCenter;
    NSNotificationQueue *_notificationQueue;
    BOOL _shouldSuppressServerAttributeChangeUpdates;
    IBARevealDataModel *_dataModel;
    NSImage *_applicationIcon;
    NSString *_applicationName;
    IBARevealDocumentLoader *_loader;
    unsigned long long _state;
    IBARevealInspectableApplication *_inspectableApplication;
    NSString *_cachedInspectableApplicationDisplayName;
}

+ (id)keyPathsForValuesAffectingApplicationDisplayName;
+ (id)keyPathsForValuesAffectingLoadedFromDisk;
+ (id)keyPathsForValuesAffectingRefreshing;
+ (id)keyPathsForValuesAffectingConnected;
+ (id)keyPathsForValuesAffectingEditable;
+ (id)keyPathsForValuesAffectingCanPerformRefresh;
+ (id)keyPathsForValuesAffectingApplicationLoaded;
+ (BOOL)representedObjectShouldRequestImage:(id)arg1;
+ (id)childNodeImageRequestsNeccessaryForChangeSet:(id)arg1 withViewHierarchy:(id)arg2;
+ (id)parentNodeImageRequestsNeccessaryForChangeSet:(id)arg1 withViewHierarchy:(id)arg2;
+ (id)imageRequestsNecessaryForChangeSet:(id)arg1 withViewHierarchy:(id)arg2;
+ (id)imageRequestsNecessaryForObjectModel:(id)arg1 withViewHierarchy:(id)arg2;
+ (id)nodesForRepresentedObjects:(id)arg1 inViewHierarchy:(id)arg2;
@property(retain, nonatomic) NSString *cachedInspectableApplicationDisplayName; // @synthesize cachedInspectableApplicationDisplayName=_cachedInspectableApplicationDisplayName;
@property(nonatomic) BOOL shouldSuppressServerAttributeChangeUpdates; // @synthesize shouldSuppressServerAttributeChangeUpdates=_shouldSuppressServerAttributeChangeUpdates;
@property(retain, nonatomic) IBARevealInspectableApplication *inspectableApplication; // @synthesize inspectableApplication=_inspectableApplication;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) IBARevealDocumentLoader *loader; // @synthesize loader=_loader;
@property(retain, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(retain, nonatomic) NSImage *applicationIcon; // @synthesize applicationIcon=_applicationIcon;
@property(retain, nonatomic) IBARevealDataModel *dataModel; // @synthesize dataModel=_dataModel;
- (void).cxx_destruct;
- (void)revealDataModel:(id)arg1 didObserveObjectModelChanges:(id)arg2;
- (void)revealDataModel:(id)arg1 didObserveViewHierarchyChanges:(id)arg2;
- (id)objectSpecifier;
@property(readonly, nonatomic) NSProgress *refreshProgress;
- (void)updateServerForAttributeValueChange:(id)arg1;
- (void)updateServerWithChangeSet:(id)arg1;
- (void)performWithSuppressingAttributeChangeServerUpdates:(CDUnknownBlockType)arg1;
- (void)didEndRefreshingApplicationStateSnapshotWithError:(id)arg1;
- (void)willBeginRefreshingApplicationStateSnapshot;
- (void)didResetDocument;
- (void)willResetDocument;
- (void)resetDocument;
- (void)refreshApplicationStateSnapshotWithCompletion:(CDUnknownBlockType)arg1;
- (void)enqueueNotificationWithName:(id)arg1 userInfo:(id)arg2;
@property(readonly, nonatomic) NSString *applicationDisplayName;
- (id)handleSaveScriptCommand:(id)arg1;
- (void)saveDocumentTo:(id)arg1;
- (void)saveDocumentAs:(id)arg1;
- (void)saveDocument:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)makeWindowControllers;
- (void)revealDocumentLoader:(id)arg1 didReceiveEdits:(id)arg2;
- (void)revealDocumentLoader:(id)arg1 didFailToReceiveImageWithError:(id)arg2 forRequest:(id)arg3;
- (void)revealDocumentLoader:(id)arg1 didReceiveImageData:(id)arg2 forRequest:(id)arg3;
- (void)revealDocumentLoader:(id)arg1 didFailRefreshingApplicationStateWithError:(id)arg2;
- (void)revealDocumentLoader:(id)arg1 didEndRefreshingApplicationState:(id)arg2;
- (void)revealDocumentLoaderDidCancelLoading:(id)arg1;
- (void)revealDocumentLoaderDidFinishLoading:(id)arg1;
- (void)revealDocumentLoaderDidBeginLoading:(id)arg1;
- (void)unregisterObserver:(id)arg1;
- (void)registerObserver:(id)arg1;
- (void)applicationIconStoreDidUpdateIconNotification:(id)arg1;
- (void)dealloc;
- (id)init;
- (BOOL)matchesApplication:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
@property(nonatomic, readonly) IBADocumentWindowController *mainWindowController;
- (BOOL)isDocumentEdited;
@property(readonly, nonatomic, getter=isLoadedFromDisk) BOOL loadedFromDisk;
@property(readonly, nonatomic, getter=isRefreshing) BOOL refreshing;
@property(readonly, nonatomic, getter=isConnected) BOOL connected;
@property(readonly, nonatomic, getter=isEditable) BOOL editable;
@property(readonly, nonatomic) BOOL canPerformRefresh;
@property(readonly, nonatomic, getter=isApplicationLoaded) BOOL applicationLoaded;
- (id)handleRefreshScriptCommand:(id)arg1;

@end

