//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedObjectIdentifier.h"

@class NSString;

@interface IBARepresentedObjectGroupIdentifier : IBARepresentedObjectIdentifier
{
    NSString *_kind;
}

@property(readonly, copy, nonatomic) NSString *kind; // @synthesize kind=_kind;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqualToGroupIdentifier:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)debugDescription;
@property(readonly, copy, nonatomic) IBARepresentedObjectIdentifier *containerIdentifer;
- (id)initWithContainerIdentifier:(id)arg1 kind:(id)arg2;

@end

