//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBARepresentedObject.h"

#import "IBAAbstractDevice-Protocol.h"

@class NSString, NSUUID;

@interface IBARepresentedDevice : IBARepresentedObject <IBAAbstractDevice>
{
}

@property(readonly, nonatomic) BOOL isSimulator;
@property(readonly, copy, nonatomic) NSUUID *identifierForVendor;
@property(readonly, nonatomic) long long userInterfaceIdiom;
@property(readonly, copy, nonatomic) NSString *localizedModel;
@property(readonly, copy, nonatomic) NSString *model;
@property(readonly, copy, nonatomic) NSString *systemVersion;
@property(readonly, copy, nonatomic) NSString *systemName;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSString *iba_identifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

