//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IBARepresentedObjectModel : NSObject
{
    // Error parsing type: , name: typeRegistry
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: delegate
    // Error parsing type: , name: identifierToObjectMap
    // Error parsing type: , name: valueChangeNotificationCenter
}

- (void).cxx_destruct;
- (void)removeAttributeChangeObserver:(id)arg1;
- (id)addAttributeChangeObserverForKeyPath:(id)arg1 object:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)representedObjectForIdentifier:(id)arg1;
- (id)init;
@property(nonatomic, readonly) NSArray *representedObjects;

@end

