//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IBARevealDataModelStaticData : NSObject
{
    // Error parsing type: , name: fontFamilies
    // Error parsing type: , name: locales
    // Error parsing type: , name: calendars
    // Error parsing type: , name: timeZones
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithFontFamilies:(id)arg1 locales:(id)arg2 calendars:(id)arg3 timeZones:(id)arg4;
@property(nonatomic, readonly) NSArray *timeZones; // @synthesize timeZones;
@property(nonatomic, readonly) NSArray *calendars; // @synthesize calendars;
@property(nonatomic, readonly) NSArray *locales; // @synthesize locales;
@property(nonatomic, readonly) NSArray *fontFamilies; // @synthesize fontFamilies;

@end

