//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPathCell.h>

@class NSAttributedString, NSString;

@interface IBARevealBorderlessPathCell : NSPathCell
{
}

+ (Class)pathComponentCellClass;
- (id)init;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)rectOfPathComponentCell:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
@property(nonatomic, retain) NSAttributedString *placeholderAttributedString;
@property(nonatomic, copy) NSString *placeholderString;
@property(nonatomic, retain) NSAttributedString *attributedStringValue;
@property(nonatomic, copy) NSString *stringValue;
- (void)prepareForInterfaceBuilder;
- (void)awakeFromNib;
- (id)initTextCell:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

