//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSplitViewController.h>

@class NSSplitViewItem;

@interface IBARevealContentSplitViewController : NSSplitViewController
{
    // Error parsing type: , name: outlineViewSplitItem
    // Error parsing type: , name: canvasViewSplitItem
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, retain) NSSplitViewItem *canvasViewSplitItem; // @synthesize canvasViewSplitItem;
@property(nonatomic, retain) NSSplitViewItem *outlineViewSplitItem; // @synthesize outlineViewSplitItem;

@end

