//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBASyntheticAttributesModel : NSObject
{
    // Error parsing type: , name: attributeChangePublisher
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: providerMapping
}

+ (id)makeWithCommonProvidersAndImageStore:(id)arg1 objectModel:(id)arg2;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)updateWithChangeSet:(id)arg1;
- (id)valueForAttributeWithKeyPath:(id)arg1 object:(id)arg2;
- (id)addObserver:(id)arg1;

@end

