//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "IBASimulatorApplicationLauncherDelegate-Protocol.h"

@class IBASimulatorApplicationLauncher, NSProgress, NSProgressIndicator, NSString, NSTextField;
@protocol IBASampleAppWindowControllerDelegate;

@interface IBASampleAppWindowController : NSWindowController <IBASimulatorApplicationLauncherDelegate>
{
    id <IBASampleAppWindowControllerDelegate> _sampleAppDelegate;
    NSTextField *_label;
    NSProgressIndicator *_progressIndicator;
    IBASimulatorApplicationLauncher *_launcher;
    NSProgress *_launchProgress;
}

+ (id)keyPathsForValuesAffectingSampleApplicationIsLaunching;
@property(retain, nonatomic) NSProgress *launchProgress; // @synthesize launchProgress=_launchProgress;
@property(retain, nonatomic) IBASimulatorApplicationLauncher *launcher; // @synthesize launcher=_launcher;
@property(nonatomic) __weak NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(nonatomic) __weak NSTextField *label; // @synthesize label=_label;
@property(nonatomic) __weak id <IBASampleAppWindowControllerDelegate> sampleAppDelegate; // @synthesize sampleAppDelegate=_sampleAppDelegate;
- (void).cxx_destruct;
- (void)invalidateLauncher;
- (void)notifyDelegateOfLaunchAndConnectSuccess:(BOOL)arg1;
- (void)dismissAndNotifyWithSuccess:(BOOL)arg1 error:(id)arg2;
- (void)connectDocumentToSampleAppWithDescription:(id)arg1;
- (void)didEndSheet:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)simulatorApplicationLauncher:(id)arg1 applicationWithDescription:(id)arg2 didStart:(BOOL)arg3 withError:(id)arg4;
- (void)inspectDemoProjectWithParentWindow:(id)arg1;
- (void)windowDidLoad;
@property(readonly, nonatomic) BOOL sampleApplicationIsLaunching;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

