//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewController.h"

@class NSTextField;

@interface IBAScreenModeInspectorViewController : IBAInspectorViewController
{
    NSTextField *_secondaryLabelTextField;
    NSTextField *_pixelAspectRatioField;
    NSTextField *_widthField;
    NSTextField *_heightField;
}

@property(retain, nonatomic) NSTextField *heightField; // @synthesize heightField=_heightField;
@property(retain, nonatomic) NSTextField *widthField; // @synthesize widthField=_widthField;
@property(retain, nonatomic) NSTextField *pixelAspectRatioField; // @synthesize pixelAspectRatioField=_pixelAspectRatioField;
@property(retain, nonatomic) NSTextField *secondaryLabelTextField; // @synthesize secondaryLabelTextField=_secondaryLabelTextField;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

