//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAInspectorViewModel.h"

@class NSNumber;

@interface IBAScreenModeInspectorViewModel : IBAInspectorViewModel
{
    NSNumber *_pixelAspectRatio;
    NSNumber *_width;
    NSNumber *_height;
}

+ (BOOL)canModelRepresentedType:(id)arg1;
+ (void)load;
@property(readonly, nonatomic) NSNumber *height; // @synthesize height=_height;
@property(readonly, nonatomic) NSNumber *width; // @synthesize width=_width;
@property(readonly, nonatomic) NSNumber *pixelAspectRatio; // @synthesize pixelAspectRatio=_pixelAspectRatio;
- (void).cxx_destruct;
- (id)initWithRepresentedObject:(id)arg1;
- (Class)representingInspectorViewControllerClass;

@end

