//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBASimulatorApplicationLauncher, IBASimulatorLaunchDescription, NSError;

@protocol IBASimulatorApplicationLauncherDelegate <NSObject>

@optional
- (void)simulatorApplicationLauncher:(IBASimulatorApplicationLauncher *)arg1 applicationWithDescription:(IBASimulatorLaunchDescription *)arg2 didStart:(BOOL)arg3 withError:(NSError *)arg4;
@end

