//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSArray, NSAttributedString;

@interface IBAStyledTextField : NSTextField
{
    // Error parsing type: , name: isEmphasized
    // Error parsing type: , name: isSelected
    // Error parsing type: , name: queryHighlightRanges
    // Error parsing type: , name: needsLabelUpdate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewDidChangeEffectiveAppearance;
- (void)layout;
@property(nonatomic, retain) NSAttributedString *attributedStringValue;
@property(nonatomic) BOOL highlighted;
- (BOOL)isHighlighted;
@property(nonatomic) BOOL enabled;
- (BOOL)isEnabled;
@property(nonatomic, copy) NSArray *queryHighlightRanges; // @synthesize queryHighlightRanges;
@property(nonatomic) BOOL isSelected; // @synthesize isSelected;
@property(nonatomic) BOOL isEmphasized; // @synthesize isEmphasized;

@end

