//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString, NSURL;

@interface IBASimulatorLaunchDescription : NSObject
{
    NSURL *_applicationBundleURL;
    NSString *_deviceTypeIdentifier;
    NSString *_minimumSDKVersion;
    NSDictionary *_environment;
    NSArray *_arguments;
}

+ (id)sampleApplicationSimulatorLaunchDescriptionWithError:(id *)arg1;
@property(readonly, nonatomic) NSArray *arguments; // @synthesize arguments=_arguments;
@property(readonly, nonatomic) NSDictionary *environment; // @synthesize environment=_environment;
@property(readonly, nonatomic) NSString *minimumSDKVersion; // @synthesize minimumSDKVersion=_minimumSDKVersion;
@property(readonly, nonatomic) NSString *deviceTypeIdentifier; // @synthesize deviceTypeIdentifier=_deviceTypeIdentifier;
@property(readonly, nonatomic) NSURL *applicationBundleURL; // @synthesize applicationBundleURL=_applicationBundleURL;
- (void).cxx_destruct;
- (id)initWithApplicationBundleURL:(id)arg1 minimumSDKVersion:(id)arg2 deviceTypeIdentifier:(id)arg3 arguments:(id)arg4 environment:(id)arg5;

@end

