//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSEvent, NSSegmentedControl;

@protocol IBASegmentedControlHoverDelegate

@optional
- (void)hoverableSegmentedControl:(NSSegmentedControl *)arg1 mouseDidExitAtSegment:(long long)arg2 withEvent:(NSEvent *)arg3;
- (void)hoverableSegmentedControl:(NSSegmentedControl *)arg1 mouseDidMoveToSegment:(long long)arg2 withEvent:(NSEvent *)arg3;
- (void)hoverableSegmentedControl:(NSSegmentedControl *)arg1 mouseDidEnterAtSegment:(long long)arg2 withEvent:(NSEvent *)arg3;
@end

