//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBAGCDAsyncSocketDelegate-Protocol.h"
#import "IBAUSBServiceRelaySocketProvider-Protocol.h"

@class IBAAMDevice, IBAGCDAsyncSocket, IBAUSBService, IBAUSBServiceAdvertisementDecoder, IBAUSBServiceRelay, NSString;
@protocol IBAUSBAdvertiserConnectionDelegate;

@interface IBAUSBAdvertiserConnection : NSObject <IBAUSBServiceRelaySocketProvider, IBAGCDAsyncSocketDelegate>
{
    IBAAMDevice *_device;
    unsigned long long _advertiserPort;
    IBAUSBService *_resolvedService;
    IBAUSBService *_relayedService;
    id <IBAUSBAdvertiserConnectionDelegate> _delegate;
    IBAGCDAsyncSocket *_advertiserSocket;
    IBAUSBServiceRelay *_relay;
    IBAUSBServiceAdvertisementDecoder *_advertisementDecoder;
}

@property(retain, nonatomic) IBAUSBServiceAdvertisementDecoder *advertisementDecoder; // @synthesize advertisementDecoder=_advertisementDecoder;
@property(retain, nonatomic) IBAUSBServiceRelay *relay; // @synthesize relay=_relay;
@property(readonly, nonatomic) IBAGCDAsyncSocket *advertiserSocket; // @synthesize advertiserSocket=_advertiserSocket;
@property(nonatomic) __weak id <IBAUSBAdvertiserConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IBAUSBService *relayedService; // @synthesize relayedService=_relayedService;
@property(retain, nonatomic) IBAUSBService *resolvedService; // @synthesize resolvedService=_resolvedService;
@property(readonly, nonatomic) unsigned long long advertiserPort; // @synthesize advertiserPort=_advertiserPort;
@property(readonly, nonatomic) IBAAMDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (int)serviceRelaySocketForOutgoingConnection:(id)arg1;
- (void)startServiceRelay;
- (void)didFinishReadingAdvertisement;
- (void)resolveService;
- (id)initWithDevice:(id)arg1 advertiserSocketHandle:(int)arg2 port:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

