//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBAMobileDeviceAccessListener-Protocol.h"
#import "IBAUSBDeviceDelegate-Protocol.h"

@class IBAMobileDeviceAccess, NSMutableArray, NSString;
@protocol IBAUSBServiceBrowserDelegate;

@interface IBAUSBServiceBrowser : NSObject <IBAMobileDeviceAccessListener, IBAUSBDeviceDelegate>
{
    id <IBAUSBServiceBrowserDelegate> _delegate;
    IBAMobileDeviceAccess *_mobileDeviceAccess;
    NSMutableArray *_devices;
}

@property(readonly, nonatomic) NSMutableArray *devices; // @synthesize devices=_devices;
@property(readonly, nonatomic) IBAMobileDeviceAccess *mobileDeviceAccess; // @synthesize mobileDeviceAccess=_mobileDeviceAccess;
@property(nonatomic) __weak id <IBAUSBServiceBrowserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)device:(id)arg1 didRemoveService:(id)arg2;
- (void)device:(id)arg1 didFindService:(id)arg2;
- (void)mobileDeviceAccess:(id)arg1 didDisconnectDevice:(id)arg2;
- (void)mobileDeviceAccess:(id)arg1 didConnectDevice:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

