//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBAUSBDevice, IBAUSBService;

@protocol IBAUSBDeviceDelegate <NSObject>
- (void)device:(IBAUSBDevice *)arg1 didRemoveService:(IBAUSBService *)arg2;
- (void)device:(IBAUSBDevice *)arg1 didFindService:(IBAUSBService *)arg2;
@end

