//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IBAUSBAdvertiserConnectionDelegate-Protocol.h"

@class IBAAMDevice, IBAAMNotificationProxy, NSMutableArray, NSString;
@protocol IBAUSBDeviceDelegate;

@interface IBAUSBDevice : NSObject <IBAUSBAdvertiserConnectionDelegate>
{
    IBAAMDevice *_device;
    id <IBAUSBDeviceDelegate> _delegate;
    IBAAMNotificationProxy *_notificationProxy;
    NSMutableArray *_advertiserConnections;
}

@property(readonly, nonatomic) NSMutableArray *advertiserConnections; // @synthesize advertiserConnections=_advertiserConnections;
@property(readonly, nonatomic) IBAAMNotificationProxy *notificationProxy; // @synthesize notificationProxy=_notificationProxy;
@property(nonatomic) __weak id <IBAUSBDeviceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IBAAMDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)advertiserConnectionDidClose:(id)arg1;
- (void)advertiserConnection:(id)arg1 didFailServiceResolutionWithError:(id)arg2;
- (void)advertiserConnection:(id)arg1 didResolveAndRelayService:(id)arg2;
- (void)removeServiceConnection:(id)arg1;
- (void)rescanAdvertisers;
- (void)handleServiceStartedNotification:(id)arg1;
- (void)deviceDidDisconnect;
- (id)initWithDevice:(id)arg1 delegate:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

