//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface IBAUSBService : NSObject
{
    NSString *_name;
    unsigned long long _port;
    NSData *_payload;
}

+ (id)objectWithJSONPayload:(id)arg1;
+ (id)dictionaryWithTXTRecordPayload:(id)arg1;
+ (id)payloadWithJSONObject:(id)arg1;
+ (id)payloadWithTXTRecordDictionary:(id)arg1;
@property(readonly, copy, nonatomic) NSData *payload; // @synthesize payload=_payload;
@property(readonly, nonatomic) unsigned long long port; // @synthesize port=_port;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)serviceWithPort:(unsigned long long)arg1;
- (id)initWithName:(id)arg1 port:(unsigned long long)arg2 payload:(id)arg3;

@end

