//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBAUSBAdvertiserConnection, IBAUSBService, NSError;

@protocol IBAUSBAdvertiserConnectionDelegate <NSObject>
- (void)advertiserConnectionDidClose:(IBAUSBAdvertiserConnection *)arg1;
- (void)advertiserConnection:(IBAUSBAdvertiserConnection *)arg1 didFailServiceResolutionWithError:(NSError *)arg2;
- (void)advertiserConnection:(IBAUSBAdvertiserConnection *)arg1 didResolveAndRelayService:(IBAUSBService *)arg2;
@end

