//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBAUSBService, NSData, NSMutableData, NSString;

@interface IBAUSBServiceAdvertisementDecoder : NSObject
{
    BOOL _isInvalid;
    NSMutableData *_accumulator;
    unsigned long long _currentChunk;
    unsigned long long _chunkStartPosition;
    unsigned long long _serviceNameLength;
    NSString *_serviceName;
    unsigned long long _servicePort;
    unsigned long long _payloadLength;
    NSData *_payload;
}

@property(copy, nonatomic) NSData *payload; // @synthesize payload=_payload;
@property(nonatomic) unsigned long long payloadLength; // @synthesize payloadLength=_payloadLength;
@property(nonatomic) unsigned long long servicePort; // @synthesize servicePort=_servicePort;
@property(copy, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(nonatomic) unsigned long long serviceNameLength; // @synthesize serviceNameLength=_serviceNameLength;
@property(nonatomic) unsigned long long chunkStartPosition; // @synthesize chunkStartPosition=_chunkStartPosition;
@property(nonatomic) unsigned long long currentChunk; // @synthesize currentChunk=_currentChunk;
@property(readonly, nonatomic) NSMutableData *accumulator; // @synthesize accumulator=_accumulator;
@property(nonatomic) BOOL isInvalid; // @synthesize isInvalid=_isInvalid;
- (void).cxx_destruct;
- (void)appendChunkData:(id)arg1;
- (unsigned long long)lengthForChunk:(unsigned long long)arg1;
- (unsigned long long)nextChunkLength;
@property(readonly, copy, nonatomic) IBAUSBService *service;
@property(readonly, nonatomic) BOOL isFinished;
- (id)init;

@end

