//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAViewHierarchyCanvasStateMemento : NSObject
{
    double _zoomFactor;
    double _rotationAngleInRadians;
    struct SCNVector3 _panPosition;
}

@property(readonly) double rotationAngleInRadians; // @synthesize rotationAngleInRadians=_rotationAngleInRadians;
@property(readonly) struct SCNVector3 panPosition; // @synthesize panPosition=_panPosition;
@property(readonly) double zoomFactor; // @synthesize zoomFactor=_zoomFactor;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithZoomFactor:(double)arg1 panPosition:(struct SCNVector3)arg2 rotationAngleInRadians:(double)arg3;
- (id)init;

@end

