//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAOutlineView.h"

@class IBAViewHoverAspect;
@protocol IBAViewHierarchyOutlineViewDelegate;

@interface IBAViewHierarchyOutlineView : IBAOutlineView
{
    id <IBAViewHierarchyOutlineViewDelegate> _viewHierarchyOutlineDelegate;
    IBAViewHoverAspect *_hoverAspect;
    long long _highlightedRow;
}

@property long long highlightedRow; // @synthesize highlightedRow=_highlightedRow;
@property(retain, nonatomic) IBAViewHoverAspect *hoverAspect; // @synthesize hoverAspect=_hoverAspect;
@property(nonatomic) __weak id <IBAViewHierarchyOutlineViewDelegate> viewHierarchyOutlineDelegate; // @synthesize viewHierarchyOutlineDelegate=_viewHierarchyOutlineDelegate;
- (void).cxx_destruct;
- (void)hoverableView:(id)arg1 mouseDidExitWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidMoveWithEvent:(id)arg2;
- (void)hoverableView:(id)arg1 mouseDidEnterWithEvent:(id)arg2;
- (void)updateRowView:(id)arg1 expandedStateForItem:(id)arg2;
- (void)updateRowViewExpandedStateForItem:(id)arg1;
- (void)collapseItem:(id)arg1 collapseChildren:(BOOL)arg2;
- (void)expandItem:(id)arg1 expandChildren:(BOOL)arg2;
- (void)reloadData;
- (void)didHighlightRow:(long long)arg1;
- (void)unhighlightRow;
- (void)highlightRow:(long long)arg1;
- (void)highlightRowIfNeeded:(long long)arg1;
- (void)highlightRowIfNeededForEvent:(id)arg1;
- (long long)rowAtLocationInWindow:(struct CGPoint)arg1;
- (void)updateHoverAspect;
- (void)didAddRowView:(id)arg1 forRow:(long long)arg2;
- (id)makeViewWithIdentifier:(id)arg1 owner:(id)arg2;
- (void)viewDidMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

