//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPointerArray;

@interface IBAViewHierarchyNodeAssociatedCanvasTreeItemsStorage : NSObject
{
    NSPointerArray *_canvasTreeItems;
}

@property(readonly, nonatomic) NSPointerArray *canvasTreeItems; // @synthesize canvasTreeItems=_canvasTreeItems;
- (void).cxx_destruct;
- (id)init;

@end

