//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSEvent, NSView;

@protocol IBAViewHoverDelegate

@optional
- (void)hoverableView:(NSView *)arg1 mouseDidExitWithEvent:(NSEvent *)arg2;
- (void)hoverableView:(NSView *)arg1 mouseDidMoveWithEvent:(NSEvent *)arg2;
- (void)hoverableView:(NSView *)arg1 mouseDidEnterWithEvent:(NSEvent *)arg2;
@end

