//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reveal32ViewHierarchyOutlineBaseCellView.h"

@class NSTextField;

@interface IBAViewHierarchyOutlineCellView : _TtC6Reveal32ViewHierarchyOutlineBaseCellView
{
    // Error parsing type: , name: textFieldObservationTokens
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
@property(nonatomic, retain) NSTextField *textField;

@end

