//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAViewHierarchyLayoutIssuesTree : NSObject
{
    // Error parsing type: , name: viewHierarchy
    // Error parsing type: , name: sparseTree
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)identifiersAffectedByProcessingChangeSet:(id)arg1;
- (id)initWithViewHierarchy:(id)arg1;
- (id)makeIssueAdaptorForIdentifier:(id)arg1 withPresentationStateController:(id)arg2;

@end

