//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBAExclusionControllerObservationProxy, IBAExpansionControllerObservationProxy, IBAFilteringControllerObservationProxy, IBAFocusControllerObservationProxy, IBAHighlightControllerObservationProxy, IBAOutlineViewModelBatchingProxy, IBAPresentationStateController, IBASelectionControllerObservationProxy, IBAViewHierarchy, IBAViewHierarchyLayoutIssuesTree, IBAViewHierarchyNodesToOutlineViewTreeItemsAdaptor, IBAViewHierarchyOutlineViewNavigator, NSArray;
@protocol IBAViewHierarchyOutlineViewModelDelegate;

@interface IBAViewHierarchyOutlineViewModel : NSObject
{
    IBAViewHierarchy *_viewHierarchy;
    IBAPresentationStateController *_presentationStateController;
    NSArray *_rootItems;
    IBAViewHierarchyOutlineViewNavigator *_navigator;
    id <IBAViewHierarchyOutlineViewModelDelegate> _delegate;
    IBAOutlineViewModelBatchingProxy *_batchingProxy;
    IBAViewHierarchyNodesToOutlineViewTreeItemsAdaptor *_nodesToTreeItemsAdaptor;
    IBAExclusionControllerObservationProxy *_exclusionObservationProxy;
    IBAExpansionControllerObservationProxy *_expansionObservationProxy;
    IBAFilteringControllerObservationProxy *_filteringObservationProxy;
    IBAFocusControllerObservationProxy *_focusObservationProxy;
    IBAHighlightControllerObservationProxy *_highlightObservationProxy;
    IBASelectionControllerObservationProxy *_selectionObservationProxy;
    NSArray *_rootIdentifiers;
    NSArray *_selectedItems;
    IBAViewHierarchyLayoutIssuesTree *_layoutIssuesTree;
}

@property(retain, nonatomic) IBAViewHierarchyLayoutIssuesTree *layoutIssuesTree; // @synthesize layoutIssuesTree=_layoutIssuesTree;
@property(copy, nonatomic) NSArray *selectedItems; // @synthesize selectedItems=_selectedItems;
@property(copy, nonatomic) NSArray *rootIdentifiers; // @synthesize rootIdentifiers=_rootIdentifiers;
@property(retain, nonatomic) IBASelectionControllerObservationProxy *selectionObservationProxy; // @synthesize selectionObservationProxy=_selectionObservationProxy;
@property(retain, nonatomic) IBAHighlightControllerObservationProxy *highlightObservationProxy; // @synthesize highlightObservationProxy=_highlightObservationProxy;
@property(retain, nonatomic) IBAFocusControllerObservationProxy *focusObservationProxy; // @synthesize focusObservationProxy=_focusObservationProxy;
@property(retain, nonatomic) IBAFilteringControllerObservationProxy *filteringObservationProxy; // @synthesize filteringObservationProxy=_filteringObservationProxy;
@property(retain, nonatomic) IBAExpansionControllerObservationProxy *expansionObservationProxy; // @synthesize expansionObservationProxy=_expansionObservationProxy;
@property(retain, nonatomic) IBAExclusionControllerObservationProxy *exclusionObservationProxy; // @synthesize exclusionObservationProxy=_exclusionObservationProxy;
@property(readonly, nonatomic) IBAViewHierarchyNodesToOutlineViewTreeItemsAdaptor *nodesToTreeItemsAdaptor; // @synthesize nodesToTreeItemsAdaptor=_nodesToTreeItemsAdaptor;
@property(readonly, nonatomic) IBAOutlineViewModelBatchingProxy *batchingProxy; // @synthesize batchingProxy=_batchingProxy;
@property(nonatomic) __weak id <IBAViewHierarchyOutlineViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IBAViewHierarchyOutlineViewNavigator *navigator; // @synthesize navigator=_navigator;
@property(copy, nonatomic) NSArray *rootItems; // @synthesize rootItems=_rootItems;
@property(retain, nonatomic) IBAPresentationStateController *presentationStateController; // @synthesize presentationStateController=_presentationStateController;
@property(retain, nonatomic) IBAViewHierarchy *viewHierarchy; // @synthesize viewHierarchy=_viewHierarchy;
- (void).cxx_destruct;
- (void)expansionController:(id)arg1 didChangeExpansionStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)highlightController:(id)arg1 didChangeHighlightStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)selectionController:(id)arg1 didChangeSelectionStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)focusController:(id)arg1 didChangeFocusedNode:(id)arg2;
- (void)filteringController:(id)arg1 didChangeFilteredStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)filteringController:(id)arg1 didChangeFilteringState:(BOOL)arg2;
- (void)exclusionController:(id)arg1 didChangeIgnoredStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)exclusionController:(id)arg1 didChangeDisabledStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (void)exclusionController:(id)arg1 didChangeHiddenStateOfIdentifiers:(id)arg2 toValue:(BOOL)arg3;
- (id)queryStringForNodeWithIdentifier:(id)arg1;
- (BOOL)shouldIncludeNodeWithIdentifier:(id)arg1;
- (BOOL)shouldEmphasizeNodeWithIdentifier:(id)arg1;
- (BOOL)shouldEnableNodeWithIdentifier:(id)arg1;
- (void)reloadContents;
- (void)endBatchingUpdates;
- (void)beginBatchingUpdates;
- (void)collapseItemsWithIdentifiers:(id)arg1;
- (void)expandItemsWithIdentifiers:(id)arg1;
- (void)reloadFocus;
- (void)reloadHighlight;
- (void)reloadSelection;
- (void)reloadDataAfterChangingRootIdentifiers:(BOOL)arg1;
- (void)reloadData;
- (void)updateTreeItem:(id)arg1 updateChildren:(BOOL)arg2;
- (void)updateTreeItemsForIdentifiers:(id)arg1;
- (void)updateTreeItemForIdentifier:(id)arg1 reloadChildren:(BOOL)arg2;
- (void)updateAllTreeItems;
- (id)transformViewHierarchyNodesToTreeItems:(id)arg1;
@property(readonly, nonatomic) BOOL isFiltered;
- (void)updateWithViewHierarchyChange:(id)arg1;
- (id)init;
- (void)setViewHierarchy:(id)arg1 presentationStateController:(id)arg2;
- (id)flattenedTreeItems;
- (id)outlineViewTreeItemsForIdentifiers:(id)arg1;

@end

