//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IBAOutlineViewTreeItem, IBAViewHierarchyOutlineViewModel, NSArray;

@protocol IBAViewHierarchyOutlineViewModelDelegate <NSObject>

@optional
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didUpdateContentForItem:(IBAOutlineViewTreeItem *)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didFilterContents:(BOOL)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 willFilterContents:(BOOL)arg2;
- (BOOL)shouldSuppressExpansionNotificationsFromViewModel:(IBAViewHierarchyOutlineViewModel *)arg1;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didCollapseItem:(IBAOutlineViewTreeItem *)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didExpandItem:(IBAOutlineViewTreeItem *)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didHighlightItems:(NSArray *)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didSelectItems:(NSArray *)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 didReloadContentsChangingRootItems:(BOOL)arg2;
- (void)viewModel:(IBAViewHierarchyOutlineViewModel *)arg1 willReloadContentsChangingRootItems:(BOOL)arg2;
@end

