//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IBAViewController.h"

#import "IBACanvasSceneViewDelegate-Protocol.h"
#import "IBACanvasTreeAdapterDataSource-Protocol.h"

@class IBACanvasBitmapErrorPresenter, IBACanvasBottomBarView, IBACanvasSceneView, IBACanvasToastBoard, IBACanvasToastsController, IBACanvasTopBarView, IBACanvasTreeAdapter, IBAFocusControllerObservationProxy, IBAGradientView, IBAPresentationStateController, NSString, NSView;

@interface IBAViewHierarchyCanvasViewController : IBAViewController <IBACanvasTreeAdapterDataSource, IBACanvasSceneViewDelegate>
{
    IBAPresentationStateController *_presentationStateController;
    double _hiddenItemOpacity;
    IBAFocusControllerObservationProxy *_focusObservationProxy;
    NSView *_containerView;
    IBAGradientView *_backgroundView;
    IBACanvasSceneView *_canvasSceneView;
    IBACanvasToastBoard *_canvasToastBoard;
    IBACanvasTopBarView *_canvasToolbar;
    IBACanvasBottomBarView *_canvasBottomToolbar;
    IBACanvasToastsController *_toastsController;
    IBACanvasBitmapErrorPresenter *_bitmapErrorPresenter;
    long long _renderMode;
    long long _perspective;
    IBACanvasTreeAdapter *_canvasTreeAdapter;
}

+ (BOOL)shouldForceOpenGLWithUserDefaultsManager:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversOfHiddenItemOpacity;
+ (id)keyPathsForValuesAffectingZoomFactor;
+ (BOOL)automaticallyNotifiesObserversOfZoomFactor;
+ (id)zoomLevels;
@property(retain, nonatomic) IBACanvasTreeAdapter *canvasTreeAdapter; // @synthesize canvasTreeAdapter=_canvasTreeAdapter;
@property(nonatomic) long long perspective; // @synthesize perspective=_perspective;
@property(nonatomic) long long renderMode; // @synthesize renderMode=_renderMode;
@property(retain) IBACanvasBitmapErrorPresenter *bitmapErrorPresenter; // @synthesize bitmapErrorPresenter=_bitmapErrorPresenter;
@property(retain) IBACanvasToastsController *toastsController; // @synthesize toastsController=_toastsController;
@property(retain) IBACanvasBottomBarView *canvasBottomToolbar; // @synthesize canvasBottomToolbar=_canvasBottomToolbar;
@property(retain) IBACanvasTopBarView *canvasToolbar; // @synthesize canvasToolbar=_canvasToolbar;
@property(retain) IBACanvasToastBoard *canvasToastBoard; // @synthesize canvasToastBoard=_canvasToastBoard;
@property(retain) IBACanvasSceneView *canvasSceneView; // @synthesize canvasSceneView=_canvasSceneView;
@property(retain) IBAGradientView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) IBAFocusControllerObservationProxy *focusObservationProxy; // @synthesize focusObservationProxy=_focusObservationProxy;
@property(nonatomic) double hiddenItemOpacity; // @synthesize hiddenItemOpacity=_hiddenItemOpacity;
@property(retain, nonatomic) IBAPresentationStateController *presentationStateController; // @synthesize presentationStateController=_presentationStateController;
- (void).cxx_destruct;
- (void)replaceSceneViewWithForcedOpenGLRenderer;
- (void)focusController:(id)arg1 didChangeFocusedNode:(id)arg2;
- (void)canvasSceneView:(id)arg1 didToggleStatistics:(BOOL)arg2;
- (void)canvasSceneView:(id)arg1 didChangeZoomFactor:(double)arg2 animated:(BOOL)arg3;
- (void)canvasSceneView:(id)arg1 toggleTreeItemExpansion:(id)arg2 includeChildren:(BOOL)arg3;
- (void)canvasSceneView:(id)arg1 didFocusTreeItem:(id)arg2;
- (void)canvasSceneView:(id)arg1 didSelectTreeItem:(id)arg2;
- (void)canvasSceneView:(id)arg1 didMouseOverTreeItem:(id)arg2;
- (struct CGRect)canvasSceneView:(id)arg1 mouseTrackingRectForVisibleRect:(struct CGRect)arg2;
- (id)viewHierarchyNodeForTreeItem:(id)arg1;
- (id)viewHierarchyNodeForIdentifier:(id)arg1;
- (void)setHiddenItemOpacity:(double)arg1 animated:(BOOL)arg2;
- (void)updateCanvasNodesDisplayAnimated:(BOOL)arg1;
- (void)updateCanvasForViewHierarchyChange:(id)arg1;
- (void)resetCanvasStateAnimated:(BOOL)arg1;
- (void)resetCanvasState;
- (void)restoreCanvasState:(id)arg1 animated:(BOOL)arg2;
- (void)restoreCanvasState:(id)arg1;
- (id)saveCanvasState;
- (void)exportSceneToURL:(id)arg1;
- (void)applyCanvasBackgroundWithTheme:(id)arg1;
- (void)configureCanvasTheme:(id)arg1;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)refreshSelectedDocumentWithPresentationStateController:(id)arg1 restoreState:(id)arg2;
- (id)canvasBitmapErrorPresenter:(id)arg1 bitmapErrorFor:(id)arg2;
- (double)currentZoomFactorForCanvasToastsController:(id)arg1;
- (BOOL)canvasToastsController:(id)arg1 isContentOptionEnabled:(long long)arg2;
- (unsigned long long)canvasTreeAdapter:(id)arg1 bitmapStateForImage:(id)arg2;
- (id)canvasTreeAdapter:(id)arg1 imageWithoutSubviewsForIdentifier:(id)arg2 error:(id *)arg3;
- (id)canvasTreeAdapter:(id)arg1 imageForIdentifier:(id)arg2 error:(id *)arg3;
- (void)rotateCanvasViewToAngleInRadians:(double)arg1 animated:(BOOL)arg2;
- (void)focusViewHierarchyNode:(id)arg1 animated:(BOOL)arg2;
- (void)panCanvasToPosition:(struct SCNVector3)arg1 animated:(BOOL)arg2;
- (void)selectRenderModeAction:(id)arg1;
- (void)selectPerspectiveAction:(id)arg1;
- (void)setDisplayExcludedItemsControlOn:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL displayExcludedItemsControlOn;
- (void)setDisplayHiddenItemsControlOn:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL displayHiddenItemsControlOn;
- (void)setDisplayAutoLayoutControlOn:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL displayAutoLayoutControlOn;
- (void)setDisplaySmartMeasurements:(BOOL)arg1;
- (void)configureForPerspective:(long long)arg1 animated:(BOOL)arg2;
- (void)configureForRenderMode:(long long)arg1 animated:(BOOL)arg2;
- (double)previousClosestZoomLevelForZoomFactor:(double)arg1;
- (double)nextClosestZoomLevelForZoomFactor:(double)arg1;
- (void)zoomIn:(id)arg1;
- (void)zoomOut:(id)arg1;
- (void)zoomCanvasViewToFactor:(double)arg1 animated:(BOOL)arg2;
- (void)zoomToFitFocusedNodeProjectedAtFrontAnimated:(BOOL)arg1;
- (void)zoomToFitScreenAnimated:(BOOL)arg1;
- (void)zoomToFitSceneAnimated:(BOOL)arg1;
- (void)zoomToFitSelectedAnimated:(BOOL)arg1;
- (void)zoomToActualSizeAnimated:(BOOL)arg1;
- (void)zoomOutAnimated:(BOOL)arg1;
- (void)zoomInAnimated:(BOOL)arg1;
@property(nonatomic) double zoomFactor;
- (void)decreaseZDepthAnimated:(BOOL)arg1;
- (void)increaseZDepthAnimated:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

