//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBAViewHoverAspect : NSObject
{
    // Error parsing type: , name: owner
    // Error parsing type: , name: trackingOptions
    // Error parsing type: , name: delegate
    // Error parsing type: , name: trackingArea
    // Error parsing type: , name: state
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)invalidateHovering:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
@property(nonatomic, readonly) BOOL hovering;
- (void)updateTrackingArea;
- (id)initWithOwner:(id)arg1 style:(long long)arg2 delegate:(id)arg3;

@end

