//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBARepresentedObjectGroupIdentifier, IBAViewHierarchyNode, NSArray;

@interface IBAViewHierarchyNodeGroup : NSObject
{
    // Error parsing type: , name: containerNode
    // Error parsing type: , name: groupIdentifier
    // Error parsing type: , name: nodes
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSArray *nodes; // @synthesize nodes;
@property(nonatomic, readonly) IBARepresentedObjectGroupIdentifier *groupIdentifier; // @synthesize groupIdentifier;
@property(nonatomic, readonly) IBAViewHierarchyNode *containerNode; // @synthesize containerNode;

@end

