//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"

@class NSTableColumn, NSTextField, _TtC6Reveal24ViewHierarchyOutlineView;
@protocol IBAViewHierarchyOutlineViewControllerDelegate;

@interface IBAViewHierarchyOutlineViewController : NSViewController <NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: outlineView
    // Error parsing type: , name: viewModel.storage
    // Error parsing type: , name: presentationStateController
    // Error parsing type: , name: templateCellViews
    // Error parsing type: , name: expansionUpdatesSuppressionCount
    // Error parsing type: , name: outlineColumn
    // Error parsing type: , name: noFilterResultsTextField
    // Error parsing type: , name: batchedIdentifiersToExpand
    // Error parsing type: , name: batchedIdentifiersToCollapse
    // Error parsing type: , name: suggestedCellWidths
    // Error parsing type: , name: cellFittingWidthCache
    // Error parsing type: , name: floatingViewsTrailingOffset
    // Error parsing type: , name: stateMementoPendingReload
    // Error parsing type: , name: preFilterStateMemento
    // Error parsing type: , name: notificationTokens
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, retain) NSTextField *noFilterResultsTextField; // @synthesize noFilterResultsTextField;
@property(nonatomic, retain) NSTableColumn *outlineColumn; // @synthesize outlineColumn;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic, retain) _TtC6Reveal24ViewHierarchyOutlineView *outlineView; // @synthesize outlineView;
@property(nonatomic) __weak id <IBAViewHierarchyOutlineViewControllerDelegate> delegate; // @synthesize delegate;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (void)invalidateSuggestedWidthForAllItems;
- (void)invalidateSuggestedWidthForItem:(id)arg1;
- (double)estimatedWidthOfContentColumnInOutlineView:(id)arg1 withRootItems:(id)arg2;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (void)outlineView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)setNeedsRefreshAfterOutlineViewDidReloadData:(id)arg1;
- (void)setNeedsColumnWidthResetForOutlineView:(id)arg1 deferred:(BOOL)arg2;
- (void)unregisterForNotifications:(id)arg1;
- (void)registerForNotificationsForOutlineView:(id)arg1;
- (void)selectItemWithLayoutIssue:(id)arg1;
- (void)focusOnTreeItem:(id)arg1;

@end

