//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSOneCollectorChannelDelegate, NSMutableArray, NSNumber, NSString, NSUUID;
@protocol MSChannelGroupProtocol, MSChannelUnitProtocol;

@interface MSAppCenter : NSObject
{
    BOOL _sdkConfigured;
    BOOL _configuredFromApplication;
    BOOL _enabledStateUpdating;
    BOOL _setMaxStorageSizeHasBeenCalled;
    NSUUID *_installId;
    NSString *_logUrl;
    id <MSChannelUnitProtocol> _channelUnit;
    MSOneCollectorChannelDelegate *_oneCollectorChannelDelegate;
    id <MSChannelGroupProtocol> _channelGroup;
    NSMutableArray *_services;
    NSMutableArray *_startedServiceNames;
    NSString *_appSecret;
    NSString *_defaultTransmissionTargetToken;
    NSNumber *_requestedMaxStorageSizeInBytes;
    CDUnknownBlockType _maxStorageSizeCompletionHandler;
}

+ (void)resetSharedInstance;
+ (void)setCountryCode:(id)arg1;
+ (void)setUserId:(id)arg1;
+ (void)setMaxStorageSize:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)groupId;
+ (id)logTag;
+ (id)sdkVersion;
+ (BOOL)isDebuggerAttached;
+ (void)setCustomProperties:(id)arg1;
+ (void)setWrapperSdk:(id)arg1;
+ (void)setLogHandler:(CDUnknownBlockType)arg1;
+ (void)setLogLevel:(unsigned long long)arg1;
+ (unsigned long long)logLevel;
+ (id)installId;
+ (BOOL)isAppDelegateForwarderEnabled;
+ (BOOL)isEnabled;
+ (void)setEnabled:(BOOL)arg1;
+ (void)setLogUrl:(id)arg1;
+ (BOOL)isConfigured;
+ (void)startFromLibraryWithServices:(id)arg1;
+ (void)startService:(Class)arg1;
+ (void)startWithServices:(id)arg1;
+ (void)start:(id)arg1 withServices:(id)arg2;
+ (void)configure;
+ (void)configureWithAppSecret:(id)arg1;
+ (id)sharedInstance;
@property BOOL setMaxStorageSizeHasBeenCalled; // @synthesize setMaxStorageSizeHasBeenCalled=_setMaxStorageSizeHasBeenCalled;
@property(copy, nonatomic) CDUnknownBlockType maxStorageSizeCompletionHandler; // @synthesize maxStorageSizeCompletionHandler=_maxStorageSizeCompletionHandler;
@property BOOL enabledStateUpdating; // @synthesize enabledStateUpdating=_enabledStateUpdating;
@property BOOL configuredFromApplication; // @synthesize configuredFromApplication=_configuredFromApplication;
@property BOOL sdkConfigured; // @synthesize sdkConfigured=_sdkConfigured;
@property(retain, nonatomic) NSNumber *requestedMaxStorageSizeInBytes; // @synthesize requestedMaxStorageSizeInBytes=_requestedMaxStorageSizeInBytes;
@property(copy, nonatomic) NSString *defaultTransmissionTargetToken; // @synthesize defaultTransmissionTargetToken=_defaultTransmissionTargetToken;
@property(copy, nonatomic) NSString *appSecret; // @synthesize appSecret=_appSecret;
@property(retain, nonatomic) NSMutableArray *startedServiceNames; // @synthesize startedServiceNames=_startedServiceNames;
@property(retain, nonatomic) NSMutableArray *services; // @synthesize services=_services;
@property(retain, nonatomic) id <MSChannelGroupProtocol> channelGroup; // @synthesize channelGroup=_channelGroup;
@property(retain, nonatomic) MSOneCollectorChannelDelegate *oneCollectorChannelDelegate; // @synthesize oneCollectorChannelDelegate=_oneCollectorChannelDelegate;
@property(retain, nonatomic) id <MSChannelUnitProtocol> channelUnit; // @synthesize channelUnit=_channelUnit;
- (void).cxx_destruct;
- (BOOL)shouldDisable:(id)arg1;
- (void)sendCustomPropertiesLog:(id)arg1;
- (void)sendStartServiceLog:(id)arg1;
- (BOOL)canBeUsed;
@property(readonly, nonatomic) NSUUID *installId; // @synthesize installId=_installId;
- (void)initializeChannelGroup;
- (void)applyPipelineEnabledState:(BOOL)arg1;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
- (void)setCustomProperties:(id)arg1;
- (void)setUserId:(id)arg1;
- (void)setMaxStorageSize:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(copy) NSString *logUrl; // @synthesize logUrl=_logUrl;
- (BOOL)startService:(Class)arg1 withAppSecret:(id)arg2 transmissionTargetToken:(id)arg3 andSendLog:(BOOL)arg4 fromApplication:(BOOL)arg5;
- (id)sortServices:(id)arg1;
- (void)start:(id)arg1 withServices:(id)arg2 fromApplication:(BOOL)arg3;
- (BOOL)configureWithAppSecret:(id)arg1 transmissionTargetToken:(id)arg2 fromApplication:(BOOL)arg3;
- (id)init;

@end

