//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MSCustomProperties : NSObject
{
    NSMutableDictionary *_properties;
}

@property(retain, nonatomic) NSMutableDictionary *properties; // @synthesize properties=_properties;
- (void).cxx_destruct;
- (id)propertiesImmutableCopy;
- (BOOL)isValidValue:(id)arg1;
- (BOOL)isValidKey:(id)arg1;
- (id)clearPropertyForKey:(id)arg1;
- (id)setObject:(id)arg1 forKey:(id)arg2;
- (id)setDate:(id)arg1 forKey:(id)arg2;
- (id)setBool:(BOOL)arg1 forKey:(id)arg2;
- (id)setNumber:(id)arg1 forKey:(id)arg2;
- (id)setString:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

