//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface MSEncrypter : NSObject
{
    BOOL _cryptorCreated;
    NSData *_key;
    struct _CCCryptor *_encryptorObject;
    struct _CCCryptor *_decryptorObject;
}

+ (id)generateKeyWithTag:(id)arg1;
+ (id)loadKeyFromKeychainWithTag:(id)arg1;
+ (void)deleteKeyWithTag:(id)arg1;
@property(nonatomic) BOOL cryptorCreated; // @synthesize cryptorCreated=_cryptorCreated;
@property(nonatomic) struct _CCCryptor *decryptorObject; // @synthesize decryptorObject=_decryptorObject;
@property(nonatomic) struct _CCCryptor *encryptorObject; // @synthesize encryptorObject=_encryptorObject;
@property(retain, nonatomic) NSData *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)decryptString:(id)arg1;
- (id)encryptString:(id)arg1;
- (void)dealloc;
- (void)createCryptorContexts:(id)arg1;
- (id)initWitKeyTag:(id)arg1;

@end

