//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSIngestionUtil : NSObject
{
}

+ (id)hideSecret:(id)arg1;
+ (BOOL)isRequestCanceledError:(id)arg1;
+ (BOOL)isSSLConnectionError:(id)arg1;
+ (BOOL)isNoInternetConnectionError:(id)arg1;
+ (long long)getStatusCode:(id)arg1;
+ (BOOL)isRecoverableError:(long long)arg1;

@end

