//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol MSIngestionProtocol;

@protocol MSIngestionDelegate <NSObject>

@optional
- (void)ingestionDidReceiveFatalError:(id <MSIngestionProtocol>)arg1;
- (void)ingestionDidResume:(id <MSIngestionProtocol>)arg1;
- (void)ingestionDidPause:(id <MSIngestionProtocol>)arg1;
@end

