//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSChannelDelegate-Protocol.h"

@class MSOneCollectorIngestion, NSMutableDictionary, NSString, NSUUID;

@interface MSOneCollectorChannelDelegate : NSObject <MSChannelDelegate>
{
    NSMutableDictionary *_oneCollectorChannels;
    MSOneCollectorIngestion *_oneCollectorIngestion;
    NSMutableDictionary *_epochsAndSeqsByIKey;
    NSUUID *_installId;
}

@property(retain, nonatomic) NSUUID *installId; // @synthesize installId=_installId;
@property(retain, nonatomic) NSMutableDictionary *epochsAndSeqsByIKey; // @synthesize epochsAndSeqsByIKey=_epochsAndSeqsByIKey;
@property(retain, nonatomic) MSOneCollectorIngestion *oneCollectorIngestion; // @synthesize oneCollectorIngestion=_oneCollectorIngestion;
@property(retain, nonatomic) NSMutableDictionary *oneCollectorChannels; // @synthesize oneCollectorChannels=_oneCollectorChannels;
- (void).cxx_destruct;
- (BOOL)validateLogName:(id)arg1;
- (BOOL)validateLog:(id)arg1;
- (BOOL)shouldSendLogToOneCollector:(id)arg1;
- (BOOL)isOneCollectorGroup:(id)arg1;
- (void)channel:(id)arg1 didResumeWithIdentifyingObject:(id)arg2;
- (void)channel:(id)arg1 didPauseWithIdentifyingObject:(id)arg2;
- (void)channel:(id)arg1 didSetEnabled:(BOOL)arg2 andDeleteDataOnDisabled:(BOOL)arg3;
- (BOOL)channelUnit:(id)arg1 shouldFilterLog:(id)arg2;
- (void)channel:(id)arg1 didPrepareLog:(id)arg2 internalId:(id)arg3 flags:(unsigned long long)arg4;
- (void)channel:(id)arg1 prepareLog:(id)arg2;
- (void)channelGroup:(id)arg1 didAddChannelUnit:(id)arg2;
- (id)initWithInstallId:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

