//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSUserDefaults : NSObject
{
}

+ (id)shared;
- (BOOL)updateObject:(id)arg1 forKey:(id)arg2;
- (BOOL)updateObject:(id)arg1 forKey:(id)arg2 expiration:(float)arg3;
- (id)updateDictionary:(id)arg1 forKey:(id)arg2;
- (id)updateDictionary:(id)arg1 forKey:(id)arg2 expiration:(float)arg3;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;

@end

