//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MSUserIdHistoryInfo, NSMutableArray;

@interface MSUserIdContext : NSObject
{
    MSUserIdHistoryInfo *_currentUserIdInfo;
    NSMutableArray *_userIdHistory;
}

+ (id)prefixedUserIdFromUserId:(id)arg1;
+ (BOOL)isUserIdValidForOneCollector:(id)arg1;
+ (BOOL)isUserIdValidForAppCenter:(id)arg1;
+ (void)resetSharedInstance;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *userIdHistory; // @synthesize userIdHistory=_userIdHistory;
@property(retain, nonatomic) MSUserIdHistoryInfo *currentUserIdInfo; // @synthesize currentUserIdInfo=_currentUserIdInfo;
- (void).cxx_destruct;
- (void)clearUserIdHistory;
- (id)userIdAt:(id)arg1;
- (void)setUserId:(id)arg1;
- (id)userId;
- (id)init;

@end

