//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSApplication.h>

@class NSDictionary;

@interface NSApplication (izGctaiJPX)
+ (void)setPublicKeyWithString:(id)arg1;
- (id)valueForKey:(id)arg1;
@property(readonly, nonatomic) BOOL IcSU9NLYZQKD4gE; // @dynamic IcSU9NLYZQKD4gE;
@property(readonly, nonatomic) NSDictionary *MYJh8blWOIN1X2;
- (BOOL)qlQQY7eIddUl6;
- (void)activateWithInfo:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(nonatomic) unsigned long long sx7dtvOQOpvw2pFQd; // @dynamic sx7dtvOQOpvw2pFQd;
@end

