//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSBundle.h>

@class NSString;

@interface NSBundle (Reveal)
@property(nonatomic, readonly) NSString *localizedBundleName;
@property(nonatomic, readonly) NSString *bundleShortVersionStringWithoutBuildNumbers;
@property(nonatomic, readonly) NSString *bundleShortVersionString;
@property(nonatomic, readonly) NSString *bundleVersion;
@property(nonatomic, readonly) NSString *bundleName;
@end

