//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal4)
+ (id)iba_propertyInspectorTabBarIconSelectedColor;
+ (id)iba_propertyInspectorTabBarIconHighlightedColor;
+ (id)iba_propertyInspectorTabBarIconDisabledColor;
+ (id)iba_propertyInspectorTabBarIconColor;
+ (id)iba_propertyInspectorTabBarSelectedBackgroundColor;
+ (id)iba_propertyInspectorTabBarBackgroundColor;
+ (id)iba_propertyInspectorScopeHoveringTextColor;
+ (id)iba_propertyInspectorScopeHighlightedTextColor;
+ (id)iba_propertyInspectorScopeTextColor;
+ (id)iba_propertyInspectorScopeSelectedBackgroundColor;
+ (id)iba_propertyInspectorScopeHoveringBackgroundColor;
+ (id)iba_propertyInspectorScopeHighlightedBackgroundColor;
+ (id)iba_propertyInspectorScopeNormalBackgroundColor;
+ (id)iba_propertyInspectorActionButtonSelectedColor;
+ (id)iba_propertyInspectorActionButtonHighlightedColor;
+ (id)iba_propertyInspectorActionButtonDisabledColor;
+ (id)iba_propertyInspectorActionButtonColor;
+ (id)iba_propertyInspectorSectionHeaderTextColor;
+ (id)iba_propertyInspectorValueTextColor;
+ (id)iba_propertyInspectorTextFieldStrokeColor;
+ (id)iba_propertyInspectorTextFieldBackgroundColor;
+ (id)iba_propertyInspectorLabelTextColor;
+ (id)iba_propertyInspectorDividerColor;
+ (id)iba_propertyInspectorHeaderBackgroundColor;
@end

