//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal9)
+ (id)iba_splitViewDividerColor;
+ (id)iba_baseToolbarBackgroundColor;
+ (id)iba_baseContentDividerColor;
+ (id)iba_baseContentBackgroundColor;
@end

