//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal6)
+ (id)iba_focusHistoryPathComponentSeparatorColor;
+ (id)iba_focusHistorySegmentedButtonHighlightedIconColor;
+ (id)iba_focusHistorySegmentedButtonDisabledIconColor;
+ (id)iba_focusHistorySegmentedButtonIconColor;
+ (id)iba_focusHistoryPathComponentPlaceholderTextColor;
+ (id)iba_focusHistoryPathComponentTextHighlightedColor;
+ (id)iba_focusHistoryPathComponentTextColor;
+ (id)iba_focusHistoryPathComponentDividerColor;
+ (id)iba_focusHistoryPathComponentBackgroundColor;
@end

