//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal2)
+ (id)iba_preferencesProgressIndicatorTextRightColor;
+ (id)iba_preferencesProgressIndicatorTextLeftColor;
+ (id)iba_preferencesProgressIndicatorBarFillColor;
+ (id)iba_preferencesProgressIndicatorBarBackgroundColor;
+ (id)iba_preferencesHeaderTextEmphasizedColor;
+ (id)iba_preferencesHeaderTextNormalColor;
@end

