//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal5)
+ (id)iba_canvasAlignmentRectLineColor;
+ (id)iba_canvasWireframeGuideColor;
+ (id)iba_canvasWireframeViewTooLargeErrorDimmedColor;
+ (id)iba_canvasWireframeViewTooLargeErrorSelectedColor;
+ (id)iba_canvasWireframeViewTooLargeErrorHighlightedColor;
+ (id)iba_canvasWireframeViewTooLargeErrorColor;
+ (id)iba_canvasWireframeGenericErrorDimmedColor;
+ (id)iba_canvasWireframeGenericErrorSelectedColor;
+ (id)iba_canvasWireframeGenericErrorHighlightedColor;
+ (id)iba_canvasWireframeGenericErrorColor;
+ (id)iba_canvasWireframeDimmedColor;
+ (id)iba_canvasWireframeEmphasizedHighlightedColor;
+ (id)iba_canvasWireframeEmphasizedColor;
+ (id)iba_canvasWireframeSelectedColor;
+ (id)iba_canvasWireframeHighlightedColor;
+ (id)iba_canvasWireframeColor;
+ (id)iba_canvasViewTooLargeErrorSelectedTintColor;
+ (id)iba_canvasViewTooLargeErrorTintColor;
+ (id)iba_canvasGenericErrorSelectedTintColor;
+ (id)iba_canvasGenericErrorTintColor;
+ (id)iba_canvasSelectedEmphasizedTintColor;
+ (id)iba_canvasSelectedTintColor;
+ (id)iba_canvasFalloffTintColor;
+ (id)iba_canvasBrokenConstraintLinesColor;
+ (id)iba_canvasSystemConstraintLinesColor;
+ (id)iba_canvasUserConstraintLinesColor;
+ (id)iba_canvasAlignmentLinesColor;
+ (id)iba_canvasBackgroundGradientBottomColor;
+ (id)iba_canvasBackgroundGradientTopColor;
@end

