//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal3)
+ (id)iba_hierarchyOutlineViewScrollBackgroundColor;
+ (id)iba_hierarchyOutlineViewHighlightBackgroundStrokeColor;
+ (id)iba_hierarchyOutlineViewHighlightBackgroundColor;
+ (id)iba_hierarchyOutlineViewInactiveSelectionBackgroundColor;
+ (id)iba_hierarchyOutlineViewSelectionBackgroundColor;
+ (id)iba_hierarchyOutlineViewBackgroundMatchFilterColor;
+ (id)iba_hierarchyOutlineViewMatchFilterBackgroundColor;
+ (id)iba_hierarchyOutlineViewMatchFilterTextColor;
+ (id)iba_hierarchyOutlineViewTextHighlightedDisabledColor;
+ (id)iba_hierarchyOutlineViewTextHighlightedColor;
+ (id)iba_hierarchyOutlineViewTextSelectedDisabledColor;
+ (id)iba_hierarchyOutlineViewTextSelectedColor;
+ (id)iba_hierarchyOutlineViewTextDisabledColor;
+ (id)iba_hierarchyOutlineViewTextColor;
+ (id)iba_hierarchyOutlineViewDividerColor;
+ (id)iba_hierarchyOutlineViewBackgroundColor;
@end

