//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (Reveal10)
+ (id)iba_canvasBitmapErrorToastViewTooLargeBorderColor;
+ (id)iba_canvasBitmapErrorToastGenericBorderColor;
+ (id)iba_canvasBitmapErrorToastTextShadowColor;
+ (id)iba_canvasBitmapErrorToastTextColor;
+ (id)iba_canvasBitmapErrorToastBackgroundColor;
+ (id)iba_canvasToastTextColor;
+ (id)iba_canvasToastBackgroundColor;
+ (id)iba_canvasSliderMaximumTrackTintColor;
+ (id)iba_canvasSliderMinimumTrackTintColor;
+ (id)iba_canvasButtonToggleOnTintColor;
+ (id)iba_canvasButtonToggleOffTintColor;
+ (id)iba_canvasButtonHighlightedTintColor;
+ (id)iba_canvasButtonNormalTintColor;
+ (id)iba_canvasSegmentedControlSelectedTintColor;
+ (id)iba_canvasSegmentedControlHighlightedTintColor;
+ (id)iba_canvasSegmentedControlNormalTintColor;
+ (id)iba_canvasBottomBarBorderColor;
+ (id)iba_canvasBottomBarFillColor;
@end

