//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (Reveal)
- (BOOL)fileExistsAtURL:(id)arg1;
- (BOOL)directoryExistsAtURL:(id)arg1;
- (id)applicationCachesDirectory;
- (id)applicationSupportDirectory;
- (id)findOrCreateDirectory:(unsigned long long)arg1 inDomain:(unsigned long long)arg2 appendPathComponent:(id)arg3 error:(id *)arg4;
@end

