//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@class NSURL;

@interface NSFileManager (Reveal)
- (BOOL)fileExistsAt:(id)arg1;
- (BOOL)directoryExistsAt:(id)arg1;
@property(nonatomic, readonly) NSURL *cachesDirectory;
@property(nonatomic, readonly) NSURL *applicationSupportDirectory;
@end

