//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (MSUtility_StringFormatting)
+ (id)prettyPrintJson:(id)arg1;
+ (id)targetKeyFromTargetToken:(id)arg1;
+ (id)iKeyFromTargetToken:(id)arg1;
+ (id)transmissionTargetTokenFrom:(id)arg1;
+ (id)appSecretFrom:(id)arg1;
+ (id)sha256:(id)arg1;
@end

