//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURLSession.h>

@interface NSURLSession (Reveal)
- (void)cancelPendingRequestsForURL:(id)arg1 method:(id)arg2 passingTest:(CDUnknownBlockType)arg3;
- (void)cancelPendingRequestsForURL:(id)arg1 method:(id)arg2;
- (void)cancelAllPendingRequests;
- (id)jsonTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)imageDataTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)imageTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@end

