//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  4 2018 10:55:41).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (MapKit)
+ (id)iba_valueWithMapSize:(CDStruct_c3b9c2ee)arg1;
+ (id)iba_valueWithMapRect:(CDStruct_90e2a262)arg1;
+ (id)iba_valueWithMapPoint:(CDStruct_c3b9c2ee)arg1;
+ (id)iba_valueWithMapCoordinateRegion:(CDStruct_2b0c6e0b)arg1;
@property(readonly) CDStruct_c3b9c2ee iba_mapSizeValue;
@property(readonly) CDStruct_90e2a262 iba_mapRectValue;
@property(readonly) CDStruct_c3b9c2ee iba_mapPointValue;
@property(readonly) CDStruct_2b0c6e0b iba_mapCoordinateRegion;
@end

